# Generated by Django 5.1.1 on 2024-11-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminio", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("companyio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="permission",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminio.role",
            ),
        ),
    ]
