# Generated by Django 5.1.1 on 2024-11-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminio', '0002_companyrole'),
        ('companyio', '0002_companyuser_permission_companyuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminio.companyrole'),
        ),
    ]
