# Generated by Django 5.1.1 on 2025-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0005_companysetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='multi_currency',
        ),
        migrations.AddField(
            model_name='companysetting',
            name='is_organized_job_related_activity',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
