# Generated by Django 5.1.1 on 2025-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0007_companysetting_multi_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kind',
            field=models.CharField(default='CONSTRUCTION', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='kind',
            field=models.CharField(default='CONSTRUCTION', max_length=20),
        ),
    ]
