# Generated by Django 5.1.1 on 2025-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0008_company_kind_historicalcompany_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='CONSTRUCTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='kind',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='CONSTRUCTION', max_length=20),
        ),
    ]
