# Generated by Django 5.1.1 on 2025-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0009_alter_company_kind_alter_historicalcompany_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('PROPERTY_BOOKKEEPING', 'Property Bookkeeping'), ('REAL_ESTATE', 'Real Estate Company'), ('ECOMMERCE', 'E-commerce'), ('FASHION_APPAREL', 'Fashion and Apparel Industry'), ('FOOD_BEVERAGE', 'Food and Beverage Industry'), ('HARDWARE_ELECTRONICS', 'Hardware and Electronics Industry'), ('LEGAL_BOOKKEEPING', 'Legal Bookkeeping'), ('AGRICULTURE', 'Agriculture Industry'), ('AUTOMOBILE', 'Automobile Industry'), ('EDUCATION_TRAINING', 'Education and Training Industry'), ('RESTAURANT_HOTEL', 'Restaurant and Hotel Business'), ('SPORTS_FITNESS', 'Sports and Fitness Industry'), ('TRAVEL_TOURISM', 'Travel and Tourism Industry'), ('RETAIL_WHOLESALE', 'Retail and Wholesale Industry'), ('MEDICAL_PHARMACEUTICAL', 'Medical and Pharmaceutical Industry'), ('MARKETING_ADVERTISING', 'Marketing and Advertising Industry'), ('FINANCIAL_SERVICES', 'Financial Services Industry'), ('BUSINESS_CONSULTING', 'Business Services and Consulting Industry'), ('BROKERAGE_HOUSE', 'Brokerage House')], default='CONSTRUCTION', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='kind',
            field=models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('PROPERTY_BOOKKEEPING', 'Property Bookkeeping'), ('REAL_ESTATE', 'Real Estate Company'), ('ECOMMERCE', 'E-commerce'), ('FASHION_APPAREL', 'Fashion and Apparel Industry'), ('FOOD_BEVERAGE', 'Food and Beverage Industry'), ('HARDWARE_ELECTRONICS', 'Hardware and Electronics Industry'), ('LEGAL_BOOKKEEPING', 'Legal Bookkeeping'), ('AGRICULTURE', 'Agriculture Industry'), ('AUTOMOBILE', 'Automobile Industry'), ('EDUCATION_TRAINING', 'Education and Training Industry'), ('RESTAURANT_HOTEL', 'Restaurant and Hotel Business'), ('SPORTS_FITNESS', 'Sports and Fitness Industry'), ('TRAVEL_TOURISM', 'Travel and Tourism Industry'), ('RETAIL_WHOLESALE', 'Retail and Wholesale Industry'), ('MEDICAL_PHARMACEUTICAL', 'Medical and Pharmaceutical Industry'), ('MARKETING_ADVERTISING', 'Marketing and Advertising Industry'), ('FINANCIAL_SERVICES', 'Financial Services Industry'), ('BUSINESS_CONSULTING', 'Business Services and Consulting Industry'), ('BROKERAGE_HOUSE', 'Brokerage House')], default='CONSTRUCTION', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=50),
        ),
    ]
