# Generated by Django 5.1.1 on 2025-03-18 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0010_alter_company_kind_alter_company_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companyio.company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
