# Generated by Django 5.1.1 on 2025-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0012_alter_companyuser_company_alter_companyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
