# Generated by Django 5.1.1 on 2025-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0013_alter_company_time_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='company_address',
        ),
        migrations.AddField(
            model_name='company',
            name='company_addresses',
            field=models.JSONField(blank=True, default=dict, help_text='JSON encoded keyword arguments(Example: {"address": "address", "city": "city", "state": "state", "country": "country", "zip_code": "zip_code"}),'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='company_addresses',
            field=models.JSONField(blank=True, default=dict, help_text='JSON encoded keyword arguments(Example: {"address": "address", "city": "city", "state": "state", "country": "country", "zip_code": "zip_code"}),'),
        ),
    ]
