# Generated by Django 5.1.1 on 2025-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0014_remove_company_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyshift',
            name='grace_time',
        ),
        migrations.AddField(
            model_name='companyshift',
            name='grace_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='companyshift',
            name='lunch_time',
        ),
        migrations.AddField(
            model_name='companyshift',
            name='lunch_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='companyshift',
            name='regular_hour',
        ),
        migrations.AddField(
            model_name='companyshift',
            name='regular_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='companyshift',
            name='tiffin_time',
        ),
        migrations.AddField(
            model_name='companyshift',
            name='tiffin_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historicalcompanyshift',
            name='grace_time',
        ),
        migrations.AddField(
            model_name='historicalcompanyshift',
            name='grace_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historicalcompanyshift',
            name='lunch_time',
        ),
        migrations.AddField(
            model_name='historicalcompanyshift',
            name='lunch_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historicalcompanyshift',
            name='regular_hour',
        ),
        migrations.AddField(
            model_name='historicalcompanyshift',
            name='regular_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='historicalcompanyshift',
            name='tiffin_time',
        ),
        migrations.AddField(
            model_name='historicalcompanyshift',
            name='tiffin_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
