# Generated by Django 5.1.1 on 2025-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0015_alter_companyshift_grace_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydesignation',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanydesignation',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
