# Generated by Django 5.1.1 on 2026-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0020_remove_company_legal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether the user pinned this company to the top of their workspace switcher.'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, help_text="When the user last selected/entered this company. Drives the 'last opened' sort and label.", null=True),
        ),
    ]
