# Generated by Django 5.1.1 on 2026-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0023_enable_rls_core_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companydesignation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='companydesignation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('company', 'title'), name='uniq_active_designation_company_title'),
        ),
    ]
