"""Bring `supplierio_supplier` under Row-Level Security.

`0023_enable_rls_core_tables` took the five tables that were the obvious tenant
data at the time -- customer, product, sale, purchase, chart of account. Supplier
was not on that list, and the omission is load-bearing rather than cosmetic
because **customer and supplier are handled identically at the application layer
and differently at the database.**

Every writable supplier picker resolves a client-supplied `uid` against a
queryset with no company filter:

    supplier_uid = SlugRelatedField(
        slug_field="uid",
        queryset=Supplier.objects.filter(status=SupplierStatusChoices.ACTIVE),
        write_only=True,
    )                            -- weapi/django_rest/serializers/purchases.py:130

Fourteen such pickers exist across bills, bill payments, credit notes, recurring
templates, bank rules, products and journal entries. The customer fields beside
them are written the same way -- `journalio/.../serializers/common.py:57-58` has
an unscoped `supplier` and a `customer` on adjacent lines -- but
`customerio_customer` carries this policy and `supplierio_supplier` does not. So
the customer half of that hole is closed at the database and the supplier half is
open at both layers.

The companion serializer-layer fix ships alongside this. Neither is sufficient
alone: the mixin can be forgotten on the next serializer someone writes, and RLS
is permissive whenever a request carries no company (see `common/db/rls.py`), so
each covers the other's gap.

Additive and reversible. The policy is the same one the other five tables carry,
generated by the same builders, so there is one definition of "tenant isolation"
in the schema rather than two.
"""

from django.db import migrations

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

RLS_TABLES = ["supplierio_supplier"]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    dependencies = [
        ("companyio", "0024_alter_companydesignation_unique_together_and_more"),
        ("supplierio", "0005_alter_supplier_billing_rate_and_more"),
    ]

    operations = [
        migrations.RunPython(apply_rls, remove_rls),
    ]
