# Generated by Django 5.1.1 on 2026-07-02 06:50

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

# New tenant tables (each carries a company_id) get the same tenant-isolation
# RLS policy as the core tables; see common/db/rls.py. No-op off PostgreSQL.
RLS_TABLES = [
    "recurringio_recurringtemplate",
    "recurringio_recurringtemplateline",
    "recurringio_recurringoccurrence",
]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('agencyio', '0010_agency_state'),
        ('companyio', '0023_enable_rls_core_tables'),
        ('customerio', '0008_customer_charter_account'),
        ('employeeio', '0001_initial'),
        ('productio', '0010_alter_productadditionalcost_prefferred_supplier_and_more'),
        ('purchaseio', '0023_alter_paybill_email_alter_purchase_email_and_more'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
        ('termio', '0005_termconnector_purchase'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('txn_type', models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense')], default='BILL', max_length=20)),
                ('template_type', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('REMINDER', 'Reminder'), ('UNSCHEDULED', 'Unscheduled')], default='SCHEDULED', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('autopay_enabled', models.BooleanField(default=False)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('create_days_in_advance', models.PositiveIntegerField(blank=True, null=True)),
                ('remind_days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20, null=True)),
                ('interval_count', models.PositiveIntegerField(default=1)),
                ('day_mode', models.CharField(blank=True, choices=[('DAY_OF_MONTH', 'Day of month'), ('WEEKDAY', 'Weekday of month')], max_length=20, null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveIntegerField(blank=True, null=True)),
                ('ordinal', models.CharField(blank=True, choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth'), ('LAST', 'Last')], max_length=10, null=True)),
                ('month_of_year', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_type', models.CharField(choices=[('NONE', 'Never'), ('BY_DATE', 'By date'), ('AFTER_COUNT', 'After N occurrences')], default='NONE', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_after_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_run_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField(blank=True, null=True)),
                ('occurrences_generated', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplierio.supplier')),
                ('terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termio.term')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecurringTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_type', models.CharField(choices=[('CATEGORY', 'Category'), ('ITEM', 'Item')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=19, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=19, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('is_billable', models.BooleanField(default=False)),
                ('charter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerio.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productio.product')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyio.agencytax')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='recurringio.recurringtemplate')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecurringOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_date', models.DateField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('REMINDED', 'Reminded'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=20)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('generated_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrences', to='purchaseio.purchase')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='recurringio.recurringtemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'occurrence_date'), name='unique_recurring_occurrence_per_template_date')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
