# Generated by Django 5.1.1 on 2026-07-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('paymentio', '0008_paymentinformation_stripe_invoice_id_and_more'),
        ('recurringio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payment_templates', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentio.paymentmethod'),
        ),
    ]
