# Generated by Django 5.1.1 on 2026-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0002_recurringtemplate_payment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='permit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='print_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque')], default='BILL', max_length=20),
        ),
    ]
