# Generated by Django 5.1.1 on 2026-07-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerio', '0008_customer_charter_account'),
        ('recurringio', '0003_recurringtemplate_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='auto_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='customerio.customer'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='email_bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='email_cc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='email_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='message_on_estimate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate')], default='BILL', max_length=20),
        ),
    ]
