# Generated by Django 5.1.1 on 2026-07-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0010_agency_state'),
        ('recurringio', '0004_recurringtemplate_auto_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='statement_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_document_templates', to='agencyio.agencytax'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='tax_kind',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt')], default='BILL', max_length=20),
        ),
    ]
