# Generated by Django 5.1.1 on 2026-07-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0005_recurringtemplate_reference_number_and_more'),
        ('salesio', '0038_sale_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringoccurrence',
            name='generated_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrences', to='salesio.sale'),
        ),
    ]
