# Generated by Django 5.1.1 on 2026-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0006_recurringoccurrence_generated_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='expiry_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
