# Generated by Django 5.1.1 on 2026-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0007_recurringtemplate_expiry_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtemplate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
    ]
