# Generated by Django 5.1.1 on 2026-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0008_alter_recurringtemplate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='acceptance_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='when_to_charge',
            field=models.CharField(choices=[('FUTURE', 'On the schedule'), ('ACCEPT', 'When the customer accepts')], default='FUTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment')], default='BILL', max_length=20),
        ),
    ]
