# Generated by Django 5.1.1 on 2026-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0009_recurringtemplate_acceptance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='deposit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='discount_kind',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='PERCENTAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='include_unbilled_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='payment_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice')], default='BILL', max_length=20),
        ),
    ]
