# Generated by Django 5.1.1 on 2026-07-27 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerio', '0008_customer_charter_account'),
        ('recurringio', '0010_recurringtemplate_deposit_recurringtemplate_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='full_shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='ship_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_ship_to_templates', to='customerio.customer'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='shipping_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase order')], default='BILL', max_length=20),
        ),
    ]
