# Generated by Django 5.1.1 on 2026-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0011_recurringtemplate_full_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='shipping_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase order'), ('SALES_RECEIPT', 'Sales receipt')], default='BILL', max_length=20),
        ),
    ]
