# Generated by Django 5.1.1 on 2026-07-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('paymentio', '0008_paymentinformation_stripe_invoice_id_and_more'),
        ('recurringio', '0012_recurringtemplate_shipping_from_and_more'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='cash_back_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_cash_back_templates', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='cash_back_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='cash_back_memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplate',
            name='track_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtemplateline',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentio.paymentmethod'),
        ),
        migrations.AddField(
            model_name='recurringtemplateline',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recurringtemplateline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_template_lines', to='supplierio.supplier'),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase order'), ('SALES_RECEIPT', 'Sales receipt'), ('DEPOSIT', 'Bank deposit')], default='BILL', max_length=20),
        ),
    ]
