# Generated by Django 5.1.1 on 2026-07-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0013_recurringtemplate_cash_back_account_and_more'),
        ('transactionio', '0013_transactioninformation_matched_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringoccurrence',
            name='generated_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrences', to='transactionio.bankdeposit'),
        ),
    ]
