# Generated by Django 5.1.1 on 2026-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0014_recurringoccurrence_generated_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtemplate',
            name='txn_type',
            field=models.CharField(choices=[('BILL', 'Bill'), ('EXPENSE', 'Expense'), ('CHEQUE', 'Cheque'), ('ESTIMATE', 'Estimate'), ('REFUND_RECEIPT', 'Refund receipt'), ('PAYMENT', 'Payment'), ('INVOICE', 'Invoice'), ('PURCHASE_ORDER', 'Purchase order'), ('SALES_RECEIPT', 'Sales receipt'), ('DEPOSIT', 'Bank deposit'), ('CREDIT_MEMO', 'Credit memo')], default='BILL', max_length=20),
        ),
    ]
