# Generated by Django 5.1.1 on 2026-07-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0012_creditnote_credit_note_sales_tax'),
        ('recurringio', '0015_alter_recurringtemplate_txn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringoccurrence',
            name='generated_credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_occurrences', to='creditnoteio.creditnote'),
        ),
    ]
