# Generated by Django 5.1.1 on 2024-11-21 09:32

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import journalio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicaluser_is_admin_user_is_admin'),
        ('customerio', '0001_initial'),
        ('journalio', '0001_initial'),
        ('supplierio', '0001_initial'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=journalio.django_rest.helpers.slug_helpers.get_journal_entry_connector_slug, unique=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('kind', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journalio.journalentry')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
                ('warehose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
