# Generated by Django 5.1.1 on 2024-11-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0003_alter_companyuser_role'),
        ('journalio', '0002_journalentryconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
            preserve_default=False,
        ),
    ]
