# Generated by Django 5.1.1 on 2024-11-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencyio", "0002_agency_start_of_period"),
        ("journalio", "0003_journalentry_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentryconnector",
            name="tax",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="agencyio.agencytax",
            ),
        ),
    ]
