# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0004_journalentryconnector_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journalentryconnector',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journalentryconnector',
            name='debit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
