# Generated by Django 5.1.1 on 2025-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0006_journalentry_request_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('JOURNAL_ENTRY', 'Journal Entry'), ('TRANSACTION', 'Transaction')], default='JOURNAL_ENTRY', max_length=50),
        ),
    ]
