# Generated by Django 5.1.1 on 2025-03-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0007_journalentry_kind'),
        ('purchaseio', '0019_alter_paybill_email'),
        ('salesio', '0021_alter_sale_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='request_kind',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='model_kind',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='pay_bill',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='purchase_payment',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='sale_payment_receive',
        ),
        migrations.RemoveField(
            model_name='journalentryconnector',
            name='sale_receipt',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.expense'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_journal_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='model_kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive')], default='PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='pay_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.paybill'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='purchase_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.sale'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sale_payment_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salepaymentreceive'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sale_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salereceipt'),
        ),
        migrations.AddField(
            model_name='journalentryconnector',
            name='request_kind',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('RECOVERED', 'Recovered')], default='CREATED', max_length=50),
        ),
    ]
