# Generated by Django 5.1.1 on 2025-03-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0008_remove_journalentry_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='model_kind',
            new_name='kind',
        ),
    ]
