# Generated by Django 5.1.1 on 2025-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0009_rename_model_kind_journalentry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='last_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
