# Generated by Django 5.1.1 on 2025-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0010_journalentryconnector_last_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
