# Generated by Django 5.1.1 on 2025-03-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0011_journalentryconnector_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='journalio.journalentryconnector'),
        ),
    ]
