# Generated by Django 5.1.1 on 2025-03-28 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0009_alter_employeesalary_basic_alter_employeesalary_cash_and_more'),
        ('journalio', '0012_journalentryconnector_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employeeio.employee'),
        ),
    ]
