# Generated by Django 5.1.1 on 2025-04-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0009_creditnote_total_tax'),
        ('journalio', '0013_journalentryconnector_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote'),
        ),
    ]
