# Generated by Django 5.1.1 on 2025-04-17 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0014_journalentry_credit_note'),
        ('stockio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='stock_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockio.stockadjustment'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive')], default='PURCHASE', max_length=50),
        ),
    ]
