# Generated by Django 5.1.1 on 2025-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0015_journalentry_stock_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
