# Generated by Django 5.1.1 on 2025-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0016_journalentryconnector_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
