# Generated by Django 5.1.1 on 2025-04-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0020_journalentry_priduct_alter_journalentry_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='priduct',
            new_name='product',
        ),
    ]
