# Generated by Django 5.1.1 on 2025-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0021_rename_priduct_journalentry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('CHEQUE', 'Cheque'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('REFUND_RECEIPT', 'Refund Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT_PRURCHASE', 'Product Purchase'), ('CHART_OF_ACCOUNT', 'Chart Of Account')], default='PURCHASE', max_length=50),
        ),
    ]
