# Generated by Django 5.1.1 on 2025-05-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0022_alter_journalentry_kind'),
        ('salesio', '0022_alter_salereceipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='saleitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.saleitem'),
        ),
    ]
