# Generated by Django 5.1.1 on 2025-05-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0023_journalentryconnector_saleitem'),
        ('purchaseio', '0021_purchaseitem_opening_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchaseitem'),
        ),
    ]
