# Generated by Django 5.1.1 on 2025-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0024_journalentryconnector_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='sale_receipt',
        ),
    ]
