# Generated by Django 5.1.1 on 2025-06-17 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0025_remove_journalentry_sale_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
