# Generated by Django 5.1.1 on 2025-06-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0011_alter_creditnote_email'),
        ('journalio', '0026_journalentryconnector_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='credit_note_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
    ]
