# Generated by Django 5.1.1 on 2025-07-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0027_journalentryconnector_credit_note_item'),
        ('transactionio', '0010_transactioninformation_is_matched_bankdeposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionio.bankdeposit'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('CHEQUE', 'Cheque'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('REFUND_RECEIPT', 'Refund Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT_PRURCHASE', 'Product Purchase'), ('CHART_OF_ACCOUNT', 'Chart Of Account'), ('BANK_DEPOSIT', 'Bank Deposit')], default='PURCHASE', max_length=50),
        ),
    ]
