# Generated by Django 5.1.1 on 2025-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0028_journalentry_bank_deposit_journalentry_is_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='is_customer_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
