# Generated by Django 5.1.1 on 2025-07-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0029_journalentryconnector_is_customer_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentryconnector',
            old_name='is_customer_transaction',
            new_name='is_customer_or_supplier_transaction',
        ),
    ]
