# Generated by Django 5.1.1 on 2025-07-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0042_rename_is_joind_employee_is_joined'),
        ('journalio', '0030_rename_is_customer_transaction_journalentryconnector_is_customer_or_supplier_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryconnector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee'),
        ),
    ]
