# Generated by Django 5.1.1 on 2025-09-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
        ('journalio', '0031_alter_journalentryconnector_created_by'),
        ('payrollio', '0029_payrollcontactinfosetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='payroll_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollio.payrollsalaryprocess'),
        ),
        migrations.AddField(
            model_name='journalentryconnector',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_journal_entry_connector_set', to='employeeio.employee'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('CHEQUE', 'Cheque'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('REFUND_RECEIPT', 'Refund Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT_PRURCHASE', 'Product Purchase'), ('CHART_OF_ACCOUNT', 'Chart Of Account'), ('BANK_DEPOSIT', 'Bank Deposit'), ('PAYROLL_SALARY_PROCESS', 'Payroll Salary Process')], default='PURCHASE', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentryconnector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_journal_entry_connector_set', to='employeeio.employee'),
        ),
    ]
