# Generated by Django 5.1.1 on 2025-10-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0033_journalentry_tax_payment_alter_journalentry_kind'),
        ('salesio', '0034_salestax'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sales_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesio.salestax'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('CHEQUE', 'Cheque'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('REFUND_RECEIPT', 'Refund Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT_PRURCHASE', 'Product Purchase'), ('CHART_OF_ACCOUNT', 'Chart Of Account'), ('BANK_DEPOSIT', 'Bank Deposit'), ('PAYROLL_SALARY_PROCESS', 'Payroll Salary Process'), ('PAYROLL_TAX_PAYMENT', 'Payroll Tax Payment'), ('SALES_TAX', 'Sales Tax')], default='PURCHASE', max_length=50),
        ),
    ]
