# Generated by Django 5.1.15 on 2026-08-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('journalio', '0034_journalentry_sales_tax_alter_journalentry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryconnector',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.chartofaccount'),
        ),
    ]
