# Generated by Django 5.1.15 on 2026-08-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0013_alter_creditnoteitem_tax'),
        ('journalio', '0035_alter_journalentryconnector_account'),
        ('purchaseio', '0025_alter_purchaseitem_tax'),
        ('salesio', '0040_alter_saleitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryconnector',
            name='credit_note_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='journalentryconnector',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchaseio.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='journalentryconnector',
            name='saleitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salesio.saleitem'),
        ),
    ]
