# Generated by Django 5.1.15 on 2026-08-25 06:05

import django.db.models.deletion
"""Give a ledger leg somewhere to record that it was reconciled.

Phase 3.1 of `BANK_REGISTER_FIX_PLAN.md`. Until now the only cleared marker in
the system was `TransactionInformation.is_matched` -- a flag on an imported
statement row, not on the book. Reconciling therefore said nothing about the
ledger, which is BR-1.

On the connector, not the entry: an entry has legs on several accounts and only
the bank leg clears. `JournalEntry.bank_reconciliation` already exists and means
"this entry IS that session's forced discrepancy adjustment", a different fact.

Both fields are nullable and default NULL, so this is additive: every existing
leg reads as unreconciled, which is what it is.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0037_journalentry_bank_reconciliation_and_more'),
        ('transactionio', '0014_bankreconciliation_forced_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='cleared_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentryconnector',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_lines', to='transactionio.bankreconciliation'),
        ),
    ]
