# Generated by Django 5.1.15 on 2026-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0025_enable_rls_supplier'),
        ('creditnoteio', '0013_alter_creditnoteitem_tax'),
        ('journalio', '0038_journalentryconnector_cleared_on_and_more'),
        ('payrollio', '0038_payrolltaxconfig'),
        ('productio', '0012_alter_productadditionalcost_tax'),
        ('purchaseio', '0025_alter_purchaseitem_tax'),
        ('salesio', '0040_alter_saleitem_tax'),
        ('stockio', '0004_stockmovementlayerconsumption_source_movement'),
        ('transactionio', '0016_alter_bankreconciliation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_reconciliation__isnull', False)), fields=('bank_reconciliation',), name='one_discrepancy_entry_per_reconciliation'),
        ),
    ]
