# Generated by Django 5.1.15 on 2026-08-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0039_alter_journalentry_options_and_more'),
        ('purchaseio', '0026_paybillapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryconnector',
            name='pay_bill_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchaseio.paybillitem'),
        ),
    ]
