# Generated by Django 5.1.15 on 2026-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0040_journalentryconnector_pay_bill_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='kind',
            field=models.CharField(choices=[('CREDIT_NOTE', 'Credit Note'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('CHEQUE', 'Cheque'), ('SALE', 'Sale'), ('SALE_RECEPT', 'Sale Recept'), ('REFUND_RECEIPT', 'Refund Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT_PRURCHASE', 'Product Purchase'), ('CHART_OF_ACCOUNT', 'Chart Of Account'), ('JOURNAL_ENTRY', 'Journal Entry'), ('BANK_DEPOSIT', 'Bank Deposit'), ('BANK_RECONCILIATION', 'Bank Reconciliation'), ('PAYROLL_SALARY_PROCESS', 'Payroll Salary Process'), ('PAYROLL_TAX_PAYMENT', 'Payroll Tax Payment'), ('SALES_TAX', 'Sales Tax')], default='PURCHASE', max_length=50),
        ),
    ]
