# Generated by Django 5.1.15 on 2026-08-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_backfill_is_money_account'),
        ('agencyio', '0010_agency_state'),
        ('creditnoteio', '0013_alter_creditnoteitem_tax'),
        ('customerio', '0009_alter_customer_status'),
        ('employeeio', '0067_backfill_employee_company'),
        ('journalio', '0042_relabel_manual_journal_entries'),
        ('purchaseio', '0026_paybillapplication'),
        ('salesio', '0040_alter_saleitem_tax'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
        ('transactionio', '0020_bankreconciliation_report_snapshot'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentryconnector',
            index=models.Index(fields=['account', 'date', 'id'], name='jec_account_date_id_idx'),
        ),
    ]
