# Generated by Django 5.1.1 on 2025-08-29 06:39

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import moovmoneyio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0050_employee_is_same_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoovAccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=moovmoneyio.django_rest.helpers.slug_helpers.get_moov_account_setting_slug, unique=True)),
                ('moov_account_uid', models.CharField(max_length=64, unique=True)),
                ('moov_account_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
