# Generated by Django 5.1.1 on 2025-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovaccountsettings',
            name='moov_representative_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
