# Generated by Django 5.1.1 on 2025-09-01 10:53

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import moovmoneyio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
        ('moovmoneyio', '0002_moovaccountsettings_moov_representative_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoovBankAccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=moovmoneyio.django_rest.helpers.slug_helpers.get_moov_bank_account_setting_slug, unique=True)),
                ('bank_account_uid', models.CharField(max_length=64, unique=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('NEW', 'New')], default='ACTIVE', max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('moov_account_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moov_bank_accounts', to='moovmoneyio.moovaccountsettings')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
