# Generated by Django 5.1.1 on 2025-09-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0003_moovbankaccountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moovbankaccountsettings',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('NEW', 'New')], default='NEW', max_length=250),
        ),
    ]
