# Generated by Django 5.1.1 on 2025-09-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0004_alter_moovbankaccountsettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovbankaccountsettings',
            name='bank_account_kind',
            field=models.CharField(default='DESTINATION', max_length=50, verbose_name=[('SOURCE', 'Source'), ('DESTINATION', 'Destination')]),
        ),
    ]
