# Generated by Django 5.1.1 on 2025-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0005_moovbankaccountsettings_bank_account_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moovbankaccountsettings',
            name='bank_account_kind',
            field=models.CharField(choices=[('SOURCE', 'Source'), ('DESTINATION', 'Destination')], default='DESTINATION', max_length=250),
        ),
    ]
