# Generated by Django 5.1.1 on 2025-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0006_alter_moovbankaccountsettings_bank_account_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moovbankaccountsettings',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed'), ('NEW', 'New')], default='DRAFT', max_length=250),
        ),
    ]
