# Generated by Django 5.1.1 on 2025-09-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0050_employee_is_same_address_and_more'),
        ('moovmoneyio', '0007_alter_moovbankaccountsettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovbankaccountsettings',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moov_employee_bank_accounts', to='employeeio.employee'),
        ),
    ]
