# Generated by Django 5.1.1 on 2025-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0009_moovtransfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moovtransfers',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('RESERVED', 'Reserved'), ('REMOVED', 'Removed')], default='PENDING', max_length=250),
        ),
    ]
