# Generated by Django 5.1.1 on 2026-07-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovmoneyio', '0011_alter_moovbankaccountsettings_status'),
        ('payrollio', '0038_payrolltaxconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='moovtransfers',
            name='payroll_salary_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moov_transfers', to='payrollio.payrollsalaryprocess'),
        ),
    ]
