# Generated by Django 5.1.1 on 2025-07-17 09:31

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import leaveio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0014_remove_company_company_address_and_more'),
        ('employeeio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=leaveio.django_rest.helpers.slug_helpers.get_leave_type_slug, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('maximum_allocation', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_after_working_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_consecutive_allowed', models.PositiveIntegerField(blank=True, null=True)),
                ('leave_type', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('HOURLY', 'Hourly')], default='PAID', max_length=20)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forwarded', models.PositiveIntegerField(blank=True, null=True)),
                ('carry_expiry_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_encashable', models.BooleanField(default=False)),
                ('max_encashable', models.PositiveIntegerField(blank=True, null=True)),
                ('min_encashable', models.PositiveIntegerField(blank=True, null=True)),
                ('earning_components', models.TextField(blank=True)),
                ('is_earned_leave', models.BooleanField(default=False)),
                ('earned_leave_frequency', models.CharField(blank=True, max_length=100)),
                ('allocate_on_day', models.CharField(blank=True, max_length=20)),
                ('rounders', models.CharField(blank=True, max_length=10)),
                ('is_partially_paid', models.BooleanField(default=False)),
                ('fraction_salary_per_leave', models.FloatField(blank=True, null=True)),
                ('is_leave_without_pay', models.BooleanField(default=False)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('include_holidays_within_leave', models.BooleanField(default=False)),
                ('is_optional_leave', models.BooleanField(default=False)),
                ('allow_over_allocation', models.BooleanField(default=False)),
                ('is_compensatory', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
