# Generated by Django 5.1.1 on 2025-07-22 05:41

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0001_initial'),
        ('leaveio', '0004_leaverequest_approved_by_alter_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='adjusted',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='allocated',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='encashed',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='used',
        ),
        migrations.CreateModel(
            name='EmployeeLeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_year', models.PositiveIntegerField(default=2025)),
                ('allocated_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('allocated', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('used', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('encashed', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('adjusted', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_allocation_created_by', to='employeeio.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
                ('leave_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leaveio.leavebalance')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveio.leavetype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
