# Generated by Django 5.1.1 on 2025-07-22 09:56

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0020_rename_reports_to_employee_report_to'),
        ('leaveio', '0005_remove_leavebalance_adjusted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEncashment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encashment_date', models.DateField(default=django.utils.timezone.now)),
                ('total_encashment_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_encashment_created_by', to='employeeio.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
                ('leave_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveio.leavebalance')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveEncashmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('actual_encashable_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('encashment_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount_per_day', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('encashment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='leaveio.leaveencashment')),
                ('leave_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaveio.employeeleaveallocation')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveio.leavetype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
