# Generated by Django 5.1.1 on 2025-07-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveio', '0006_leaveencashment_leaveencashmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveallocation',
            name='used_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
