# Generated by Django 5.1.1 on 2025-07-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveio', '0007_employeeleaveallocation_used_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveencashment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
    ]
