# Generated by Django 5.1.1 on 2025-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveio', '0008_alter_leaveencashment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='maximum_allocation_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('HOURLY', 'Hourly')], default='DAILY', max_length=20),
        ),
    ]
