# Generated by Django 5.1.1 on 2025-08-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('leaveio', '0009_leavetype_maximum_allocation_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='employee_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companyshift'),
        ),
    ]
