# Generated by Django 5.1.1 on 2026-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveio', '0010_leaverequest_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaveallocation',
            name='leave_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
