# Generated by Django 5.1.1 on 2026-05-08 13:20

from django.db import migrations

def create_leave_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    # Leave Requests
    ct_req, _ = ContentType.objects.get_or_create(app_label="leaveio", model="leaverequests")
    for codename, name in [
        ("view_leaverequests", "Can view leave requests"),
        ("add_leaverequests", "Can add leave requests"),
        ("change_leaverequests", "Can change leave requests"),
        ("delete_leaverequests", "Can delete leave requests"),
    ]:
        Permission.objects.get_or_create(codename=codename, content_type=ct_req, defaults={"name": name})

    # Leave Approval
    ct_app, _ = ContentType.objects.get_or_create(app_label="leaveio", model="leaveapproval")
    for codename, name in [
        ("view_leaveapproval", "Can view leave approval"),
        ("add_leaveapproval", "Can add leave approval"),
        ("change_leaveapproval", "Can change leave approval"),
        ("delete_leaveapproval", "Can delete leave approval"),
    ]:
        Permission.objects.get_or_create(codename=codename, content_type=ct_app, defaults={"name": name})

def remove_leave_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    Permission.objects.filter(codename__in=[
        "view_leaverequests", "add_leaverequests", "change_leaverequests", "delete_leaverequests",
        "view_leaveapproval", "add_leaveapproval", "change_leaveapproval", "delete_leaveapproval"
    ]).delete()
    ContentType.objects.filter(app_label="leaveio", model__in=["leaverequests", "leaveapproval"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('leaveio', '0011_alter_employeeleaveallocation_leave_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Leave Approval',
                'verbose_name_plural': 'Leave Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leaveio.leaverequest',),
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leaveio.leaverequest',),
        ),
        migrations.RunPython(create_leave_permissions, reverse_code=remove_leave_permissions),
    ]
