from companyio.choices import CompanyKindChoices

from accounts.choices import ChartOfAccountKindChoices

constructions = [
    {
        "kind": CompanyKindChoices.CONSTRUCTION,
        "chart_of_accounts": [
            {
                "title": "Cash on Hand",
                "code": "1000",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Cash on hand",
            },
            {
                "title": "Checking Account",
                "code": "1010",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Checking",
            },
            {
                "title": "Savings Account",
                "code": "1020",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Savings",
            },
            {
                "title": "Accounts Receivable (A/R)",
                "code": "1100",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Accounts Receivable (A/R)",
                "detail_type_title": "Accounts Receivable",
            },
            {
                "title": "Retention Receivable",
                "code": "1110",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Accounts Receivable (A/R)",
                "detail_type_title": "Accounts Receivable",
            },
            {
                "title": "Construction in Progress (CIP)",
                "code": "1200",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Other fixed assets",
            },
            {
                "title": "Equipment & Machinery",
                "code": "1300",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Machinery & Equipment",
            },
            {
                "title": "Accumulated Depreciation",
                "code": "1310",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Accumulated Depreciation",
            },
            
            # {
            #     "title": "Historical Adjustment",
            #     "code": "1411",
            #     "kind": ChartOfAccountKindChoices.ASSETS,
            #     "account_type_title": "Other Current Assets",
            #     "detail_type_title": "Other Current Asset",
            # },
            {
                "title": "Prepaid Insurance",
                "code": "1400",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Prepaid Expenses",
            },
            {
                "title": "Undeposited Funds",
                "code": "1410",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Undeposited Funds",
            },
            {
                "title": "Inventory Asset",
                "code": "1500",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Accounts Payable (A/P)",
                "code": "2000",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Accounts Payable (A/P)",
                "detail_type_title": "Accounts Payable",
            },
            {
                "title": "Retention Payable",
                "code": "2010",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Accounts Payable (A/P)",
                "detail_type_title": "Accounts Payable",
            },
            {
                "title": "Line of Credit",
                "code": "2100",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Line of Credit",
            },
            {
                "title": "Other Current Liabilities",
                "code": "2200",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Other Current Liability",
            },
            {
                "title": "Loan Payable",
                "code": "2300",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Loan Payable",
            },
            {
                "title": "Accrued Payroll",
                "code": "2400",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Tax Payable",
            },
            {
                "title": "Sales Tax Payable",
                "code": "2500",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Sales Tax Payable",
            },
            {
                "parent": None,
                "title": "Federal Taxes (941/943/944)",
                "code": "2501",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "Federal Unemployment (940)",
                "code": "2502",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Income Tax",
                "code": "2503",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Employment Taxes",
                "code": "2504",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Income Tax",
                "code": "2505",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Unemployment Taxes",
                "code": "2506",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Income Tax",
                "code": "2507",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Unemployment Tax",
                "code": "2508",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "title": "Long-Term Loan Payable",
                "code": "2600",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Long Term Liabilities",
                "detail_type_title": "Notes Payable",
            },
            {
                "title": "State/Local Income Tax Payable",
                "code": "2700",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Owner’s Equity",
                "code": "3000",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Owner's Equity",
            },
            {
                "title": "Retained Earnings",
                "code": "3100",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Retained Earnings",
            },
            {
                "title": "Opening Balance Equity",
                "code": "3300",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Opening Balance Equity",
            },
            {
                # Contra-revenue. Carries a DEBIT balance inside the income
                # section, which is correct -- do not treat it as a sign error.
                "title": "Sales Discounts",
                "code": "4060",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Discounts/Refunds Given",
            },
            {
                # Shipping charged TO the customer, i.e. revenue. Distinct from
                # the freight/shipping EXPENSE accounts, which are what the
                # company pays out.
                "title": "Shipping Income",
                "code": "4070",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Other Primary Income",
            },
            {
                "title": "Construction Revenue",
                "code": "4000",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Retainage Earned",
                "code": "4010",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Change Order Revenue",
                "code": "4020",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Consulting Revenue",
                "code": "4030",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Sales of Product Income",
                "code": "4080",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Service/Fee Income",
                "code": "4090",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Service",
                "code": "4100",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Interest Income",
                "code": "7000",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Interest Earned",
            },
            {
                "title": "Cost of Goods Sold (COGS)",
                "code": "5001",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Direct Labor Costs",
                "code": "5000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Costs of Labor-COST",
            },
            {
                "title": "Materials & Supplies",
                "code": "5100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies-COGS",
            },
            {
                "title": "Equipment Rental",
                "code": "5200",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Equipment Rental-COGS",
            },
            {
                "title": "Subcontractor Costs",
                "code": "5300",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Costs of Labor-COST",
            },
            {
                "title": "Permit & Licensing Fees",
                "code": "5400",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Service-COGS",
            },
            {
                "title": "Inventory Shrinkage",
                "code": "5500",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Other Costs of Services - COST",
            },
            {
                "title": "Office Rent",
                "code": "6000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Rent or Lease of Buildings",
            },
            {
                "title": "Utilities",
                "code": "6010",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Office Supplies",
                "code": "6020",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Supplies & Materials",
            },
            {
                "title": "Insurance Expense",
                "code": "6030",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Insurance",
            },
            {
                "title": "Advertising & Marketing",
                "code": "6040",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Advertising/Promotional",
            },
            {
                "title": "Accounting & Legal Fees",
                "code": "6050",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Legal & Professional Fees",
            },
            {
                "title": "Travel & Meals",
                "code": "6060",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Travel Meals",
            },
            {
                "title": "Training & Development",
                "code": "6070",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Office/General Administrative Expenses",
            },
            {
                "title": "Payroll Expense",
                "code": "6080",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "title": "Depreciation Expense",
                "code": "6090",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Depreciation",
            },
            {
                "title": "Bad Debt Expense",
                "code": "6100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Bad Debts",
            },
            {
                "parent": None,
                "title": "Company Contributions",
                "code": "6101",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Wages",
                "code": "6102",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": "Company Contributions",
                "title": "Health Insurance",
                "code": "6103",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Taxes",
                "code": "6104",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "title": "Interest Expense",
                "code": "7100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Interest Paid",
            },
            {
                "title": "Gain/Loss on Asset Sale",
                "code": "7200",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
            {
                "title": "Other Miscellaneous Expense",
                "code": "7300",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
        ],
    }
]

