from companyio.choices import CompanyKindChoices

from accounts.choices import ChartOfAccountKindChoices

ecommerce = [
    {
        "kind": CompanyKindChoices.ECOMMERCE,
        "chart_of_accounts": [
            {
                "title": "Cash on Hand",
                "code": "1000",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Cash & Cash Equivalents",
            },
            {
                "title": "Checking Account",
                "code": "1010",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Checking",
            },
            {
                "title": "Savings Account",
                "code": "1020",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Savings",
            },
            {
                "title": "PayPal Account",
                "code": "1030",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Other Current Asset",
            },
            {
                "title": "Stripe Holding Account",
                "code": "1040",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Other Current Asset",
            },
            {
                "title": "Amazon Holding Account",
                "code": "1050",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Other Current Asset",
            },
            {
                "title": "Shopify Payments Account",
                "code": "1060",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Other Current Asset",
            },
            {
                "title": "Accounts Receivable (A/R)",
                "code": "1100",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Accounts Receivable (A/R)",
                "detail_type_title": "Accounts Receivable",
            },
            {
                "title": "Inventory Asset",
                "code": "1200",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Undeposited Funds",
                "code": "1410",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Undeposited Funds",
            },
            {
                "title": "Prepaid Expenses",
                "code": "1300",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Prepaid Expenses",
            },
            # {
            #     "title": "Historical Adjustment",
            #     "code": "1411",
            #     "kind": ChartOfAccountKindChoices.ASSETS,
            #     "account_type_title": "Other Current Assets",
            #     "detail_type_title": "Other Current Asset",
            # },
            {
                "title": "Security Deposits",
                "code": "1400",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Other Current Asset",
            },
            {
                "title": "Equipment & Furniture",
                "code": "1500",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Furniture & Fixtures",
            },
            {
                "title": "Fixed Asset Software",
                "code": "1510",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Fixed Asset Software",
            },
            {
                "title": "Fixed Asset Computer",
                "code": "1511",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Fixed Asset Computer",
            },
            {
                "title": "Warehouse Property",
                "code": "1520",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Buildings",
            },
            {
                "title": "Accumulated Depreciation",
                "code": "1600",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Accumulated Depreciation",
            },
            {
                "title": "Accounts Payable (A/P)",
                "code": "2000",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Accounts Payable (A/P)",
                "detail_type_title": "Accounts Payable",
            },
            {
                "title": "Credit Card Payable",
                "code": "2100",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Credit Cards",
                "detail_type_title": "Credit Card",
            },
            {
                "title": "Sales Tax Payable",
                "code": "2200",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Sales Tax Payable",
            },
            {
                "title": "Loan Payable - Short Term",
                "code": "2300",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Loan Payable",
            },
            {
                "title": "Loan Payable - Long Term",
                "code": "2400",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Long Term Liabilities",
                "detail_type_title": "Notes Payable",
            },
            {
                "title": "Payroll Liabilities",
                "code": "2500",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "Federal Taxes (941/943/944)",
                "code": "2501",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "Federal Unemployment (940)",
                "code": "2502",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Income Tax",
                "code": "2503",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Employment Taxes",
                "code": "2504",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Income Tax",
                "code": "2505",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Unemployment Taxes",
                "code": "2506",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Income Tax",
                "code": "2507",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Unemployment Tax",
                "code": "2508",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "title": "Gift Card Liabilities",
                "code": "2600",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Deferred Revenue",
            },
            {
                "title": "State/Local Income Tax Payable",
                "code": "2700",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Deferred Revenue",
                "code": "2800",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Deferred Revenue",
            },
            {
                "title": "Owner’s Equity",
                "code": "3000",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Owner's Equity",
            },
            {
                "title": "Retained Earnings",
                "code": "3100",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Retained Earnings",
            },
            {
                "title": "Opening Balance Equity",
                "code": "3300",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Opening Balance Equity",
            },
            {
                "title": "Product Sales Revenue",
                "code": "4000",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Affiliate Commission Revenue",
                "code": "4020",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Commission Income",
            },
            {
                "title": "Marketplace Fees Reimbursement",
                "code": "4030",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Gift Card Sales",
                "code": "4040",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Other Miscellaneous Income",
            },
            {
                "title": "Interest Income",
                "code": "4050",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Interest Earned",
            },
            {
                # Shipping charged TO the customer, i.e. revenue. Distinct from
                # the freight/shipping EXPENSE accounts, which are what the
                # company pays out.
                "title": "Shipping Income",
                "code": "4070",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Other Primary Income",
            },
            {
                "title": "Sales Discounts",
                "code": "4060",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Discounts/Refunds Given",
            },
            {
                "title": "Sales of Product Income",
                "code": "4080",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Service/Fee Income",
                "code": "4090",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Service",
                "code": "4100",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Cost of Goods Sold (COGS)",
                "code": "5001",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Cost of Goods Sold - Products",
                "code": "5000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Freight In (Inbound Shipping)",
                "code": "5010",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Shipping, Freight & Delivery - COST",
            },
            {
                "title": "Packaging Supplies",
                "code": "5020",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Materials & Supplies",
                "code": "5100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Merchant Processing Fees",
                "code": "5030",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Merchant Fees",
            },
            {
                "title": "Returns & Refunds",
                "code": "5040",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Refunds & Chargebacks",
            },
            {
                "title": "Inventory Shrinkage",
                "code": "5500",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Other Costs of Services - COST",
            },
            {
                "title": "Advertising & Marketing",
                "code": "6000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Advertising/Promotional",
            },
            {
                "title": "Professional Services - Accounting",
                "code": "6030",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Legal & Professional Fees",
            },
            {
                "title": "Professional Services - Legal",
                "code": "6040",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Legal & Professional Fees",
            },
            {
                "title": "Rent & Warehouse Costs",
                "code": "6050",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Rent or Lease of Buildings",
            },
            {
                "title": "Utilities (Warehouse)",
                "code": "6060",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Telephone & Internet",
                "code": "6070",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Travel & Meals",
                "code": "6080",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Travel",
            },
            {
                "title": "Payroll Expenses",
                "code": "6090",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "title": "Bank Service Charges",
                "code": "6100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Bank Charges",
            },
            {
                "parent": None,
                "title": "Company Contributions",
                "code": "6101",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Wages",
                "code": "6102",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": "Company Contributions",
                "title": "Health Insurance",
                "code": "6103",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Taxes",
                "code": "6104",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "title": "Shipping & Delivery Costs",
                "code": "6110",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Shipping, Freight & Delivery",
            },
            {
                "title": "Insurance - Business",
                "code": "6120",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Insurance",
            },
            {
                "title": "Property Taxes",
                "code": "6130",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Taxes & Licenses",
            },
            {
                "title": "Depreciation Expense",
                "code": "6140",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Depreciation",
            },
            {
                "title": "Bad Debt Expense",
                "code": "6150",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Bad Debts",
            },
            {
                "title": "Interest Expense - Loans",
                "code": "7000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Interest Paid",
            },
            {
                "title": "Gain/Loss on Asset Sale",
                "code": "7100",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Other Miscellaneous Income",
            },
            {
                "title": "Other Miscellaneous Expense",
                "code": "7300",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
        ],
    }
]

