from companyio.choices import CompanyKindChoices

from accounts.choices import ChartOfAccountKindChoices

restaurant_hotel = [
    {
        "kind": CompanyKindChoices.RESTAURANT_HOTEL,
        "chart_of_accounts": [
            {
                "title": "Cash on Hand",
                "code": "1000",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Cash & Cash Equivalents",
            },
            {
                "title": "Checking Account",
                "code": "1010",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Checking",
            },
            {
                "title": "Savings Account",
                "code": "1020",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Bank",
                "detail_type_title": "Savings",
            },
            {
                "title": "Accounts Receivable (A/R)",
                "code": "1100",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Accounts Receivable (A/R)",
                "detail_type_title": "Accounts Receivable",
            },
            {
                "title": "Inventory Asset",
                "code": "1200",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Inventory - Work in Progress (WIP)",
                "code": "1210",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Inventory - Finished Goods",
                "code": "1220",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Undeposited Funds",
                "code": "1410",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Undeposited Funds",
            },
            {
                "title": "Prepaid Expenses",
                "code": "1300",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Prepaid Expenses",
            },
            {
                "title": "Security Deposits",
                "code": "1400",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Assets",
                "detail_type_title": "Security Deposits",
            },
            {
                "title": "Fixed Asset Furniture",
                "code": "1501",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Fixed Asset Furniture",
            },
            {
                "title": "Machinery & Equipment",
                "code": "1502",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Machinery & Equipment",
            },
            {
                "title": "Fixed Asset Software",
                "code": "1510",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Fixed Asset Software",
            },
            {
                "title": "Fixed Asset Computer",
                "code": "1511",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Fixed Asset Computer",
            },
            {
                "title": "Vehicles for Business",
                "code": "1520",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Vehicles",
            },
            {
                "title": "Accumulated Depreciation",
                "code": "1600",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Accumulated Depreciation",
            },
            {
                "title": "Accounts Payable (A/P)",
                "code": "2000",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Accounts Payable (A/P)",
                "detail_type_title": "Accounts Payable",
            },
            {
                "title": "Credit Card Payable",
                "code": "2100",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Credit Cards",
                "detail_type_title": "Credit Card",
            },
            {
                "title": "Sales Tax Payable",
                "code": "2200",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Sales Tax Payable",
            },
            {
                "title": "Payroll Liabilities",
                "code": "2300",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "title": "Loan Payable - Short Term",
                "code": "2400",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Loan Payable",
            },
            {
                "title": "Loan Payable - Long Term",
                "code": "2500",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Long Term Liabilities",
                "detail_type_title": "Notes Payable",
            },
            {
                "parent": None,
                "title": "Federal Taxes (941/943/944)",
                "code": "2501",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "Federal Unemployment (940)",
                "code": "2502",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Income Tax",
                "code": "2503",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "NYS Employment Taxes",
                "code": "2504",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Income Tax",
                "code": "2505",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "MN Unemployment Taxes",
                "code": "2506",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Income Tax",
                "code": "2507",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "parent": None,
                "title": "AL Unemployment Tax",
                "code": "2508",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Payroll Liabilities",
            },
            {
                "title": "Deferred Revenue",
                "code": "2600",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Deferred Revenue",
            },
            {
                "title": "State/Local Income Tax Payable",
                "code": "2700",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Owner’s Equity",
                "code": "3000",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Owner's Equity",
            },
            {
                "title": "Retained Earnings",
                "code": "3100",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Retained Earnings",
            },
            {
                "title": "Opening Balance Equity",
                "code": "3300",
                "kind": ChartOfAccountKindChoices.EQUITIES,
                "account_type_title": "Equity",
                "detail_type_title": "Opening Balance Equity",
            },
            {
                "title": "Product Sales Revenue",
                "code": "4000",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Wholesale Revenue",
                "code": "4010",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Online Sales Revenue",
                "code": "4020",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Affiliate Commission Revenue",
                "code": "4040",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Commission Income",
            },
            {
                "title": "Gift Card Sales",
                "code": "4050",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Other Miscellaneous Income",
            },
            {
                # Shipping charged TO the customer, i.e. revenue. Distinct from
                # the freight/shipping EXPENSE accounts, which are what the
                # company pays out.
                "title": "Shipping Income",
                "code": "4070",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Other Primary Income",
            },
            {
                "title": "Sales Discounts",
                "code": "4060",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Discounts/Refunds Given",
            },
            {
                "title": "Sales of Product Income",
                "code": "4080",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Service/Fee Income",
                "code": "4090",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Service",
                "code": "4100",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Cost of Goods Sold (COGS)",
                "code": "5001",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Cost of Materials (Fabric, Threads)",
                "code": "5000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Materials & Supplies",
                "code": "5100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Manufacturing Costs",
                "code": "5010",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Freight In (Inbound Shipping)",
                "code": "5020",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Shipping, Freight & Delivery - COST",
            },
            {
                "title": "Packaging Supplies",
                "code": "5030",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Merchant Processing Fees",
                "code": "5040",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Merchant Fees",
            },
            {
                "title": "Returns & Refunds",
                "code": "5050",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Refunds & Chargebacks",
            },
            {
                "title": "Inventory Shrinkage",
                "code": "5500",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Other Costs of Services - COST",
            },
            {
                "title": "Advertising & Marketing",
                "code": "6000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Advertising/Promotional",
            },
            {
                "title": "Photography & Fashion Shoots",
                "code": "6010",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Advertising/Promotional",
            },
            {
                "title": "Professional Services - Accounting",
                "code": "6040",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Legal & Professional Fees",
            },
            {
                "title": "Professional Services - Legal",
                "code": "6050",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Legal & Professional Fees",
            },
            {
                "title": "Showroom & Rent Expenses",
                "code": "6060",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Rent or Lease of Buildings",
            },
            {
                "title": "Utilities (Office & Warehouse)",
                "code": "6070",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Telephone & Internet",
                "code": "6080",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Travel & Fashion Events",
                "code": "6090",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Travel",
            },
            {
                "title": "Payroll Expenses",
                "code": "6100",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Company Contributions",
                "code": "6101",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Wages",
                "code": "6102",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": "Company Contributions",
                "title": "Health Insurance",
                "code": "6103",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "parent": None,
                "title": "Taxes",
                "code": "6104",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Payroll Expenses",
            },
            {
                "title": "Bank Service Charges",
                "code": "6120",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Bank Charges",
            },
            {
                "title": "Shipping & Delivery Costs",
                "code": "6130",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Shipping, Freight & Delivery",
            },
            {
                "title": "Insurance - Business",
                "code": "6140",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Insurance",
            },
            {
                "title": "Property Taxes",
                "code": "6150",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Taxes & Licenses",
            },
            {
                "title": "Depreciation Expense",
                "code": "6160",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Depreciation",
            },
            {
                "title": "Bad Debt Expense",
                "code": "6170",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Bad Debts",
            },
            {
                "title": "Interest Expense - Loans",
                "code": "7000",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Interest Paid",
            },
            {
                "title": "Other Miscellaneous Expense",
                "code": "7300",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
            {
                "title": "Inventory (Food)",
                "code": "1401",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Inventory (Beverage)",
                "code": "1402",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Inventory (Hotel Supplies)",
                "code": "1403",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Current Assets",
                "detail_type_title": "Inventory",
            },
            {
                "title": "Equipment (Kitchen)",
                "code": "1508",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Machinery & Equipment",
            },
            {
                "title": "Furniture and Fixtures",
                "code": "1509",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Furniture & Fixtures",
            },
            {
                "title": "Property and Land",
                "code": "1503",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Buildings",
            },
            {
                "title": "Building",
                "code": "1504",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Buildings",
            },
            {
                "title": "Leasehold Improvements",
                "code": "1505",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Leasehold Improvements",
            },
            {
                "title": "Vehicles",
                "code": "1506",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Fixed Assets",
                "detail_type_title": "Vehicles",
            },
            {
                "title": "Investments",
                "code": "1507",
                "kind": ChartOfAccountKindChoices.ASSETS,
                "account_type_title": "Other Assets",
                "detail_type_title": "Other Long-term Assets",
            },
            {
                "title": "Accounts Payable (Food and Beverage)",
                "code": "2710",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Accounts Payable (A/P)",
                "detail_type_title": "Accounts Payable",
            },
            {
                "title": "Accrued Expenses",
                "code": "2711",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Other Current Liability",
            },
            {
                "title": "Short-term Loans Payable",
                "code": "2712",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Loan Payable",
            },
            {
                "title": "Long-term Loans Payable",
                "code": "2713",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Long Term Liabilities",
                "detail_type_title": "Other Long Term Liabilities",
            },
            {
                "title": "Mortgages Payable",
                "code": "2714",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Long Term Liabilities",
                "detail_type_title": "Other Long Term Liabilities",
            },
            {
                "title": "Taxes Payable",
                "code": "2715",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Unearned Revenue",
                "code": "2716",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Deferred Revenue",
            },
            {
                "title": "Food Sales (Restaurant)",
                "code": "4016",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Beverage Sales (Restaurant)",
                "code": "4017",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Sales of Product Income",
            },
            {
                "title": "Room Revenue (Hotel)",
                "code": "4018",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Event Revenue (Banquet/Conference)",
                "code": "4019",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Catering Revenue",
                "code": "4022",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Other Revenue",
                "code": "4021",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Income",
                "detail_type_title": "Service/Fee Income",
            },
            {
                "title": "Cost of Food Sold",
                "code": "5016",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Cost of Beverage Sold",
                "code": "5017",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Cost of Supplies Sold (Hotel)",
                "code": "5018",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Cost of Catering Sold",
                "code": "5019",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Labor Costs",
                "code": "5021",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Cost of Goods Sold (COGS)",
                "detail_type_title": "Supplies & Materials - COGS",
            },
            {
                "title": "Rent Expense",
                "code": "6186",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Rent or Lease of Buildings",
            },
            {
                "title": "Utilities",
                "code": "6187",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Utilities",
            },
            {
                "title": "Insurance",
                "code": "6188",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Insurance",
            },
            {
                "title": "Property Maintenance",
                "code": "6189",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Repair & Maintenance",
            },
            {
                "title": "Marketing and Advertising",
                "code": "6190",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Advertising/Promotional",
            },
            {
                "title": "Repairs and Maintenance",
                "code": "6191",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Repair & Maintenance",
            },
            {
                "title": "Housekeeping Supplies",
                "code": "6192",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Supplies & Materials",
            },
            {
                "title": "Guest Amenities",
                "code": "6193",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Other Business Expenses",
            },
            {
                "title": "Food and Beverage Supplies",
                "code": "6194",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Supplies & Materials",
            },
            {
                "title": "Laundry Expenses",
                "code": "6195",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Other Business Expenses",
            },
            {
                "title": "Equipment Maintenance",
                "code": "6196",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Repair & Maintenance",
            },
            {
                "title": "Administrative Expenses",
                "code": "6197",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Office/General Administrative Expenses",
            },
            {
                "title": "Training and Development",
                "code": "6198",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Other Business Expenses",
            },
            {
                "title": "Travel and Entertainment",
                "code": "6199",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Travel",
            },
            {
                "title": "Property Management Fees",
                "code": "6200",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Expense",
                "detail_type_title": "Other Business Expenses",
            },
            {
                "title": "Interest Income",
                "code": "7047",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Interest Earned",
            },
            {
                "title": "Interest Expense",
                "code": "7301",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Interest Paid",
            },
            {
                "title": "Gain/Loss on Sale of Assets",
                "code": "7302",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
            {
                "title": "Other Non-Operating Income/Expenses",
                "code": "7303",
                "kind": ChartOfAccountKindChoices.EXPENSES,
                "account_type_title": "Other Expenses",
                "detail_type_title": "Other Miscellaneous Expense",
            },
            {
                "title": "Income Taxes",
                "code": "2717",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Property Taxes Payable",
                "code": "2718",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Occupancy Taxes",
                "code": "2719",
                "kind": ChartOfAccountKindChoices.LIABILITIES,
                "account_type_title": "Other Current Liabilities",
                "detail_type_title": "Taxes Payable",
            },
            {
                "title": "Donations and Contributions",
                "code": "7048",
                "kind": ChartOfAccountKindChoices.INCOMES,
                "account_type_title": "Other Income",
                "detail_type_title": "Other Miscellaneous Income",
            },
        ],
    },
]


