# Generated by Django 5.1.1 on 2024-12-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyio', '0003_currencyconnector_sale_and_more'),
        ('salesio', '0002_rename_bill_date_sale_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconnector',
            name='sale_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salereceipt'),
        ),
        migrations.AlterField(
            model_name='currencyconnector',
            name='model_kind',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RECEIPT', 'Sale Receipt')], max_length=50, null=True),
        ),
    ]
