# Generated by Django 5.1.1 on 2024-12-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0001_initial'),
        ('currencyio', '0004_currencyconnector_sale_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconnector',
            name='credit_noteio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='currencyconnector',
            name='model_kind',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RECEIPT', 'Sale Receipt'), ('CREDIT_NOTE_ITEM', 'Credit Note Item')], max_length=50, null=True),
        ),
    ]
