# Generated by Django 5.1.1 on 2024-12-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0002_creditnote_supplier'),
        ('currencyio', '0005_currencyconnector_credit_noteio_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconnector',
            name='credit_noteio_item',
        ),
        migrations.AddField(
            model_name='currencyconnector',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote'),
        ),
    ]
