# Generated by Django 5.1.1 on 2025-02-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyio', '0007_currencyconnector_sale_payment_receive_and_more'),
        ('purchaseio', '0012_expense_expense_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconnector',
            name='purchase_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment'),
        ),
        migrations.AlterField(
            model_name='currencyconnector',
            name='model_kind',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RECEIPT', 'Sale Receipt'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PURCHASE_PAYMENT', 'Purchase Payment')], max_length=50, null=True),
        ),
    ]
