# Generated by Django 5.1.1 on 2025-02-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyio', '0008_currencyconnector_purchase_payment_and_more'),
        ('purchaseio', '0018_paybill_paybillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconnector',
            name='pay_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.paybill'),
        ),
        migrations.AlterField(
            model_name='currencyconnector',
            name='model_kind',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_RECEIPT', 'Sale Receipt'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill')], max_length=50, null=True),
        ),
    ]
