# Generated by Django 5.1.1 on 2025-03-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0010_alter_company_kind_alter_company_status_and_more'),
        ('currencyio', '0009_currencyconnector_pay_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.company'),
        ),
    ]
