# Generated by Django 5.1.1 on 2025-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencyio', '0010_alter_currency_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconnector',
            name='sale_receipt',
        ),
        migrations.AlterField(
            model_name='currencyconnector',
            name='model_kind',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill')], max_length=50, null=True),
        ),
    ]
