# Generated by Django 5.1.1 on 2026-07-07 04:26

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

# Only the tenant table gets the isolation policy; NexusStateRule is global
# reference data (no company_id). No-op off PostgreSQL. See common/db/rls.py.
RLS_TABLES = ["nexusio_nexusstatestatus"]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0023_enable_rls_core_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexusStateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('state_name', models.CharField(max_length=100)),
                ('has_sales_tax', models.BooleanField(default=True)),
                ('sales_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('txn_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('combination_logic', models.CharField(choices=[('SALES_ONLY', 'Sales only'), ('OR', 'Sales or transactions'), ('AND', 'Sales and transactions'), ('NONE', 'No sales tax')], max_length=20)),
                ('includable_sales_basis', models.CharField(choices=[('GROSS', 'Gross'), ('RETAIL', 'Retail'), ('TAXABLE', 'Taxable')], default='GROSS', max_length=10)),
                ('measurement_period_type', models.CharField(choices=[('CURRENT_YEAR', 'Current calendar year'), ('PREVIOUS_YEAR', 'Previous calendar year'), ('CURRENT_OR_PREVIOUS_YEAR', 'Current or previous year'), ('TRAILING_12M', 'Trailing 12 months')], max_length=30)),
                ('trailing_nexus_rule', models.TextField(blank=True, null=True)),
                ('registration_timing_note', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('state_code', '-effective_from'),
                'constraints': [models.UniqueConstraint(fields=('state_code', 'effective_from'), name='uniq_nexus_rule_state_effective')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NexusStateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('taxable_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('txn_count', models.PositiveIntegerField(default=0)),
                ('pct_of_sales_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pct_of_txn_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('threshold_met', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_APPROACHING', 'Not approaching'), ('APPROACHING', 'Approaching'), ('MET', 'Threshold met'), ('REGISTERED', 'Registered'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_APPROACHING', max_length=20)),
                ('threshold_met_date', models.DateField(blank=True, null=True)),
                ('episode_key', models.CharField(blank=True, max_length=64, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('state_code',),
                'indexes': [models.Index(fields=['company', 'status'], name='nexusio_nex_company_c36b72_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'state_code'), name='uniq_nexus_status_company_state')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
