# Generated by Django 5.1.1 on 2026-07-07 05:05

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

RLS_TABLES = ["nexusio_nexussettings", "nexusio_nexusagencyregistration"]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0010_agency_state'),
        ('companyio', '0023_enable_rls_core_tables'),
        ('nexusio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NexusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning_fraction', models.DecimalField(decimal_places=3, default=0.8, max_digits=4)),
                ('include_marketplace_in_measurement', models.BooleanField(default=True)),
                ('alert_channels', models.JSONField(default=list)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NexusAgencyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('registration_type', models.CharField(choices=[('ECONOMIC', 'Economic nexus'), ('PHYSICAL_MANUAL', 'Physical presence (manual)')], default='ECONOMIC', max_length=20)),
                ('registration_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('REGISTERED', 'Registered')], default='NOT_STARTED', max_length=20)),
                ('sales_tax_permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=20, null=True)),
                ('collection_start_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('tax_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyio.agency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'state_code'), name='uniq_nexus_registration_company_state')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
