# Generated by Django 5.1.1 on 2026-07-07 05:28

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

RLS_TABLES = ["nexusio_nexusalertlog"]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0023_enable_rls_core_tables'),
        ('nexusio', '0002_nexussettings_nexusagencyregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NexusAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('alert_type', models.CharField(choices=[('APPROACHING', 'Approaching'), ('CROSSED', 'Crossed')], max_length=20)),
                ('episode_key', models.CharField(max_length=64)),
                ('threshold_pct_at_alert', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-triggered_at',),
                'indexes': [models.Index(fields=['company', 'triggered_at'], name='nexusio_nex_company_7d9345_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'state_code', 'alert_type', 'episode_key'), name='uniq_nexus_alert_episode')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
