# Generated by Django 5.1.1 on 2025-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
