# Generated by Django 5.1.1 on 2026-07-06 13:12

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from common.db.rls import disable_rls_for_tables, enable_rls_for_tables

# New tenant tables (each carries company_id) get the tenant-isolation RLS
# policy like the core tables; see common/db/rls.py. No-op off PostgreSQL.
RLS_TABLES = [
    "stockio_stockmovement",
    "stockio_stockmovementlayerconsumption",
]


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(enable_rls_for_tables(RLS_TABLES))


def remove_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(disable_rls_for_tables(RLS_TABLES))


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0023_enable_rls_core_tables'),
        ('creditnoteio', '0012_creditnote_credit_note_sales_tax'),
        ('employeeio', '0067_backfill_employee_company'),
        ('productio', '0010_alter_productadditionalcost_prefferred_supplier_and_more'),
        ('purchaseio', '0024_purchase_source_template'),
        ('salesio', '0038_sale_source_template'),
        ('stockio', '0002_stockadjustment_reason'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening balance'), ('PURCHASE', 'Purchase'), ('PURCHASE_RETURN', 'Purchase return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale return'), ('ADJUSTMENT_IN', 'Adjustment (in)'), ('ADJUSTMENT_OUT', 'Adjustment (out)'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('signed_quantity', models.IntegerField()),
                ('rate', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
                ('inventory_cost', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('credit_note_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creditnoteio.creditnoteitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productio.product')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseio.purchaseitem')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesio.saleitem')),
                ('stock_adjustment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockio.stockadjustmentitem')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('date', 'created_at', 'id'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovementLayerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_consumed', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('unit_cost', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('cost_amount', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('is_fallback', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='stockio.stockmovement')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseio.purchaseitem')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'product', 'date'], name='stockio_sto_company_9ebca3_idx'),
        ),
        migrations.RunPython(apply_rls, remove_rls),
    ]
