# Generated by Django 5.1.15 on 2026-08-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockio', '0003_stockmovement_stockmovementlayerconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementlayerconsumption',
            name='source_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_by', to='stockio.stockmovement'),
        ),
    ]
