# Generated by Django 5.1.1 on 2024-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryio', '0003_category_description_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('BRAND', 'Brand'), ('PURCHASE', 'Purchase')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
