# Generated by Django 5.1.1 on 2024-12-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandio', '0002_initial'),
        ('categoryio', '0004_alter_category_kind'),
        ('productio', '0006_product_expired_date'),
        ('purchaseio', '0006_alter_expense_payment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconnector',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('BRAND', 'Brand'), ('PURCHASE', 'Purchase'), ('PURCHASE_ITEM', 'Purchase Item')], default='PRODUCT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoryconnector',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brandio.brand'),
        ),
        migrations.AlterField(
            model_name='categoryconnector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productio.product'),
        ),
    ]
