# Generated by Django 5.1.1 on 2024-12-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryio', '0005_categoryconnector_purchase_item_alter_category_kind_and_more'),
        ('creditnoteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryconnector',
            name='credit_noteio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('BRAND', 'Brand'), ('PURCHASE', 'Purchase'), ('PURCHASE_ITEM', 'Purchase Item'), ('CREDIT_NOTE_ITEM', 'Credit Note Item')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
