# Generated by Django 5.1.1 on 2024-12-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryio', '0006_categoryconnector_credit_noteio_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryconnector',
            old_name='credit_noteio_item',
            new_name='credit_note_item',
        ),
    ]
