# Generated by Django 5.1.1 on 2025-02-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryio', '0007_rename_credit_noteio_item_categoryconnector_credit_note_item'),
        ('companyio', '0008_company_kind_historicalcompany_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('BRAND', 'Brand'), ('PURCHASE', 'Purchase'), ('PURCHASE_ITEM', 'Purchase Item'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('CHART_OF_ACCOUNT', 'Chart of Account')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
