from rest_framework.serializers import ModelSerializer

from subscriptionio.models import Subscription, SubscriptionPrice


class PublicSubscriptionListSerializer(ModelSerializer):
    class Meta:
        model = Subscription
        fields = [
            "slug",
            "title",
            "status",
            "kind",
            "description",
            "currency",
            "user_limit",
            "storage_limit",
            "trial_period",
            "is_chart_of_account",
            "is_chart_of_account_tree",
            "is_journal_entry",
            "is_bank_transaction",
            "is_sales",
            "is_customer",
            "is_inventory",
            "is_warehouse",
            "is_expense",
            "is_supplier_management",
            "is_standard_report",
            "is_agency_tax",
            "is_employees",
            "is_payroll",
            "is_attendance",
            "is_punch_data_import",
            "is_multicurrency",
            "is_company_setting",
            "is_audit_log",
            "is_attachment",
            "is_user_role_management",
            "is_terms",
            "is_payment_management",
            "is_configuration",
            "is_user_profile",
            "is_support_ticket",
            "is_ai_finzify",
            "is_auto_renew",
            "is_enable_email_notification",
            "cancel_policy",
            "note",
            # Accountant related
            "is_monthly_bookkeeping_and_reconciliations",
            "is_reports",
            "is_annual_tax_filing",
            "is_1099_preparation_filing",
            "is_30_minute_consultation_per_quarter",
            "is_monthly_or_biweekly_payroll_processing",
            "is_quarterly_tax_planning_reviews",
            "is_budgeting_and_cash_flow_forecasting",
            "is_sales_tax_filing",
            "is_unlimited_email_support",
            "is_dedicated_accountant",
            "is_Virtual_CFO_services",
            "is_financial_modeling_and_custom_dashboards",
            "is_investo_ready_financial_statements",
            "is_audit_support_and_representation",
            "is_year_end_planning_for_tax_minimization",
            "is_multi_entity_or_multi_state_handling",
            "is_priority_support",
            "created_at",
            "updated_at",
        ]


class PublicSubscriptionDetailsSerializer(ModelSerializer):
    class Meta:
        model = Subscription
        fields = [
            "slug",
            "title",
            "status",
            "kind",
            "description",
            "currency",
            "user_limit",
            "storage_limit",
            "trial_period",
            "is_chart_of_account",
            "is_chart_of_account_tree",
            "is_journal_entry",
            "is_bank_transaction",
            "is_sales",
            "is_customer",
            "is_inventory",
            "is_warehouse",
            "is_expense",
            "is_supplier_management",
            "is_standard_report",
            "is_agency_tax",
            "is_employees",
            "is_payroll",
            "is_attendance",
            "is_punch_data_import",
            "is_multicurrency",
            "is_company_setting",
            "is_audit_log",
            "is_attachment",
            "is_user_role_management",
            "is_terms",
            "is_payment_management",
            "is_configuration",
            "is_user_profile",
            "is_support_ticket",
            "is_ai_finzify",
            "is_auto_renew",
            "is_enable_email_notification",
            "cancel_policy",
            "note",
            # Accountant related
            "is_monthly_bookkeeping_and_reconciliations",
            "is_reports",
            "is_annual_tax_filing",
            "is_1099_preparation_filing",
            "is_30_minute_consultation_per_quarter",
            "is_monthly_or_biweekly_payroll_processing",
            "is_quarterly_tax_planning_reviews",
            "is_budgeting_and_cash_flow_forecasting",
            "is_sales_tax_filing",
            "is_unlimited_email_support",
            "is_dedicated_accountant",
            "is_Virtual_CFO_services",
            "is_financial_modeling_and_custom_dashboards",
            "is_investo_ready_financial_statements",
            "is_audit_support_and_representation",
            "is_year_end_planning_for_tax_minimization",
            "is_multi_entity_or_multi_state_handling",
            "is_priority_support",
            "created_at",
            "updated_at",
        ]


class PublicSubscriptionPriceListSerializer(ModelSerializer):
    class Meta:
        model = SubscriptionPrice
        fields = [
            "slug",
            "billing_frequency",
            "price",
            "discount",
            "discount_kind",
            "created_at",
            "updated_at",
        ]
