# Generated by Django 5.1.1 on 2024-11-18 13:03

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import termio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0001_initial'),
        ('customerio', '0001_initial'),
        ('supplierio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=50)),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], default='PAYMENT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TermConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=termio.django_rest.helpers.slug_helpers.get_term_connector_slug, unique=True)),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=50)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termio.term')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
