# Generated by Django 5.1.1 on 2024-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='kind',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase')], default='PAYMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='termconnector',
            name='kind',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase')], max_length=50),
        ),
    ]
