# Generated by Django 5.1.1 on 2024-12-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0001_initial'),
        ('termio', '0002_alter_term_kind_alter_termconnector_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='termconnector',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.sale'),
        ),
        migrations.AlterField(
            model_name='term',
            name='kind',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale')], default='PAYMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='termconnector',
            name='kind',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=50),
        ),
    ]
