# Generated by Django 5.1.1 on 2025-01-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termio', '0003_termconnector_sale_alter_term_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='kind',
        ),
    ]
