# Generated by Django 5.1.1 on 2025-02-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0009_remove_purchase_term_purchaseitem_purchase_price'),
        ('termio', '0004_remove_term_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='termconnector',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase'),
        ),
    ]
