# Generated by Django 5.1.1 on 2026-05-05 11:32

import autoslug.fields
import datamigrationio.django_rest.helpers.slug_helpers
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('companyio', '0019_remove_companyuser_role'),
        ('customerio', '0008_customer_charter_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=datamigrationio.django_rest.helpers.slug_helpers.get_data_migrations_jobs_slug, unique=True)),
                ('data_type', models.CharField(choices=[('invoices', 'Invoices'), ('estimates', 'Estimates'), ('sales_receipts', 'Sales Receipts'), ('deposits', 'Deposits'), ('bills', 'Bills'), ('purchase_orders', 'Purchase Orders'), ('expenses', 'Expenses'), ('checks', 'Checks'), ('journal_entries', 'Journal Entries'), ('bank_data', 'Bank Data'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('products', 'Products'), ('chart_of_accounts', 'Chart of Accounts'), ('employees', 'Employees'), ('locations', 'Locations'), ('opening_balances', 'Opening Balances'), ('time_activities', 'Time Activities'), ('open_transactions', 'Open Transactions'), ('historical_transactions', 'Historical Transactions')], default='invoices', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='data_migrations/files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('previewed', 'Previewed'), ('validated', 'Validated'), ('impact_reviewed', 'Impact Reviewed'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('current_step', models.CharField(choices=[('select_data_type', 'Select Data Type'), ('upload_file', 'Upload File'), ('map_fields', 'Map Fields'), ('preview_data', 'Preview Data'), ('validate_data', 'Validate Data'), ('review_impact', 'Review Impact'), ('confirm_import', 'Confirm Import'), ('results_audit', 'Results & Audit')], default='select_data_type', max_length=50)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_columns', models.PositiveIntegerField(default=0)),
                ('ready_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('partially_imported_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_handling', models.CharField(choices=[('skip_duplicates', 'Skip Duplicates')], default='skip_duplicates', max_length=50)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('decimal_format', models.CharField(default='1,234.56', max_length=20)),
                ('has_header_row', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_migration_jobs', to='companyio.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_migration_jobs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_migration_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataMigrationFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=datamigrationio.django_rest.helpers.slug_helpers.get_data_migration_field_mapping_slug)),
                ('source_column', models.CharField(max_length=100)),
                ('target_field', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('affects_accounting', models.BooleanField(default=False)),
                ('status', models.CharField(default='mapped', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='datamigrationio.datamigrationjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataMigrationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=datamigrationio.django_rest.helpers.slug_helpers.get_data_migration_row_slug)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('mapped_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('warning', 'Warning'), ('error', 'Error'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('linked_record_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_record_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='datamigrationio.datamigrationjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataMigrationImpactLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=datamigrationio.django_rest.helpers.slug_helpers.get_data_migration_impact_line_slug)),
                ('transaction_type', models.CharField(max_length=50)),
                ('account_title', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tax', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('report_impact', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerio.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_lines', to='datamigrationio.datamigrationjob')),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_lines', to='datamigrationio.datamigrationrow')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DataMigrationValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=datamigrationio.django_rest.helpers.slug_helpers.get_data_migration_validation_issue_slug)),
                ('issue_type', models.CharField(choices=[('customer_not_found', 'Customer Not Found'), ('product_not_found', 'Product Not Found'), ('product_income_account_missing', 'Product Income Account Missing'), ('income_account_not_found', 'Income Account Not Found'), ('tax_not_found', 'Tax Not Found'), ('warehouse_not_found', 'Warehouse Not Found'), ('term_not_found', 'Term Not Found'), ('invalid_date', 'Invalid Date'), ('invalid_amount', 'Invalid Amount'), ('amount_mismatch', 'Amount Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('missing_required_field', 'Missing Required Field'), ('closed_period', 'Closed Accounting Period')], max_length=50)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('duplicate', 'Duplicate')], max_length=20)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('fix_payload', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='datamigrationio.datamigrationjob')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_migration_issues', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='datamigrationio.datamigrationrow')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
