# Generated by Django 5.1.1 on 2026-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamigrationio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigrationjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('previewed', 'Previewed'), ('validated', 'Validated'), ('impact_reviewed', 'Impact Reviewed'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partially_completed', 'Partially Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled Back'), ('partially_rolled_back', 'Partially Rolled Back')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='datamigrationrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('warning', 'Warning'), ('error', 'Error'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('imported', 'Imported'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
    ]
