# Generated by Django 5.1.1 on 2026-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamigrationio', '0002_alter_datamigrationjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigrationvalidationissue',
            name='issue_type',
            field=models.CharField(choices=[('customer_not_found', 'Customer Not Found'), ('product_not_found', 'Product Not Found'), ('product_income_account_missing', 'Product Income Account Missing'), ('income_account_not_found', 'Income Account Not Found'), ('tax_not_found', 'Tax Not Found'), ('warehouse_not_found', 'Warehouse Not Found'), ('term_not_found', 'Term Not Found'), ('invalid_date', 'Invalid Date'), ('invalid_amount', 'Invalid Amount'), ('amount_mismatch', 'Amount Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('duplicate_estimate', 'Duplicate Estimate'), ('missing_required_field', 'Missing Required Field'), ('closed_period', 'Closed Accounting Period')], max_length=50),
        ),
    ]
