# Generated by Django 5.1.1 on 2026-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamigrationio', '0004_alter_datamigrationvalidationissue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamigrationvalidationissue',
            name='issue_type',
            field=models.CharField(choices=[('customer_not_found', 'Customer Not Found'), ('product_not_found', 'Product Not Found'), ('product_income_account_missing', 'Product Income Account Missing'), ('income_account_not_found', 'Income Account Not Found'), ('deposit_account_not_found', 'Deposit Account Not Found'), ('tax_not_found', 'Tax Not Found'), ('warehouse_not_found', 'Warehouse Not Found'), ('term_not_found', 'Term Not Found'), ('invalid_date', 'Invalid Date'), ('invalid_amount', 'Invalid Amount'), ('amount_mismatch', 'Amount Mismatch'), ('duplicate_invoice', 'Duplicate Invoice'), ('duplicate_sale_receipt', 'Duplicate Sale Receipt'), ('duplicate_estimate', 'Duplicate Estimate'), ('duplicate_purchase_order', 'Duplicate Purchase Order'), ('vendor_not_found', 'Vendor Not Found'), ('expense_account_not_found', 'Expense Account Not Found'), ('missing_required_field', 'Missing Required Field'), ('closed_period', 'Closed Accounting Period')], max_length=50),
        ),
    ]
