# Generated by Django 5.1.1 on 2025-01-26 07:05

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import notificationio.django_rest.helpers.slug_helpers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0007_companysetting_multi_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=notificationio.django_rest.helpers.slug_helpers.get_notification_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=50)),
                ('model_kind', models.CharField(choices=[('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('SALE', 'Sale'), ('SALE_RECEIPT', 'Sale Receipt'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('INBOX', 'Inbox'), ('STOCK_ALERT', 'Stock Alert'), ('DISPUT', 'Disput')], max_length=50)),
                ('kind', models.CharField(choices=[('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_SHARED', 'Invoice Shared'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INVOICE_OVERDUE', 'Invoice Overdue'), ('PAYMENT_FAILED', 'Payment Failed'), ('PURCHASE_PAYMENT_DUE', 'Purchase Payment Due'), ('BILL_OVERDUE', 'Bill Overdue'), ('BILL_PAYMENT', 'Bill Payment'), ('PURCHASE_CREATED', 'Purchase Created'), ('SCHEDULED_MAINTENANCE', 'Scheduled Maintenance'), ('SOFTWARE_UPDATE', 'Software Update'), ('ERROR_REPORT', 'Error Report'), ('WEEKLY_SUMMARY_REPORT', 'Weekly Summary Report'), ('MONTHLY_PROFIT_AND_LOSS_REPORT', 'Monthly Profit And Loss Report'), ('CASH_FLOW_INSIGHT', 'Cash Flow Insight'), ('NEW_PRODUCT', 'New Product'), ('DISPUT', 'Disput')], max_length=50)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=notificationio.django_rest.helpers.slug_helpers.get_notification_slug, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificationio.notification')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
