# Generated by Django 5.1.1 on 2025-01-26 07:13

import autoslug.fields
import notificationio.django_rest.helpers.slug_helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=notificationio.django_rest.helpers.slug_helpers.get_notification_setting_slug, unique=True),
        ),
    ]
