# Generated by Django 5.1.1 on 2025-01-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0006_alter_thread_author'),
        ('notificationio', '0002_alter_notificationsetting_slug'),
        ('purchaseio', '0008_purchasesetting'),
        ('salesio', '0011_salesetting'),
        ('stockio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messageio.inbox'),
        ),
        migrations.AddField(
            model_name='notification',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase'),
        ),
        migrations.AddField(
            model_name='notification',
            name='purchase_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.sale'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sale_payment_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salepaymentreceive'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sale_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salereceipt'),
        ),
        migrations.AddField(
            model_name='notification',
            name='stock_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockio.stockalert'),
        ),
    ]
