# Generated by Django 5.1.1 on 2025-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationio', '0006_alter_notification_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sale_receipt',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_SHARED', 'Invoice Shared'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INVOICE_OVERDUE', 'Invoice Overdue'), ('PAYMENT_FAILED', 'Payment Failed'), ('PURCHASE_PAYMENT_DUE', 'Purchase Payment Due'), ('BILL_OVERDUE', 'Bill Overdue'), ('BILL_PAYMENT', 'Bill Payment'), ('PURCHASE_CREATED', 'Purchase Created'), ('BILL_CREATED', 'Bill Created'), ('SCHEDULED_MAINTENANCE', 'Scheduled Maintenance'), ('SOFTWARE_UPDATE', 'Software Update'), ('ERROR_REPORT', 'Error Report'), ('WEEKLY_SUMMARY_REPORT', 'Weekly Summary Report'), ('MONTHLY_PROFIT_AND_LOSS_REPORT', 'Monthly Profit And Loss Report'), ('CASH_FLOW_INSIGHT', 'Cash Flow Insight'), ('NEW_PRODUCT', 'New Product'), ('DISPUT', 'Disput')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='model_kind',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('SALE', 'Sale'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('INBOX', 'Inbox'), ('STOCK_ALERT', 'Stock Alert'), ('DISPUT', 'Disput')], max_length=50),
        ),
    ]
