# Generated by Django 5.1.1 on 2025-01-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0002_paymentinformation'),
        ('subscriptionio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptionio.subscription'),
        ),
    ]
