# Generated by Django 5.1.1 on 2025-01-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0003_paymentinformation_subscription'),
        ('subscriptionio', '0002_alter_subscriptionprice_billing_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='subscription_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptionio.subscriptionprice'),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptionio.subscription'),
        ),
    ]
