# Generated by Django 5.1.1 on 2025-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0004_paymentinformation_subscription_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='invoice_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
