# Generated by Django 5.1.1 on 2025-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0005_alter_paymentinformation_invoice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale'), ('REFUND', 'Refund'), ('PURCHASE', 'Purchase'), ('COMPANY_SUBSCRIPTION', 'Company Subscription'), ('ACCOUNTANT_SUBSCRIPTION', 'Accountant Subscription')], db_index=True, default='COMPANY_SUBSCRIPTION', max_length=50),
        ),
    ]
