# Generated by Django 5.1.1 on 2025-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0006_alter_paymentinformation_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='is_subscription_completed',
            field=models.BooleanField(default=False),
        ),
    ]
