# Generated by Django 5.1.1 on 2026-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0007_paymentinformation_is_subscription_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='stripe_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
