# Generated by Django 5.1.1 on 2024-11-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminio", "0002_companyrole"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyrole",
            name="permission",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
    ]
