# Generated by Django 5.1.1 on 2026-05-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminio', '0009_report_section_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrole',
            options={},
        ),
    ]
