# Generated by Django 5.1.1 on 2026-09-28 08:34

import dirtyfields.dirtyfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.CharField(db_index=True, default='BD', max_length=8)),
                ('family', models.CharField(choices=[('TAX', 'Income tax'), ('LABOUR', 'Labour law')], max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='PUBLISHED', max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('jurisdiction', 'family', '-effective_from'),
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'family', 'version'), name='rulebookio_ruleset_unique_version'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='rulebookio_ruleset_window_not_inverted')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
