# Generated by Django 5.1.1 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
