# Generated by Django 5.1.1 on 2024-12-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0004_journalentryconnector_tax'),
        ('tagio', '0002_alter_tag_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconnector',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalio.journalentry'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
