# Generated by Django 5.1.1 on 2024-12-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0001_initial'),
        ('tagio', '0003_tagconnector_journal_entry_alter_tag_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconnector',
            name='credit_noteio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
