# Generated by Django 5.1.1 on 2024-12-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagio', '0004_tagconnector_credit_noteio_item_alter_tag_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagconnector',
            old_name='credit_noteio_item',
            new_name='credit_note_item',
        ),
    ]
