# Generated by Django 5.1.1 on 2024-12-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0002_creditnote_supplier'),
        ('tagio', '0005_rename_credit_noteio_item_tagconnector_credit_note_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagconnector',
            name='credit_note_item',
        ),
        migrations.AddField(
            model_name='tagconnector',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote'),
        ),
    ]
