# Generated by Django 5.1.1 on 2025-01-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0007_purchaseitem_note_purchasepayment_and_more'),
        ('tagio', '0006_remove_tagconnector_credit_note_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconnector',
            name='purchase_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('PURCHASE_PAYMENT', 'Purchase Payment')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
