# Generated by Django 5.1.1 on 2025-07-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagio', '0008_tagconnector_pay_bill_alter_tag_kind'),
        ('transactionio', '0011_remove_bankdeposit_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagconnector',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionio.bankdeposit'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('BANK_DEPOSIT', 'Bank Deposit')], default='PRODUCT', max_length=50, null=True),
        ),
    ]
