# Generated by Django 5.1.1 on 2024-11-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='supplierio.supplier'),
        ),
    ]
