# Generated by Django 5.1.1 on 2024-11-29 23:27

import supplierio.django_rest.helpers.media_path
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierio', '0002_supplier_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=supplierio.django_rest.helpers.media_path.get_customer_media_path_prefix, verbose_name='Image'),
        ),
    ]
