# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierio', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='billing_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
