# Generated by Django 5.1.1 on 2024-12-07 09:38

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import fileroomio.django_rest.helpers.media_path
import fileroomio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachmentio', '0002_alter_attachment_image'),
        ('companyio', '0003_alter_companyuser_role'),
        ('customerio', '0006_alter_customer_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=fileroomio.django_rest.helpers.slug_helpers.get_fileitem_slug, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=fileroomio.django_rest.helpers.media_path.get_fileitem_path_prefix)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UN_PUBLISHED', 'Un Published'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FileItemConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=fileroomio.django_rest.helpers.slug_helpers.get_fileitem_connector_slug, unique=True)),
                ('model_kind', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment')], max_length=50)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachmentio.attachment')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerio.customer')),
                ('file_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileroomio.fileitem')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
