# Generated by Django 5.1.1 on 2024-12-12 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0003_fileitemconnector_sale_and_more'),
        ('messageio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messageio.thread'),
        ),
    ]
