# Generated by Django 5.1.1 on 2024-12-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0004_fileitemconnector_thread'),
        ('journalio', '0004_journalentryconnector_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalio.journalentry'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry')], max_length=50),
        ),
    ]
