# Generated by Django 5.1.1 on 2024-12-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0001_initial'),
        ('fileroomio', '0005_fileitemconnector_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='credit_noteio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item')], max_length=50),
        ),
    ]
