# Generated by Django 5.1.1 on 2025-01-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0008_fileitemconnector_sale_payment_receive_and_more'),
        ('productio', '0007_product_is_addtional_cost_productadditionalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productio.product'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT', 'Product')], max_length=50),
        ),
    ]
