# Generated by Django 5.1.1 on 2025-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0010_fileitemconnector_purchase_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('CREDIT_NOTE', 'Credit Note'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT', 'Product'), ('PURCHASE_PAYMENT', 'Purchase Payment')], max_length=50),
        ),
    ]
