# Generated by Django 5.1.1 on 2025-02-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0011_alter_fileitemconnector_model_kind'),
        ('purchaseio', '0018_paybill_paybillitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='pay_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.paybill'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('CREDIT_NOTE', 'Credit Note'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT', 'Product'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill')], max_length=50),
        ),
    ]
