# Generated by Django 5.1.1 on 2025-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0012_fileitemconnector_pay_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('WORD', 'Word'), ('TEXT', 'Text'), ('OTHER', 'Other'), ('AUDIO', 'Audio')], max_length=50),
        ),
    ]
