# Generated by Django 5.1.1 on 2025-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0013_alter_fileitem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
