# Generated by Django 5.1.1 on 2025-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0015_alter_fileitem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('PDF', 'PDF'), ('EXCEL', 'Excel'), ('WORD', 'Word'), ('TEXT', 'Text'), ('AUDIO', 'Audio'), ('ARCHIVE', 'Archive'), ('PPT', 'Power Point'), ('SCRIPT', 'Script'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
