# Generated by Django 5.1.1 on 2025-07-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0016_alter_fileitem_kind'),
        ('transactionio', '0011_remove_bankdeposit_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactionio.bankdeposit'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('CREDIT_NOTE', 'Credit Note'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT', 'Product'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('BANK_DEPOSIT', 'Bank Deposit')], max_length=50),
        ),
    ]
