# Generated by Django 5.1.1 on 2026-07-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileroomio', '0018_fileitemconnector_employee_and_more'),
        ('recurringio', '0014_recurringoccurrence_generated_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitemconnector',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recurringio.recurringtemplate'),
        ),
        migrations.AlterField(
            model_name='fileitemconnector',
            name='model_kind',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PURCHASE', 'Purchase'), ('EMPLOYEE', 'Employee'), ('THREAD', 'Thread'), ('ATTACHMENT', 'Attachment'), ('SALE', 'Sale'), ('JOURNAL_ENTRY', 'Journal Entry'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('CREDIT_NOTE', 'Credit Note'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PRODUCT', 'Product'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('PAY_BILL', 'Pay Bill'), ('BANK_DEPOSIT', 'Bank Deposit'), ('RECURRING_TEMPLATE', 'Recurring Template')], max_length=50),
        ),
    ]
