# Generated by Django 5.1.1 on 2025-09-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbanditsio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxbanditsbusinessaccount',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=250),
        ),
    ]
