# Generated by Django 5.1.1 on 2025-09-26 09:34

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import taxbanditsio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0001_initial'),
        ('taxbanditsio', '0002_alter_taxbanditsbusinessaccount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxBanditsReturn940',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=taxbanditsio.django_rest.helpers.slug_helpers.get_tax_bandits_return_940_slug, unique=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('record_id', models.CharField(blank=True, max_length=64, null=True)),
                ('submission_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TRANSMITTED', 'Transmitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=250)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxbanditsio.taxbanditsbusinessaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
