# Generated by Django 5.1.1 on 2025-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxbanditsio', '0003_taxbanditsreturn940'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbanditsreturn940',
            name='filing_reference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxbanditsreturn940',
            name='from_940_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
