# Generated by Django 5.1.1 on 2024-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_email_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-step verification via email passcode.'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_sms_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-step verification via SMS.'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-step verification via email passcode.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sms_verification_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-step verification via SMS.'),
        ),
    ]
