# Generated by Django 5.1.1 on 2024-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_historicaluser_status_alter_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='kind',
            field=models.CharField(choices=[('LEDGER', 'Ledger'), ('GROUP', 'Group'), ('BANK', 'Bank')], max_length=50),
        ),
    ]
