# Generated by Django 5.1.1 on 2024-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_chartofaccount_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='kind',
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('debtors', 'Debtors'), ('current_assets', 'Current Assets'), ('cash_at_bank', 'Cash at Bank and in Hand'), ('tangible_assets', 'Tangible Assets'), ('non_current_assets', 'Non-current Assets'), ('creditors', 'Creditors'), ('credit_card', 'Credit Card'), ('current_liabilities', 'Current Liabilities'), ('non_current_liabilities', 'Non-current Liabilities'), ('equity', 'Equity'), ('income', 'Income'), ('other_income', 'Other Income'), ('cost_of_sales', 'Cost of Sales'), ('expenses', 'Expenses'), ('other_expense', 'Other Expense')], default='current_assets', max_length=50),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='detail_type',
            field=models.CharField(choices=[('allowance_bad_debts', 'Allowance for Bad Debts'), ('called_up_share_capital', 'Called up Share Capital Not Paid'), ('development_costs', 'Development Costs'), ('employee_cash_advances', 'Employee Cash Advances'), ('investments_other', 'Investments - Other'), ('loans_to_officers', 'Loans to Officers'), ('loans_to_others', 'Loans to Others'), ('loans_to_shareholders', 'Loans to Shareholders'), ('other_current_assets', 'Other Current Assets'), ('prepaid_expenses', 'Prepaid Expenses'), ('retainage', 'Retainage'), ('stock', 'Stock'), ('undeposited_funds', 'Undeposited Funds')], default='other_current_assets', max_length=50),
        ),
    ]
