# Generated by Django 5.1.1 on 2024-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_chartofaccount_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
