# Generated by Django 5.1.1 on 2024-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chartofaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('DEBTORS', 'Debtors'), ('CURRENT_ASSETS', 'Current Assets'), ('CASH_AT_BANK', 'Cash at Bank and in Hand'), ('TANGIBLE_ASSETS', 'Tangible Assets'), ('NON_CURRENT_ASSETS', 'Non-current Assets'), ('CREDITORS', 'Creditors'), ('CREDIT_CARD', 'Credit Card'), ('CURRENT_LIABILITIES', 'Current Liabilities'), ('NON_CURRENT_LIABILITIES', 'Non-current Liabilities'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('OTHER_INCOME', 'Other Income'), ('COST_OF_SALES', 'Cost of Sales'), ('EXPENSES', 'Expenses'), ('OTHER_EXPENSE', 'Other Expense')], default='CURRENT_ASSETS', max_length=50),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='detail_type',
            field=models.CharField(choices=[('ALLOWANCE_FOR_BAD_DEBTS', 'Allowance for Bad Debts'), ('CALLED_UP_SHARE_CAPITAL', 'Called up Share Capital Not Paid'), ('DEVELOPMENT_COSTS', 'Development Costs'), ('EMPLOYEE_CASH_ADVANCES', 'Employee Cash Advances'), ('INVESTMENTS_OTHER', 'Investments - Other'), ('LOANS_TO_OFFICERS', 'Loans to Officers'), ('LOANS_TO_OTHERS', 'Loans to Others'), ('LOANS_TO_SHAREHOLDERS', 'Loans to Shareholders'), ('OTHER_CURRENT_ASSETS', 'Other Current Assets'), ('PREPAID_EXPENSES', 'Prepaid Expenses'), ('RETAINAGE', 'Retainage'), ('STOCK', 'Stock'), ('UNDEPOSITED_FUNDS', 'Undeposited Funds')], default='OTHER_CURRENT_ASSETS', max_length=50),
        ),
    ]
