# Generated by Django 5.1.1 on 2024-12-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chartofaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
