# Generated by Django 5.1.1 on 2025-01-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(blank=True, default='#-901777', max_length=10, null=True, unique=True),
        ),
    ]
