# Generated by Django 5.1.1 on 2025-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_chartofaccount__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(default='#-891815', max_length=10, unique=True),
        ),
    ]
