# Generated by Django 5.1.1 on 2025-01-17 20:05

import accounts.django_rest.helpers.media_path
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_chartofaccount__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(default='#-788887', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=accounts.django_rest.helpers.media_path.get_user_media_path_prefix, verbose_name='Image'),
        ),
    ]
