# Generated by Django 5.1.1 on 2025-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_chartofaccount__id_alter_historicaluser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(default='#-298615', max_length=10, unique=True),
        ),
    ]
