# Generated by Django 5.1.1 on 2025-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_accountingsetting_alter_chartofaccount__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(default='#-587419', max_length=10, unique=True),
        ),
    ]
