# Generated by Django 5.1.1 on 2025-01-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_chartofaccount__id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingSetting',
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='_id',
            field=models.CharField(default='#-779760', max_length=30, unique=True),
        ),
    ]
