# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_chartofaccount_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
