# Generated by Django 5.1.1 on 2025-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_chartofaccount_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='used_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
