# Generated by Django 5.1.1 on 2025-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_chartofaccount_used_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='kind',
            field=models.CharField(choices=[('EXPENSES', 'Expenses'), ('INCOMES', 'Incomes'), ('EQUITY', 'Equity'), ('REMOVED', 'Liabilities'), ('ASSETS', 'Assets')], default='ASSETS', max_length=50),
        ),
    ]
