# Generated by Django 5.1.1 on 2025-02-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_chartofaccount_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='detail_type',
        ),
    ]
