# Generated by Django 5.1.1 on 2025-02-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_chartofaccount_account_type_and_more'),
        ('categoryio', '0008_alter_category_company_alter_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_categories', to='categoryio.category'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='detail_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_categories', to='categoryio.category'),
        ),
    ]
