# Generated by Django 5.1.1 on 2025-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_chartofaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='kind',
            field=models.CharField(choices=[('EXPENSES', 'Expenses'), ('INCOMES', 'Incomes'), ('EQUITY', 'Equity'), ('LIABILITIES', 'Liabilities'), ('ASSETS', 'Assets')], default='ASSETS', max_length=50),
        ),
    ]
