# Generated by Django 5.1.1 on 2025-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_chartofaccount_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
