# Generated by Django 5.1.1 on 2025-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_chartofaccount_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='kind',
            field=models.CharField(choices=[('EXPENSES', 'Expenses'), ('INCOMES', 'Incomes'), ('EQUITIES', 'Equities'), ('LIABILITIES', 'Liabilities'), ('ASSETS', 'Assets')], default='ASSETS', max_length=50),
        ),
    ]
