# Generated by Django 5.1.1 on 2025-04-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_chartofaccount_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='_id',
        ),
    ]
