# Generated by Django 5.1.1 on 2025-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_chartofaccount__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='bank_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='bank_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
