# Generated by Django 5.1.1 on 2025-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_historicaluser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
