# Generated by Django 5.1.1 on 2025-07-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_historicaluser_ssn_user_ssn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
