# Generated by Django 5.1.15 on 2026-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_default_groups'),
        ('categoryio', '0008_alter_category_company_alter_category_kind'),
        ('companyio', '0024_alter_companydesignation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='system_key',
            field=models.CharField(blank=True, choices=[('AR', 'Accounts Receivable'), ('AP', 'Accounts Payable'), ('INVENTORY_ASSET', 'Inventory Asset'), ('UNDEPOSITED_FUNDS', 'Undeposited Funds'), ('OPENING_BALANCE_EQUITY', 'Opening Balance Equity'), ('SALES_TAX_PAYABLE', 'Sales Tax Payable'), ('COGS', 'Cost of Goods Sold'), ('SALES_OF_PRODUCT_INCOME', 'Sales of Product Income'), ('SERVICE', 'Service'), ('OTHER_MISC_EXPENSE', 'Other Miscellaneous Expense')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False), models.Q(('status', 'REMOVED'), _negated=True)), fields=('company', 'system_key'), name='unique_system_key_per_company'),
        ),
    ]
