# Generated by Django 5.1.15 on 2026-08-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_chartofaccount_system_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='system_key',
            field=models.CharField(blank=True, choices=[('AR', 'Accounts Receivable'), ('AP', 'Accounts Payable'), ('INVENTORY_ASSET', 'Inventory Asset'), ('UNDEPOSITED_FUNDS', 'Undeposited Funds'), ('OPENING_BALANCE_EQUITY', 'Opening Balance Equity'), ('SALES_TAX_PAYABLE', 'Sales Tax Payable'), ('COGS', 'Cost of Goods Sold'), ('SALES_OF_PRODUCT_INCOME', 'Sales of Product Income'), ('SERVICE', 'Service'), ('OTHER_MISC_EXPENSE', 'Other Miscellaneous Expense'), ('SALES_DISCOUNTS', 'Sales Discounts'), ('SHIPPING_INCOME', 'Shipping Income')], db_index=True, max_length=50, null=True),
        ),
    ]
