# Generated by Django 5.1.15 on 2026-08-10 07:40

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_chartofaccount_system_key'),
        ('categoryio', '0008_alter_category_company_alter_category_kind'),
        ('companyio', '0024_alter_companydesignation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('title'), models.F('company'), condition=models.Q(models.Q(('status', 'REMOVED'), _negated=True), models.Q(('title__isnull', True), _negated=True), models.Q(('title__exact', ''), _negated=True)), name='unique_title_per_company_ci'),
        ),
    ]
