# Generated by Django 5.1.15 on 2026-08-24 10:49

"""Add `ChartOfAccount.is_money_account`.

Phase 1 of `BANK_REGISTER_FIX_PLAN.md`. Nothing in the schema could say whether
an account is one money moves through; the de-facto test was a user-editable
Category title matched exactly. The backfill is a separate migration (0047) so
the schema change and the data change can be reasoned about, and reverted,
independently.

The `system_key` AlterField is unrelated drift: the choices list in the model
had moved ahead of the last migration to record it. Choices are not enforced in
PostgreSQL, so that operation is a no-op against the database -- it is included
only because `makemigrations` regenerates it for anyone who runs it otherwise.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_chartofaccount_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_money_account',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='system_key',
            field=models.CharField(blank=True, choices=[('AR', 'Accounts Receivable'), ('AP', 'Accounts Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('INVENTORY_ASSET', 'Inventory Asset'), ('UNDEPOSITED_FUNDS', 'Undeposited Funds'), ('OPENING_BALANCE_EQUITY', 'Opening Balance Equity'), ('SALES_TAX_PAYABLE', 'Sales Tax Payable'), ('COGS', 'Cost of Goods Sold'), ('SALES_OF_PRODUCT_INCOME', 'Sales of Product Income'), ('SERVICE', 'Service'), ('OTHER_MISC_EXPENSE', 'Other Miscellaneous Expense'), ('SALES_DISCOUNTS', 'Sales Discounts'), ('SHIPPING_INCOME', 'Shipping Income'), ('RECONCILIATION_DISCREPANCIES', 'Reconciliation Discrepancies'), ('PAYROLL_LIABILITIES', 'Payroll Liabilities'), ('FEDERAL_TAX_941', 'Federal Taxes (941/943/944)'), ('FEDERAL_UNEMPLOYMENT_940', 'Federal Unemployment (940)')], db_index=True, max_length=50, null=True),
        ),
    ]
