# Generated by Django 5.1.1 on 2024-11-13 20:52

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import productio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_chartofaccount_kind_and_more'),
        ('companyio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=productio.django_rest.helpers.slug_helpers.get_product_slug, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, null=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('reorder_point', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service'), ('PROJECT', 'Project'), ('EVENT', 'Event')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], max_length=20)),
                ('is_non_stock', models.BooleanField(default=False)),
                ('is_bundle', models.BooleanField(default=False)),
                ('is_stock', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_account_set', to='accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_account_set', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
