# Generated by Django 5.1.1 on 2024-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productio', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
