# Generated by Django 5.1.1 on 2024-12-07 09:24

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productio', '0004_rename_is_bundle_product_is_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbundle',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductBundleConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productio.productbundle')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productio.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
