# Generated by Django 5.1.1 on 2024-12-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productio', '0005_remove_productbundle_product_productbundleconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
