# Generated by Django 5.1.1 on 2025-01-04 12:51

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
        ('agencyio', '0002_agency_start_of_period'),
        ('productio', '0006_product_expired_date'),
        ('supplierio', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_addtional_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
                ('prefferred_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productio.product')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyio.agencytax')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
