# Generated by Django 5.1.1 on 2025-01-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
        ('productio', '0007_product_is_addtional_cost_productadditionalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundleconnector',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_account_set', to='accounts.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_account_set', to='accounts.chartofaccount'),
        ),
    ]
