# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productio', '0008_productbundleconnector_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='productadditionalcost',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
