# Generated by Django 5.1.1 on 2025-04-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0002_agency_start_of_period'),
        ('productio', '0009_alter_product_sale_price_alter_product_vat_and_more'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionalcost',
            name='prefferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier'),
        ),
        migrations.AlterField(
            model_name='productadditionalcost',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyio.agencytax'),
        ),
    ]
