# Generated by Django 5.1.15 on 2026-08-07 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_chartofaccount_system_key'),
        ('productio', '0010_alter_productadditionalcost_prefferred_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cogs_account_set', to='accounts.chartofaccount'),
        ),
    ]
