# Generated by Django 5.1.1 on 2024-12-12 08:23

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import messageio.django_rest.helpers.slug_helpers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=messageio.django_rest.helpers.slug_helpers.get_thread_slug, unique=True)),
                ('kind', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child')], default='PARENT', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('author', models.ForeignKey(help_text="The 'User' who created the feed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='messageio.thread')),
            ],
            options={
                'ordering': ('created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=messageio.django_rest.helpers.slug_helpers.get_inbox_slug, unique=True)),
                ('ticket_noumber', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('kind', models.CharField(choices=[('SUPPORT_AND_TICKET', 'Support And Ticket'), ('PRIVATE_CHAT', 'Private Chat'), ('GROUP_CHAT', 'Group Chat')], default='SUPPORT_AND_TICKET', max_length=50)),
                ('user_kind', models.CharField(choices=[('USER', 'User'), ('AGENT', 'Agent'), ('CUSTOMER', 'Customer')], max_length=50)),
                ('is_seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(help_text="The 'User' who receive the thread", on_delete=django.db.models.deletion.CASCADE, related_name='inbox_target_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text="The 'User' who created the inbox.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageio.thread')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
