# Generated by Django 5.1.1 on 2024-12-12 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed'), ('COMPLETED', 'Completed'), ('ON_GOING', 'On Going'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='target',
            field=models.ForeignKey(blank=True, help_text="The 'User' who receive the thread", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_target_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(blank=True, help_text="The 'User' who created the inbox.", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
