# Generated by Django 5.1.1 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0002_alter_inbox_status_alter_inbox_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='ticket_noumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
