# Generated by Django 5.1.1 on 2024-12-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0003_alter_inbox_ticket_noumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='inbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messageio.inbox'),
        ),
    ]
