# Generated by Django 5.1.1 on 2025-01-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0004_alter_thread_options_remove_inbox_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messageio.inbox'),
        ),
    ]
