# Generated by Django 5.1.1 on 2025-01-17 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageio', '0005_alter_thread_inbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(blank=True, help_text="The 'User' who created the feed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
