# Generated by Django 5.1.1 on 2025-03-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedemoio', '0002_alter_livedemo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedemo',
            name='agent_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='preferred_version',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
