# Generated by Django 5.1.1 on 2025-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedemoio', '0003_livedemo_agent_count_livedemo_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedemo',
            name='is_mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='mail_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='mail_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livedemo',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
