# Generated by Django 5.1.1 on 2025-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedemoio', '0004_livedemo_is_mail_sent_livedemo_mail_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedemo',
            name='request_type',
            field=models.CharField(choices=[('LIVE_DEMO', 'Live Demo'), ('ACCOUNTANT_SERVICE', 'Accountant Service')], default='LIVE_DEMO', max_length=25),
        ),
    ]
