# Generated by Django 5.1.1 on 2024-11-11 14:23

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
import wirehouseio.django_rest.helpers.slug_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=wirehouseio.django_rest.helpers.slug_helpers.get_warehouse_slug, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('kind', models.CharField(choices=[('MAIN', 'Main'), ('TEMPORARY', 'Temporary')], default='MAIN', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
