# Generated by Django 5.1.1 on 2024-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirehouseio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
