# Generated by Django 5.1.1 on 2024-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirehouseio', '0002_alter_warehouse_remark_alter_warehouse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
