# Generated by Django 5.1.1 on 2024-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirehouseio', '0003_warehouse_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=50),
        ),
    ]
