"""Admin for recurring templates, their lines, and the occurrence ledger.

Loading notes — these models are unusually FK-heavy (25 across the three), so a
naive admin is very slow:

* Every FK uses ``raw_id_fields``. Without it each change form renders a
  ``<select>`` holding *every* customer, supplier, product, account, tax rate and
  warehouse in the database — one full-table query per FK, on every page load.
* List pages ``select_related`` exactly the columns they display, so a page of
  100 rows costs one query rather than one per row per FK.
* Line counts and occurrence counts are annotated in SQL rather than counted per
  row in Python.
* ``show_full_result_count`` is off: the unfiltered ``COUNT(*)`` Django runs to
  render "99 results (1,234 total)" is pure cost on a growing ledger.
"""

from django.contrib import admin
from django.db.models import Count

from .models import RecurringOccurrence, RecurringTemplate, RecurringTemplateLine


class RecurringTemplateLineInline(admin.TabularInline):
    """Lines edited in the context of their template."""

    model = RecurringTemplateLine
    extra = 0
    fields = [
        "position",
        "line_type",
        "product",
        "charter_account",
        "description",
        "quantity",
        "rate",
        "amount",
        "tax",
        "customer",
        "supplier",
        "payment_method",
        "reference_number",
    ]
    raw_id_fields = [
        "product",
        "charter_account",
        "tax",
        "customer",
        "supplier",
        "payment_method",
    ]
    ordering = ["position", "id"]

    def get_queryset(self, request):
        # The inline renders each line's related objects; fetch them with the
        # lines rather than one query per row.
        return (
            super()
            .get_queryset(request)
            .select_related("product", "charter_account", "tax")
        )


@admin.register(RecurringTemplate)
class RecurringTemplateAdmin(admin.ModelAdmin):
    list_display = [
        "name",
        "txn_type",
        "template_type",
        "status",
        "party",
        "total_amount",
        "next_run_date",
        "occurrences_generated",
        "line_count",
    ]
    list_filter = ["txn_type", "template_type", "status", "frequency"]
    search_fields = [
        "name",
        "supplier__display_name",
        "supplier__first_name",
        "customer__display_name",
        "customer__first_name",
    ]
    date_hierarchy = "next_run_date"
    ordering = ["-created_at"]
    inlines = [RecurringTemplateLineInline]

    # Every FK, so no change form ever renders a full-table dropdown.
    raw_id_fields = [
        "company",
        "supplier",
        "customer",
        "ship_to",
        "terms",
        "warehouse",
        "payment_account",
        "payment_method",
        "cash_back_account",
        "tax",
        "created_by",
    ]

    # Run state belongs to the generation job, not to a human. Editing
    # next_run_date or occurrences_generated by hand would silently re-fire or
    # skip real documents, so they are shown but not writable.
    readonly_fields = [
        "uid",
        "total_amount",
        "previous_run_date",
        "next_run_date",
        "occurrences_generated",
        "created_at",
        "updated_at",
    ]

    fieldsets = [
        (
            "Identity",
            {"fields": ["uid", "name", "txn_type", "template_type", "status"]},
        ),
        (
            "Schedule",
            {
                "fields": [
                    "frequency",
                    "interval_count",
                    "day_mode",
                    "day_of_month",
                    "weekday",
                    "ordinal",
                    "month_of_year",
                    "start_date",
                    "end_type",
                    "end_date",
                    "end_after_occurrences",
                    "create_days_in_advance",
                    "remind_days_before",
                ]
            },
        ),
        (
            "Run state (owned by the generation job)",
            {
                "fields": [
                    "total_amount",
                    "previous_run_date",
                    "next_run_date",
                    "occurrences_generated",
                ]
            },
        ),
        (
            "Party & document",
            {
                "fields": [
                    "company",
                    "supplier",
                    "customer",
                    "mailing_address",
                    "terms",
                    "warehouse",
                    "currency_code",
                    "memo",
                    "created_by",
                ]
            },
        ),
        (
            "Settlement & tax",
            {
                "fields": [
                    "payment_account",
                    "payment_method",
                    "tax_kind",
                    "tax",
                    "discount_kind",
                    "discount",
                    "shipping_fee",
                    "deposit",
                ]
            },
        ),
        (
            "Type-specific",
            {
                "classes": ["collapse"],
                "fields": [
                    # cheque
                    "cheque_number",
                    "print_later",
                    "permit_number",
                    # estimate / invoice / sales-side
                    "expiry_days",
                    "message_on_estimate",
                    "payment_instructions",
                    "include_unbilled_charges",
                    "internal_note",
                    "statement_memo",
                    "reference_number",
                    "tracking_number",
                    # payment
                    "when_to_charge",
                    "acceptance_status",
                    # deposit
                    "cash_back_account",
                    "cash_back_memo",
                    "cash_back_amount",
                    "track_returns",
                    # shipping
                    "shipping_from",
                    "ship_to",
                    "full_shipping_address",
                    "shipping_by",
                    # email
                    "email_to",
                    "email_cc",
                    "email_bcc",
                    "auto_email",
                    "autopay_enabled",
                ],
            },
        ),
        (
            "Timestamps",
            {"classes": ["collapse"], "fields": ["created_at", "updated_at"]},
        ),
    ]

    list_per_page = 50
    show_full_result_count = False

    def get_queryset(self, request):
        """Join what the list renders and count lines in SQL.

        The joins live here rather than in ``list_select_related`` because that
        is only applied by the changelist — anything else using this queryset
        (an action, an export) would fall back to one query per row.
        """
        return (
            super()
            .get_queryset(request)
            .select_related("supplier", "customer")
            .annotate(_line_count=Count("lines"))
        )

    @admin.display(description="Party", ordering="supplier__display_name")
    def party(self, obj):
        """The counterparty, whichever side this type uses.

        A DEPOSIT has neither — its payer lives on the fund rows.
        """
        party = obj.supplier or obj.customer
        if party is None:
            return "—"
        return (
            getattr(party, "display_name", None)
            or f"{party.first_name} {party.last_name or ''}".strip()
        )

    @admin.display(description="Lines", ordering="_line_count")
    def line_count(self, obj):
        return obj._line_count


@admin.register(RecurringTemplateLine)
class RecurringTemplateLineAdmin(admin.ModelAdmin):
    list_display = [
        "template",
        "position",
        "line_type",
        "product",
        "charter_account",
        "quantity",
        "rate",
        "amount",
    ]
    list_filter = ["line_type"]
    search_fields = ["template__name", "description", "reference_number"]
    ordering = ["template", "position"]
    raw_id_fields = [
        "company",
        "template",
        "charter_account",
        "product",
        "tax",
        "customer",
        "supplier",
        "payment_method",
    ]
    readonly_fields = ["uid", "created_at", "updated_at"]
    list_per_page = 50
    show_full_result_count = False

    def get_queryset(self, request):
        return (
            super()
            .get_queryset(request)
            .select_related("template", "product", "charter_account")
        )


@admin.register(RecurringOccurrence)
class RecurringOccurrenceAdmin(admin.ModelAdmin):
    """The run history: one row per (template, date) the job has acted on.

    This doubles as the idempotency ledger — ``unique(template,
    occurrence_date)`` is what stops a retried run double-billing — so rows are
    read-only here. Deleting one would let that date fire a second time.
    """

    list_display = [
        "occurrence_date",
        "template",
        "txn_type",
        "status",
        "generated_document",
        "resolved_at",
        "short_error",
    ]
    list_filter = ["status", "template__txn_type", "occurrence_date"]
    search_fields = ["template__name", "error_detail"]
    date_hierarchy = "occurrence_date"
    ordering = ["-occurrence_date", "-created_at"]
    raw_id_fields = [
        "company",
        "template",
        "generated_purchase",
        "generated_sale",
        "generated_credit_note",
        "generated_deposit",
    ]
    readonly_fields = [
        "uid",
        "template",
        "occurrence_date",
        "status",
        "reminded_at",
        "resolved_at",
        "error_detail",
        "generated_purchase",
        "generated_sale",
        "generated_credit_note",
        "generated_deposit",
        "company",
        "created_at",
        "updated_at",
    ]
    list_per_page = 50
    show_full_result_count = False

    def get_queryset(self, request):
        # Every column this list renders comes off a related object, so all of
        # them are joined -- see the note on the template admin.
        return (
            super()
            .get_queryset(request)
            .select_related(
                "template",
                "generated_purchase",
                "generated_sale",
                "generated_credit_note",
                "generated_deposit",
            )
        )

    def has_add_permission(self, request):
        # Occurrences are written by the generation job. A hand-made row would
        # silently prevent that date from ever firing.
        return False

    def has_change_permission(self, request, obj=None):
        return False

    @admin.display(description="Type", ordering="template__txn_type")
    def txn_type(self, obj):
        return obj.template.txn_type

    @admin.display(description="Generated")
    def generated_document(self, obj):
        """Whichever of the four document shapes this firing produced."""
        for label, document in (
            ("Purchase", obj.generated_purchase),
            ("Sale", obj.generated_sale),
            ("Credit note", obj.generated_credit_note),
            ("Deposit", obj.generated_deposit),
        ):
            if document is not None:
                return f"{label}: {document.uid}"
        return "—"

    @admin.display(description="Error")
    def short_error(self, obj):
        if not obj.error_detail:
            return ""
        return (obj.error_detail[:80] + "…") if len(obj.error_detail) > 80 else (
            obj.error_detail
        )
