# Generated by Django 5.1.1 on 2025-05-13 12:09

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import transactionio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyio', '0014_remove_company_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.get_transaction_method_slug, unique=True)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransactionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.get_transaction_information_slug, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('deposits_additions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('withdrawals_subtractions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(choices=[('FOR_REVIEW', 'For_Review'), ('CATEGORIZED', 'Categorized'), ('EXCLUDED', 'Excluded')], default='FOR_REVIEW', max_length=11)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date', 'description'], name='transaction_company_c005d1_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
