# Generated by Django 5.1.1 on 2025-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioninformation',
            old_name='deposits_additions',
            new_name='received',
        ),
        migrations.RenameField(
            model_name='transactioninformation',
            old_name='withdrawals_subtractions',
            new_name='spent',
        ),
    ]
