# Generated by Django 5.1.1 on 2025-05-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_chartofaccount__id'),
        ('transactionio', '0002_rename_deposits_additions_transactioninformation_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninformation',
            name='chart_of_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccount'),
        ),
    ]
