# Generated by Django 5.1.1 on 2025-05-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0003_transactioninformation_chart_of_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioninformation',
            old_name='chart_of_accounts',
            new_name='chart_of_account',
        ),
    ]
