# Generated by Django 5.1.1 on 2025-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0004_rename_chart_of_accounts_transactioninformation_chart_of_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninformation',
            name='check_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
