# Generated by Django 5.1.1 on 2025-05-15 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalio', '0022_alter_journalentry_kind'),
        ('transactionio', '0005_transactioninformation_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninformation',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalio.journalentry'),
        ),
    ]
