# Generated by Django 5.1.1 on 2025-05-28 11:01

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import transactionio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('companyio', '0014_remove_company_company_address_and_more'),
        ('customerio', '0008_customer_charter_account'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
        ('transactionio', '0006_transactioninformation_journal_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.trx_rule_slug, unique=True)),
                ('transaction_type', models.CharField(choices=[('RECEIVED', 'Received'), ('SPENT', 'Spent')], max_length=255)),
                ('all_account', models.BooleanField(default=False)),
                ('is_all', models.BooleanField(default=False)),
                ('auto_add', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
                ('bank_accounts', models.ManyToManyField(blank=True, to='accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransactionRuleParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.rule_params_slug, unique=True)),
                ('field', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='transactionio.transactionrules')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransactionRuleAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.rule_assign_slug, unique=True)),
                ('trx_type', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_split', models.BooleanField(default=False)),
                ('chart_of_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerio.customer')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplierio.supplier')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='transactionio.transactionrules')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
