# Generated by Django 5.1.1 on 2025-05-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0007_transactionrules_transactionruleparams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionruleassign',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='transactionio.transactionrules'),
        ),
    ]
