# Generated by Django 5.1.1 on 2025-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0008_alter_transactionruleassign_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionruleassign',
            name='trx_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card'), ('DEPOSIT', 'Deposit')], default='DEPOSIT', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionruleparams',
            name='field',
            field=models.CharField(choices=[('AMOUNT', 'Amount'), ('DESCRIPTION', 'Description'), ('BANK_TEXT', 'Bank Text')], default='DESCRIPTION', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionruleparams',
            name='operation',
            field=models.CharField(choices=[('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('IS_EXACTLY', 'Is Exactly'), ('EQUAL', 'Equal'), ('NOT_EQUAL', 'Not Equal'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than')], default='CONTAINS', max_length=255),
        ),
    ]
