# Generated by Django 5.1.1 on 2025-07-02 11:01

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import transactionio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('companyio', '0014_remove_company_company_address_and_more'),
        ('customerio', '0008_customer_charter_account'),
        ('employeeio', '0009_alter_employeesalary_basic_alter_employeesalary_cash_and_more'),
        ('journalio', '0027_journalentryconnector_credit_note_item'),
        ('paymentio', '0006_alter_paymentinformation_kind'),
        ('transactionio', '0009_alter_transactionruleassign_trx_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninformation',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.get_bank_deposit_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('cash_back_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_back_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('bank_chart_of_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalio.journalentry')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankDepositItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.get_bank_deposit_item_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Check number, transaction ID, or other reference', max_length=100, null=True)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('SALES_RECEIPT', 'Sales Receipt'), ('REFUND', 'Refund'), ('OTHER_INCOME', 'Other Income')], default='PAYMENT', max_length=50)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('bank_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_items', to='transactionio.bankdeposit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod')),
                ('received_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
