# Generated by Django 5.1.1 on 2025-07-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('customerio', '0008_customer_charter_account'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
        ('transactionio', '0010_transactioninformation_is_matched_bankdeposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='cash_back_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_back_account', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='bankdeposititem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplierio.supplier'),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdeposititem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerio.customer'),
        ),
        migrations.AlterField(
            model_name='bankdeposititem',
            name='received_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='bankdeposititem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
