# Generated by Django 5.1.1 on 2025-07-15 10:02

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import transactionio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('companyio', '0014_remove_company_company_address_and_more'),
        ('employeeio', '0001_initial'),
        ('transactionio', '0011_remove_bankdeposit_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=transactionio.django_rest.helpers.slug_helpers.get_bank_reconcile_slug, unique=True)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('statement_ending_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('statement_ending_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('reconciled_on', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounts.chartofaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
