# Generated by Django 5.1.1 on 2026-03-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0012_bankreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninformation',
            name='matched_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='transactionio.transactionrules'),
        ),
    ]
