# Generated by Django 5.1.15 on 2026-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0013_transactioninformation_matched_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='forced_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='forced_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='is_forced',
            field=models.BooleanField(default=False),
        ),
    ]
