# Generated by Django 5.1.15 on 2026-08-25 06:58

"""Session integrity, part 2: the three constraints. BR-15.

Generated from the model rather than hand-written, so the expressions cannot
drift from what `BankReconciliation.Meta` declares -- a hand-written first
attempt produced a constraint Django immediately wanted to rewrite.

  unique_reconciliation_per_account_period
      Nothing stopped two sessions on the same account and the same statement
      date, each ticking a different half of the same activity and each closing
      at a difference of zero.

  reconciliation_closed_iff_reconciled_on
      `is_closed` and `reconciled_on` were set together in one place and nothing
      else enforced the pairing, so a row could read closed with no date.

  reconciliation_forced_implies_reason_and_amount
      Without the reason and the unexplained amount, a forced close is
      indistinguishable from a clean one after the fact -- which is the entire
      point of recording it.

`AlterModelOptions(options={})` is a no-op: the model had no `Meta` before and
declares no options now, so Django is only recording that one exists.

Applies against an empty table (0 rows post-cleanup), so no row can violate
these on the way in.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_backfill_is_money_account'),
        ('companyio', '0025_enable_rls_supplier'),
        ('employeeio', '0001_initial'),
        ('transactionio', '0015_bankreconciliation_session_integrity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={},
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(fields=('company', 'bank_account', 'statement_ending_date'), name='unique_reconciliation_per_account_period'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_closed', True), ('reconciled_on__isnull', False)), models.Q(('is_closed', False), ('reconciled_on__isnull', True)), _connector='OR'), name='reconciliation_closed_iff_reconciled_on'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('is_forced', False), models.Q(('forced_difference__isnull', False), ('forced_reason__isnull', False), ('is_forced', True)), _connector='OR'), name='reconciliation_forced_implies_reason_and_amount'),
        ),
    ]
