# Generated by Django 5.1.15 on 2026-08-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
        ('transactionio', '0016_alter_bankreconciliation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_closed', to='employeeio.employee'),
        ),
    ]
