# Generated by Django 5.1.15 on 2026-08-26 10:10

"""A statement line is money in or money out. BR-18 and BR-30.

`received` and `spent` were independent, unvalidated and unconstrained, so a row
could carry both at once, or carry a negative, and whatever was there was summed
into the cleared total. Three CHECK constraints say what the columns mean.

They are NULL-safe by construction: `NULL >= 0` is NULL and a CHECK passes on
NULL, so an unparsed column stays unparsed rather than becoming a zero that
looks deliberate.

The widening from `(10, 2)` to `(19, 2)` is BR-30, and it is the same two lines.
Every figure these feed carries 19 digits -- `beginning_balance`,
`statement_ending_balance`, and the ledger's own `debit`/`credit` -- so the same
computation was being carried at two precisions, with the narrower end capping
silently at 99,999,999.99.

Applies against an empty table: `TransactionInformation` is 0 rows after the
2026-08-25 cleanup, so nothing can violate these on the way in. On a populated
table this would need a survey first -- a negative amount or a both-sides row
would abort the migration.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_backfill_is_money_account'),
        ('companyio', '0026_enable_rls_transactions'),
        ('journalio', '0039_alter_journalentry_options_and_more'),
        ('transactionio', '0017_bankreconciliation_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninformation',
            name='received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninformation',
            name='spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddConstraint(
            model_name='transactioninformation',
            constraint=models.CheckConstraint(condition=models.Q(('received__gte', 0), ('received__isnull', True), _connector='OR'), name='statement_line_received_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactioninformation',
            constraint=models.CheckConstraint(condition=models.Q(('spent__gte', 0), ('spent__isnull', True), _connector='OR'), name='statement_line_spent_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactioninformation',
            constraint=models.CheckConstraint(condition=models.Q(('received__gt', 0), ('spent__gt', 0), _negated=True), name='statement_line_is_receipt_or_payment_not_both'),
        ),
    ]
