# Generated by Django 5.1.15 on 2026-08-26 10:56

"""Replace `is_closed` with a status enum, and add the undo fields. Phase 5.

A boolean cannot survive undo. `is_closed=True` beside an `is_undone=True` means
*not closed*, and every reader that forgot the second flag would be wrong
silently rather than loudly -- including `derive_beginning_balance`, where being
wrong means a later session opens at a figure the bank never agreed to. Spec s21
names the states directly.

`is_forced` stays a separate flag. Forcing is a property of how a session
closed, not a place in its lifecycle; the spec's own data model lists `adjusted`
beside `status` for the same reason.

The period-uniqueness constraint becomes PARTIAL, over OPEN and CLOSED only. An
undone session keeps its row -- it is the only durable audit surface, this model
being unregistered with auditlog -- but must not hold the period hostage, or
undo would make a period permanently unreconcilable, which is the opposite of
its purpose.

Destructive: `is_closed` is dropped, and it is exposed on the API. Free right
now and not later -- `BankReconciliation` is 0 rows after the 2026-08-25
cleanup, and no client has ever read a successful response from these endpoints
(one was a 403 and one a 500 for every non-admin until 2026-08-24). Doing this
after real sessions exist would need a backfill and a deprecation window.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_backfill_is_money_account'),
        ('companyio', '0026_enable_rls_transactions'),
        ('employeeio', '0067_backfill_employee_company'),
        ('transactionio', '0018_alter_transactioninformation_received_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankreconciliation',
            name='unique_reconciliation_per_account_period',
        ),
        migrations.RemoveConstraint(
            model_name='bankreconciliation',
            name='reconciliation_closed_iff_reconciled_on',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('UNDONE', 'Undone')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='undo_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='undone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_undone', to='employeeio.employee'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='undone_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), fields=('company', 'bank_account', 'statement_ending_date'), name='unique_live_reconciliation_per_account_period'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reconciled_on__isnull', True), ('status', 'OPEN')), models.Q(('reconciled_on__isnull', False), ('status__in', ['CLOSED', 'UNDONE'])), _connector='OR'), name='reconciliation_closed_iff_reconciled_on'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'UNDONE'), _negated=True), models.Q(('undo_reason__isnull', False), ('undone_on__isnull', False)), _connector='OR'), name='reconciliation_undone_implies_reason_and_date'),
        ),
    ]
