# Generated by Django 5.1.15 on 2026-08-26 11:31

"""Freeze the reconciliation report at close. BR-35.

The report cannot be recomputed later: an amend appends a delta leg to a
document the session already cleared, a void appends a reversal, and both change
what the candidate query returns for a period that is already closed. Without
this, re-running last month's report gives a different answer from the one the
bank agreed to and nothing records that it moved.

Nullable, so every existing session reads as "no snapshot" -- which is what they
are. Only sessions closed from here on carry one.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionio', '0019_remove_bankreconciliation_unique_reconciliation_per_account_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='report_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
