# Generated by Django 5.1.1 on 2024-12-30 11:17

import autoslug.fields
import creditnoteio.django_rest.helpers.slug_helpers
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencyio', '0002_agency_start_of_period'),
        ('companyio', '0004_alter_companyshift_created_by'),
        ('customerio', '0006_alter_customer_currency'),
        ('employeeio', '0006_employeesalary_company_alter_employeesalary_employee_and_more'),
        ('productio', '0006_product_expired_date'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=creditnoteio.django_rest.helpers.slug_helpers.get_credit_note_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('email', models.TextField(help_text='Signature email with a comma')),
                ('kind', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSE', 'Close'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSE', 'Close'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('tax_kind', models.CharField(choices=[('INCLUSIVE', 'Inclusive of Tax'), ('EXCLUSIVE', 'Exclusive of Tax'), ('NO_TAX', 'No Tax')], default='NO_TAX', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=creditnoteio.django_rest.helpers.slug_helpers.get_credit_note_item_slug, unique=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productio.product')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyio.agencytax')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
