# Generated by Django 5.1.1 on 2024-12-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0001_initial'),
        ('supplierio', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier'),
        ),
    ]
