# Generated by Django 5.1.1 on 2025-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0002_creditnote_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase')], max_length=50),
        ),
    ]
