# Generated by Django 5.1.1 on 2025-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0003_alter_creditnote_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
