# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0004_creditnoteitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteitem',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
