# Generated by Django 5.1.1 on 2025-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0005_alter_creditnoteitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
