# Generated by Django 5.1.1 on 2025-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0006_alter_creditnote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='item_credit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
