# Generated by Django 5.1.1 on 2025-02-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_chartofaccount_used_amount'),
        ('creditnoteio', '0007_creditnoteitem_item_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
    ]
