# Generated by Django 5.1.1 on 2025-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0008_creditnoteitem_charter_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
