# Generated by Django 5.1.1 on 2025-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0009_creditnote_total_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='email',
            field=models.JSONField(default={'bcc_emails': '', 'cc_emails': '', 'customer_email': ''}),
        ),
    ]
