# Generated by Django 5.1.1 on 2025-06-23 08:57

import common.django_rest.helpers.json_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0010_alter_creditnote_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
    ]
