# Generated by Django 5.1.1 on 2026-04-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnoteio', '0011_alter_creditnote_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='credit_note_sales_tax',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
