# Generated by Django 5.1.15 on 2026-08-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0010_agency_state'),
        ('creditnoteio', '0012_creditnote_credit_note_sales_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencyio.agencytax'),
        ),
    ]
