# Generated by Django 5.1.1 on 2025-01-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='billing_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', ' Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=50),
        ),
    ]
