# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0002_alter_subscriptionprice_billing_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
