# Generated by Django 5.1.1 on 2025-04-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0003_alter_subscriptionprice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
