# Generated by Django 5.1.1 on 2025-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0004_alter_companysubscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_1099_preparation_filing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_30_minute_consultation_per_quarter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_Virtual_CFO_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_annual_tax_filing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_audit_support_and_representation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_budgeting_and_cash_flow_forecasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_dedicated_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_financial_modeling_and_custom_dashboards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_investo_ready_financial_statements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_monthly_bookkeeping_and_reconciliations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_monthly_or_biweekly_payroll_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_multi_entity_or_multi_state_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_quarterly_tax_planning_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_sales_tax_filing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_unlimited_email_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_year_end_planning_for_tax_minimization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='kind',
            field=models.CharField(choices=[('COMPANY_SUBSCRIPTION', 'Company Subscription'), ('ACCOUNTANT_SUBSCRIPTION', 'Accountant Subscription')], default='COMPANY_SUBSCRIPTION', max_length=50),
        ),
    ]
