# Generated by Django 5.1.1 on 2025-06-16 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0005_subscription_is_1099_preparation_filing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
