# Generated by Django 5.1.1 on 2025-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0006_alter_companysubscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscription',
            name='kind',
            field=models.CharField(choices=[('COMPANY_SUBSCRIPTION', 'Company Subscription'), ('ACCOUNTANT_SUBSCRIPTION', 'Accountant Subscription')], default='COMPANY_SUBSCRIPTION', max_length=50),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='renew_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
