# Generated by Django 5.1.1 on 2025-08-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
        ('subscriptionio', '0007_companysubscription_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee'),
        ),
    ]
