# Generated by Django 5.1.1 on 2026-06-09 08:53

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionio', '0009_companysubscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'code'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('GRACE', 'Grace'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50),
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_versions', to='subscriptionio.subscription')),
            ],
            options={
                'ordering': ('-version_no',),
                'unique_together': {('subscription', 'version_no')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='plan_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_subscriptions', to='subscriptionio.planversion'),
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('legacy_field', models.CharField(blank=True, help_text='Maps to boolean field on Subscription model, e.g. is_sales', max_length=80, null=True, unique=True)),
                ('permission_codenames', models.JSONField(blank=True, default=list)),
                ('api_scope', models.CharField(blank=True, max_length=120, null=True)),
                ('menu_key', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptionio.subscriptionmodule')),
            ],
            options={
                'ordering': ('module__display_order', 'code'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('USER', 'User'), ('BRANCH', 'Branch'), ('STORAGE', 'Storage'), ('PAYROLL_RUN', 'Payroll Run'), ('AI_CREDIT', 'AI Credit')], max_length=50)),
                ('included_quantity', models.PositiveIntegerField(default=0)),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('overage_unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('enforcement_mode', models.CharField(choices=[('HARD_BLOCK', 'Hard Block'), ('SOFT_WARNING', 'Soft Warning'), ('AUTO_OVERAGE', 'Auto Overage'), ('MANUAL_APPROVAL', 'Manual Approval'), ('GRACE_OVERAGE', 'Grace Overage')], default='SOFT_WARNING', max_length=30)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='subscriptionio.planversion')),
            ],
            options={
                'unique_together': {('plan_version', 'metric_code')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('NONE', 'None'), ('READ', 'Read'), ('WRITE', 'Write'), ('FULL', 'Full')], default='FULL', max_length=20)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptionio.planversion')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptionio.subscriptionfeature')),
            ],
            options={
                'unique_together': {('plan_version', 'feature')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
