# Generated by Django 5.1.1 on 2024-12-21 09:31

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import purchaseio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chartofaccount_currency'),
        ('employeeio', '0006_employeesalary_company_alter_employeesalary_employee_and_more'),
        ('paymentio', '0001_initial'),
        ('purchaseio', '0001_initial'),
        ('supplierio', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_expense_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.chartofaccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_expense_slug, unique=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseio.expense')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
