# Generated by Django 5.1.1 on 2024-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0002_expense_expenseconnector'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50),
        ),
    ]
