# Generated by Django 5.1.1 on 2024-12-21 16:04

import autoslug.fields
import purchaseio.django_rest.helpers.slug_helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0003_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseconnector',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_expense_connector_slug, unique=True),
        ),
    ]
