# Generated by Django 5.1.1 on 2024-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0004_alter_expenseconnector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
