# Generated by Django 5.1.1 on 2024-12-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chartofaccount_account_type_and_more'),
        ('paymentio', '0001_initial'),
        ('purchaseio', '0005_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod'),
        ),
    ]
