# Generated by Django 5.1.1 on 2025-01-15 09:44

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import purchaseio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
        ('companyio', '0004_alter_companyshift_created_by'),
        ('creditnoteio', '0003_alter_creditnote_kind'),
        ('employeeio', '0001_initial'),
        ('paymentio', '0004_paymentinformation_subscription_price_and_more'),
        ('purchaseio', '0006_alter_expense_payment_account_and_more'),
        ('supplierio', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_purchase_payment_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('email', models.TextField(help_text='Signature email with a comma')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PARTIALLY', 'Partially'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchasePaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_purchase_payment_item_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REMOVED', 'Removed'), ('PARTIALLY', 'Partially'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase')),
                ('purchase_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
