# Generated by Django 5.1.1 on 2025-01-19 19:17

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import purchaseio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0005_companysetting'),
        ('purchaseio', '0007_purchaseitem_note_purchasepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_purchase_setting_slug, unique=True)),
                ('is_purchase_item', models.BooleanField(default=False)),
                ('is_tag', models.BooleanField(default=False)),
                ('is_track_expense_and_items_by_customer', models.BooleanField(default=False)),
                ('is_expense_and_item_billable', models.BooleanField(default=False)),
                ('is_purchase_order', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
