# Generated by Django 5.1.1 on 2025-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0008_purchasesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='term',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
