# Generated by Django 5.1.1 on 2025-02-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_chartofaccount_detail_type'),
        ('purchaseio', '0009_remove_purchase_term_purchaseitem_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
    ]
