# Generated by Django 5.1.1 on 2025-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0010_purchase_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepaymentitem',
            name='model_kind',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('CREDIT_NOTE', 'Credit Note')], default='PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasepaymentitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasepaymentitem',
            name='used_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
