# Generated by Django 5.1.1 on 2025-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0011_purchasepaymentitem_model_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
