# Generated by Django 5.1.1 on 2025-02-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_chartofaccount_detail_type'),
        ('purchaseio', '0012_expense_expense_id_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cheque_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_cheque',
            field=models.BooleanField(default=False),
        ),
    ]
