# Generated by Django 5.1.1 on 2025-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0013_purchase_charter_account_purchase_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
