# Generated by Django 5.1.1 on 2025-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0014_alter_purchase_cheque_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
