# Generated by Django 5.1.1 on 2025-02-22 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0015_alter_purchase_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, unique=True),
        ),
    ]
