# Generated by Django 5.1.1 on 2025-02-25 20:47

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import purchaseio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_chartofaccount_account_type_and_more'),
        ('companyio', '0008_company_kind_historicalcompany_kind'),
        ('employeeio', '0009_alter_employeesalary_basic_alter_employeesalary_cash_and_more'),
        ('purchaseio', '0017_alter_expense_deposit_alter_expense_discount_and_more'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_pay_bill_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('email', models.TextField(help_text='Signature email with a comma')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PUBLISHED', 'Published'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=50)),
                ('tax_kind', models.CharField(choices=[('INCLUSIVE', 'Inclusive of Tax'), ('EXCLUSIVE', 'Exclusive of Tax'), ('NO_TAX', 'No Tax')], default='NO_TAX', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=purchaseio.django_rest.helpers.slug_helpers.get_pay_bill_item_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PUBLISHED', 'Published'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid')], default='DRAFT', max_length=50)),
                ('applied_credit', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('pay_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseio.paybill')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
