# Generated by Django 5.1.1 on 2025-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0018_paybill_paybillitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybill',
            name='email',
            field=models.TextField(blank=True, help_text='Signature email with a comma', null=True),
        ),
    ]
