# Generated by Django 5.1.1 on 2025-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0019_alter_paybill_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_via_expense',
            field=models.BooleanField(default=False),
        ),
    ]
