# Generated by Django 5.1.1 on 2025-05-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0020_purchase_is_via_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='opening_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
