# Generated by Django 5.1.1 on 2025-06-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0005_alter_paymentinformation_invoice_link'),
        ('purchaseio', '0021_purchaseitem_opening_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod'),
        ),
    ]
