# Generated by Django 5.1.1 on 2025-06-23 08:57

import common.django_rest.helpers.json_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0022_purchase_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybill',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
    ]
