# Generated by Django 5.1.1 on 2026-07-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseio', '0023_alter_paybill_email_alter_purchase_email_and_more'),
        ('recurringio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='recurringio.recurringtemplate'),
        ),
    ]
