# Generated by Django 5.1.15 on 2026-08-27 11:55

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0026_enable_rls_transactions'),
        ('purchaseio', '0025_alter_purchaseitem_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBillApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('pay_bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='purchaseio.paybillitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_bill_applications', to='purchaseio.purchase')),
            ],
            options={
                'indexes': [models.Index(fields=['purchase'], name='purchaseio__purchas_12822b_idx'), models.Index(fields=['pay_bill_item'], name='purchaseio__pay_bil_5abdf2_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
