# Generated by Django 5.1.1 on 2025-07-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0003_holiday_holidaydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaydetails',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='holidaydetails',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='attendanceio.holiday'),
        ),
    ]
