# Generated by Django 5.1.1 on 2025-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0004_alter_holidaydetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='weekend',
            field=models.TextField(blank=True, help_text="Help text: List of weekend days, e.g., ['Saturday', 'Sunday']", null=True),
        ),
    ]
