# Generated by Django 5.1.1 on 2025-08-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0005_alter_holiday_weekend'),
        ('employeeio', '0044_remove_employee_sign_w4_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_set', to='employeeio.employee'),
        ),
    ]
