# Generated by Django 5.1.1 on 2025-08-05 12:27

import attendanceio.django_rest.helpers.slug_helpers
import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0007_attendanceprocess_attendanceprocessitem'),
        ('companyio', '0016_companydesignation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companyshift'),
        ),
        migrations.AddField(
            model_name='attendanceprocess',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50),
        ),
        migrations.AddField(
            model_name='attendanceprocessitem',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendanceio.holiday'),
        ),
        migrations.AlterField(
            model_name='attendanceprocessitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=attendanceio.django_rest.helpers.slug_helpers.get_attendance_process_item_slug, unique=True),
        ),
    ]
