# Generated by Django 5.1.1 on 2025-08-05 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0008_attendance_shift_attendanceprocess_status_and_more'),
        ('companyio', '0016_companydesignation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceprocess',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
        ),
    ]
