# Generated by Django 5.1.1 on 2025-08-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0010_attendanceprocess_leave'),
        ('leaveio', '0009_leavetype_maximum_allocation_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceprocess',
            name='leave',
        ),
        migrations.AddField(
            model_name='attendanceprocessitem',
            name='leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaveio.leaverequest'),
        ),
    ]
