# Generated by Django 5.1.1 on 2025-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0011_remove_attendanceprocess_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceprocess',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceprocess',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
