# Generated by Django 5.1.1 on 2025-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0012_attendanceprocess_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('LATE_ARRIVAL', 'Late Arraival'), ('EARLY_DEPARTURE', 'Early Departure'), ('REMOVED', 'Removed'), ('SPECIAL', 'Special'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday')], default='DRAFT', max_length=20),
        ),
    ]
