# Generated by Django 5.1.1 on 2025-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0013_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimetracking',
            name='worked_hour_count',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='HistoricalDailyTimeTracking',
        ),
    ]
