# Generated by Django 5.1.1 on 2025-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0014_dailytimetracking_worked_hour_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytimetracking',
            name='worked_hour_count',
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_hour_count',
            field=models.FloatField(default=0),
        ),
    ]
