# Generated by Django 5.1.1 on 2025-10-31 06:11

import attendanceio.django_rest.helpers.slug_helpers
import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0015_remove_dailytimetracking_worked_hour_count_and_more'),
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchDataDailyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=attendanceio.django_rest.helpers.slug_helpers.get_punch_data_daily_time_slug, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('LATE_ARRIVAL', 'Late Arraival'), ('EARLY_DEPARTURE', 'Early Departure'), ('OVERTIME', 'Overtime'), ('HOLIDAY', 'Holiday'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('worked_hour', models.FloatField(blank=True, default=0, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_punch_data', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.companyshift')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'employee', 'company'), name='unique_punch_data_daily_time_for_employee_per_day')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
