# Generated by Django 5.1.1 on 2026-06-23 08:25

from django.db import migrations, models


def dedupe_attendance(apps, schema_editor):
    """Collapse any pre-existing duplicate (employee, date, company) rows.

    The old single-create path did a plain ``create()`` with no uniqueness, so
    duplicates may exist. Keep the most recently updated row per key and delete
    the rest so the unique constraint below can be added safely.
    """
    Attendance = apps.get_model("attendanceio", "Attendance")
    seen = set()
    duplicate_ids = []
    queryset = Attendance.objects.order_by(
        "employee_id", "date", "company_id", "-updated_at", "-id"
    ).values_list("id", "employee_id", "date", "company_id")
    for row_id, employee_id, date, company_id in queryset.iterator():
        key = (employee_id, date, company_id)
        if key in seen:
            duplicate_ids.append(row_id)
        else:
            seen.add(key)
    if duplicate_ids:
        Attendance.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0016_punchdatadailytime'),
        ('companyio', '0023_enable_rls_core_tables'),
        ('employeeio', '0067_backfill_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('LATE_ARRIVAL', 'Late Arraival'), ('EARLY_DEPARTURE', 'Early Departure'), ('HALF_DAY', 'Half Day'), ('REMOVED', 'Removed'), ('SPECIAL', 'Special'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(dedupe_attendance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'company'), name='unique_attendance_record_per_employee_per_day'),
        ),
    ]
