# Generated by Django 5.1.1 on 2024-12-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressio', '0001_initial'),
        ('purchaseio', '0001_initial'),
        ('supplierio', '0004_alter_supplier_currency'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchase'),
        ),
        migrations.AddField(
            model_name='addressconnector',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplierio.supplier'),
        ),
        migrations.AddField(
            model_name='addressconnector',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wirehouseio.warehouse'),
        ),
    ]
