# Generated by Django 5.1.1 on 2024-12-11 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shipping_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
