# Generated by Django 5.1.1 on 2024-12-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0003_address_shipping_date'),
        ('salesio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.sale'),
        ),
        migrations.AlterField(
            model_name='addressconnector',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('WAREHOUSE', 'Warehouse'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale')], max_length=50),
        ),
    ]
