# Generated by Django 5.1.1 on 2024-12-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0004_addressconnector_sale_alter_addressconnector_kind'),
        ('creditnoteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='credit_noteio_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnoteitem'),
        ),
        migrations.AlterField(
            model_name='addressconnector',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('WAREHOUSE', 'Warehouse'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CREDIT_NOTE_ITEM', 'Credit Note Item')], max_length=50),
        ),
    ]
