# Generated by Django 5.1.1 on 2025-01-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0006_remove_addressconnector_credit_noteio_item_and_more'),
        ('salesio', '0006_salepaymentreceive_salepaymentreceiveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='sale_payment_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salepaymentreceive'),
        ),
        migrations.AlterField(
            model_name='addressconnector',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('WAREHOUSE', 'Warehouse'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive')], max_length=50),
        ),
    ]
