# Generated by Django 5.1.1 on 2025-01-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0007_addressconnector_sale_payment_receive_and_more'),
        ('purchaseio', '0007_purchaseitem_note_purchasepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='purchase_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseio.purchasepayment'),
        ),
        migrations.AlterField(
            model_name='addressconnector',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('WAREHOUSE', 'Warehouse'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PURCHASE_PAYMENT', 'Purchase Payment')], max_length=50),
        ),
    ]
