# Generated by Django 5.1.1 on 2025-07-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0009_addressconnector_company_alter_addressconnector_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressconnector',
            name='kind',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('WAREHOUSE', 'Warehouse'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('CREDIT_NOTE_ITEM', 'Credit Note Item'), ('SALE_PAYMENT_RECEIVE', 'Sale Payment Receive'), ('PURCHASE_PAYMENT', 'Purchase Payment'), ('COMPANY', 'Company'), ('EMPLOYEE', 'Employee')], max_length=50),
        ),
    ]
