# Generated by Django 5.1.1 on 2025-07-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0010_alter_addressconnector_kind'),
        ('employeeio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconnector',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee'),
        ),
    ]
