# Generated by Django 5.1.1 on 2025-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressio', '0011_addressconnector_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_work_address',
            field=models.BooleanField(default=False),
        ),
    ]
