from django.urls import path

from datamigrationio.django_rest.views.migrations import (
    PrivateDataMigrationListCreate,
    PrivateDataMigrationDetail,
    PrivateDataMigrationDataTypes,
    PrivateDataMigrationUpload,
    PrivateDataMigrationPreview,
    PrivateDataMigrationAutoMap,
    PrivateDataMigrationMapping,
    PrivateDataMigrationValidate,
    PrivateDataMigrationValidationIssues,
    PrivateDataMigrationRowFix,
    PrivateDataMigrationReviewImpact,
    PrivateDataMigrationDryRun,
    PrivateDataMigrationConfirm,
    PrivateDataMigrationReconciliation,
    PrivateDataMigrationRollback,
    PrivateDataMigrationResults,
    PrivateDataMigrationErrorReport,
    PrivateDataMigrationAuditLogs,
    PrivateDataMigrationTemplateDownload,
)

urlpatterns = [
    path(
        r"",
        PrivateDataMigrationListCreate.as_view(),
        name="datamigrationio.migration-list-create",
    ),
    path(
        r"/data-types",
        PrivateDataMigrationDataTypes.as_view(),
        name="datamigrationio.migration-data-types",
    ),
    # Generic template download — must come before the uuid pattern
    path(
        r"/templates/<str:data_type>/download",
        PrivateDataMigrationTemplateDownload.as_view(),
        name="datamigrationio.migration-template-download-generic",
    ),
    # Keep backward-compatible invoice-specific URL
    path(
        r"/templates/invoices/download",
        PrivateDataMigrationTemplateDownload.as_view(),
        name="datamigrationio.migration-template-download",
    ),
    path(
        r"/<uuid:uid>",
        PrivateDataMigrationDetail.as_view(),
        name="datamigrationio.migration-detail",
    ),
    path(
        r"/<uuid:uid>/upload",
        PrivateDataMigrationUpload.as_view(),
        name="datamigrationio.migration-upload",
    ),
    path(
        r"/<uuid:uid>/preview",
        PrivateDataMigrationPreview.as_view(),
        name="datamigrationio.migration-preview",
    ),
    path(
        r"/<uuid:uid>/auto-map",
        PrivateDataMigrationAutoMap.as_view(),
        name="datamigrationio.migration-auto-map",
    ),
    path(
        r"/<uuid:uid>/mapping",
        PrivateDataMigrationMapping.as_view(),
        name="datamigrationio.migration-mapping",
    ),
    path(
        r"/<uuid:uid>/validate",
        PrivateDataMigrationValidate.as_view(),
        name="datamigrationio.migration-validate",
    ),
    path(
        r"/<uuid:uid>/validation-issues",
        PrivateDataMigrationValidationIssues.as_view(),
        name="datamigrationio.migration-validation-issues",
    ),
    path(
        r"/<uuid:uid>/rows/<uuid:row_uid>/fix",
        PrivateDataMigrationRowFix.as_view(),
        name="datamigrationio.migration-row-fix",
    ),
    path(
        r"/<uuid:uid>/review-impact",
        PrivateDataMigrationReviewImpact.as_view(),
        name="datamigrationio.migration-review-impact",
    ),
    path(
        r"/<uuid:uid>/dry-run",
        PrivateDataMigrationDryRun.as_view(),
        name="datamigrationio.migration-dry-run",
    ),
    path(
        r"/<uuid:uid>/confirm",
        PrivateDataMigrationConfirm.as_view(),
        name="datamigrationio.migration-confirm",
    ),
    path(
        r"/<uuid:uid>/reconciliation",
        PrivateDataMigrationReconciliation.as_view(),
        name="datamigrationio.migration-reconciliation",
    ),
    path(
        r"/<uuid:uid>/rollback",
        PrivateDataMigrationRollback.as_view(),
        name="datamigrationio.migration-rollback",
    ),
    path(
        r"/<uuid:uid>/results",
        PrivateDataMigrationResults.as_view(),
        name="datamigrationio.migration-results",
    ),
    path(
        r"/<uuid:uid>/error-report",
        PrivateDataMigrationErrorReport.as_view(),
        name="datamigrationio.migration-error-report",
    ),
    path(
        r"/<uuid:uid>/audit-logs",
        PrivateDataMigrationAuditLogs.as_view(),
        name="datamigrationio.migration-audit-logs",
    ),
]
