# Generated by Django 5.1.1 on 2024-11-22 09:52

import attachmentio.django_rest.helpers.media_path
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachmentio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=attachmentio.django_rest.helpers.media_path.get_atachment_media_path_prefix, verbose_name='Image'),
        ),
    ]
