# Generated by Django 5.1.1 on 2024-11-04 11:11

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_salary_adjustment_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('kind', models.CharField(choices=[('ADDITION', 'Addition'), ('DEDUCTION', 'Deduction')], max_length=50)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
            ],
            options={
                'verbose_name': 'Salary Adjustment',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
