# Generated by Django 5.1.1 on 2025-07-17 10:58

import autoslug.fields
import dirtyfields.dirtyfields
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0002_alter_salaryadjustment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionAndContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_dedcon_slug, unique=True)),
                ('deduction_type', models.CharField(max_length=255)),
                ('sub_type', models.CharField(max_length=255)),
                ('tax_type', models.CharField(blank=True, choices=[('PRETAX', 'Pretax'), ('POST_TAX', 'Post-Tax')], max_length=10, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
