# Generated by Django 5.1.1 on 2025-07-18 13:52

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('payrollio', '0006_payschedules_delete_payschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_pay_schedule_slug, unique=True)),
                ('pay_frequency', models.CharField(choices=[('EVERY_WEEK', 'Every Week'), ('OTHER_WEEK', 'Other Week'), ('TWICE_A_MONTH', 'Twice A Month'), ('EVERY_MONTH', 'Every Month')], max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=10)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('first_payday', models.CharField(blank=True, max_length=10, null=True)),
                ('first_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('first_month', models.CharField(blank=True, choices=[('SAME', 'Same'), ('PREVIOUS', 'Previous'), ('NEXT', 'Next')], default='SAME', max_length=10, null=True)),
                ('first_day', models.CharField(blank=True, max_length=10, null=True)),
                ('second_payday', models.CharField(blank=True, max_length=10, null=True)),
                ('second_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('second_month', models.CharField(blank=True, choices=[('SAME', 'Same'), ('PREVIOUS', 'Previous'), ('NEXT', 'Next')], default='SAME', max_length=10, null=True)),
                ('second_day', models.CharField(blank=True, max_length=10, null=True)),
                ('next_pay_date', models.DateField(blank=True, null=True)),
                ('end_of_next_pay_period', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'verbose_name_plural': 'Pay Schedule',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='PaySchedules',
        ),
    ]
