# Generated by Django 5.1.1 on 2025-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0007_payschedule_delete_payschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payschedule',
            name='first_end_day',
            field=models.CharField(blank=True, choices=[('END_DAY', 'End Day'), ('BEFORE_END_DAY', 'Before end day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payschedule',
            name='second_end_day',
            field=models.CharField(blank=True, choices=[('END_DAY', 'End Day'), ('BEFORE_END_DAY', 'Before end day')], max_length=20, null=True),
        ),
    ]
