# Generated by Django 5.1.1 on 2025-07-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0008_alter_payschedule_first_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payschedule',
            name='first_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payschedule',
            name='first_payday',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payschedule',
            name='second_day',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payschedule',
            name='second_payday',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
