# Generated by Django 5.1.1 on 2025-07-31 02:30

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('employeeio', '0041_employee_on_boarding_kind'),
        ('payrollio', '0009_alter_payschedule_first_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSalaryProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_salary_process_slug, unique=True)),
                ('pay_date', models.DateField()),
                ('pay_period', models.CharField(max_length=25)),
                ('pay_method', models.CharField(choices=[('PAPER_CHECK', 'Paper Check'), ('DIRECT_DEPOSIT', 'Direct Deposit')], max_length=15)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('accrue_time_off', models.BooleanField(default=False)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_taxes_dedcutions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer_taxes_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_salary', to='employeeio.employee')),
                ('funding_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.chartofaccount')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll_payment_account', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_type', models.CharField(max_length=255)),
                ('payroll_category', models.CharField(choices=[('PAY', 'Pay'), ('EMPLOYEE_TAXES', 'Employee Taxes'), ('EMPLOYEE_DEDUCTIONS', 'Employee Deductions'), ('EMPLOYER_TAXES', 'Employer Taxes'), ('COMPANY_PAID_CONTRIBUTIONS', 'Company Paid Contributions')], max_length=155)),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ytd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollio.payrollsalaryprocess')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
