# Generated by Django 5.1.1 on 2025-07-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('payrollio', '0010_payrollsalaryprocess_payrollcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsalaryprocess',
            name='funding_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll_funding_account', to='accounts.chartofaccount'),
        ),
    ]
