# Generated by Django 5.1.1 on 2025-08-01 10:51

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0042_rename_is_joind_employee_is_joined'),
        ('payrollio', '0011_alter_payrollsalaryprocess_funding_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollGeneralTaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('OTHER', 'Other'), ('NON_PROFIT_501C3_CORP', 'Non Profit 501c3 Corp'), ('SOLE_PROPRIETOR', 'Sole Proprietor')], default='OTHER', max_length=100, null=True)),
                ('ein_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='EIN Number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
