# Generated by Django 5.1.1 on 2025-08-02 07:26

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0001_initial'),
        ('payrollio', '0012_payrollgeneraltaxsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollgeneraltaxsetting',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_general_tax_setting_slug, unique=True),
        ),
        migrations.CreateModel(
            name='PayrollFederalTaxInfoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_federal_tax_info_setting_slug, unique=True)),
                ('ein_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('tax_form', models.CharField(blank=True, choices=[('FORM_941_EACH_QUARTER', 'Form 941 each quarter (most common)'), ('FORM_943_EACH_YEAR', 'Form 943 each year (agricultural)'), ('FORM_944_EACH_YEAR', 'Form 944 each year')], max_length=255, null=True)),
                ('payment_frequency', models.CharField(choices=[('SEMI_WEEKLY', 'Semi-Weekly (Recommended)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
