# Generated by Django 5.1.1 on 2025-08-05 11:42

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0047_alter_employee_citizenship_kind'),
        ('payrollio', '0013_alter_payrollgeneraltaxsetting_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStateTaxInfoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_state_tax_info_setting_slug, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('ein_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ui_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='UI Registration Number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollReemploymentOrWorkforceServiceFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reemployment_or_workforce_fund_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Reemployment Service Fund Rate')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_state_tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reemployment_service_funds', to='payrollio.payrollstatetaxinfosetting')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollMCTMTZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('ZONE_1', 'Zone 1'), ('ZONE_2', 'Zone 2')], max_length=10, verbose_name='Metropolitan Commuter Transportation Mobility Tax Zone')),
                ('mctmt_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Metropolitan Commuter Transportation Mobility Tax Rate')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_state_tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mctmt_zones', to='payrollio.payrollstatetaxinfosetting')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollStateTaxPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency', models.CharField(blank=True, choices=[('SEMI_WEEKLY', 'Semi-Weekly (Recommended)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('3_DAYS_AFTER_PAYROLL', '3 Days after Payroll'), ('5_DAYS_AFTER_PAYROLL', '5 Days after Payroll')], max_length=20, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_state_tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='payrollio.payrollstatetaxinfosetting')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollUnemploymentInsuranceTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='UI Rate')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_state_tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unemployment_insurance', to='payrollio.payrollstatetaxinfosetting')),
            ],
        ),
    ]
