# Generated by Django 5.1.1 on 2025-08-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0013_alter_payrollgeneraltaxsetting_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollsalaryprocess',
            old_name='employee_taxes_dedcutions',
            new_name='employee_taxes_deductions',
        ),
    ]
