# Generated by Django 5.1.1 on 2025-08-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0014_rename_employee_taxes_dedcutions_payrollsalaryprocess_employee_taxes_deductions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayrollComponent',
            new_name='PayrollSalaryComponent',
        ),
    ]
