# Generated by Django 5.1.1 on 2025-08-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0015_rename_payrollcomponent_payrollsalarycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsalaryprocess',
            name='is_salary_done',
            field=models.BooleanField(default=False),
        ),
    ]
