# Generated by Django 5.1.1 on 2025-08-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0014_payrollstatetaxinfosetting_and_more'),
        ('payrollio', '0016_payrollsalaryprocess_is_salary_done'),
    ]

    operations = [
    ]
