# Generated by Django 5.1.1 on 2025-08-06 09:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0017_merge_20250806_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollmctmtzone',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='payrollreemploymentorworkforceservicefund',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='payrollstatetaxpaymentschedule',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='payrollunemploymentinsurancetaxinfo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='payrollmctmtzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 9, 27, 19, 557657, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollmctmtzone',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollmctmtzone',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payrollmctmtzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollreemploymentorworkforceservicefund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 9, 27, 40, 909339, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollreemploymentorworkforceservicefund',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollreemploymentorworkforceservicefund',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payrollreemploymentorworkforceservicefund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollstatetaxpaymentschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 9, 28, 7, 678894, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollstatetaxpaymentschedule',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollstatetaxpaymentschedule',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payrollstatetaxpaymentschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollunemploymentinsurancetaxinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 9, 28, 28, 843497, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollunemploymentinsurancetaxinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollunemploymentinsurancetaxinfo',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payrollunemploymentinsurancetaxinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
