# Generated by Django 5.1.1 on 2025-08-08 16:33

import autoslug.fields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0018_alter_payrollmctmtzone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsalarycomponent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_salary_component_slug, unique=True),
        ),
        migrations.AlterField(
            model_name='payrollsalarycomponent',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='payrollio.payrollsalaryprocess'),
        ),
    ]
