# Generated by Django 5.1.1 on 2025-08-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
        ('payrollio', '0020_payrollworklocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworklocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_location_created_by', to='employeeio.employee'),
        ),
    ]
