# Generated by Django 5.1.1 on 2025-08-12 08:58

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0001_initial'),
        ('payrollio', '0021_payrollworklocation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollfederaltaxinfosetting',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='payrollfederaltaxinfosetting',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='payrollfederaltaxinfosetting',
            name='tax_form',
        ),
        migrations.CreateModel(
            name='PayrollAccountingPreferencesSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_accounting_preferences_slug, unique=True)),
                ('wages_expense_type', models.CharField(choices=[('SINGLE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)")], default='SINGLE_ACCOUNT', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('global_wage_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_wage_account', to='accounts.chartofaccount')),
                ('paycheck_payroll_tax_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_expense_account', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollFederalTaxInfoSettingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_form', models.CharField(blank=True, choices=[('FORM_941_EACH_QUARTER', 'Form 941 each quarter (most common)'), ('FORM_943_EACH_YEAR', 'Form 943 each year (agricultural)'), ('FORM_944_EACH_YEAR', 'Form 944 each year')], max_length=255, null=True)),
                ('payment_frequency', models.CharField(choices=[('SEMI_WEEKLY', 'Semi-Weekly (Recommended)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_federal_tax_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payrollio.payrollfederaltaxinfosetting')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WageExpenseAccountComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wage_expense_accounts', to='employeeio.employee')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_expense_account', to='accounts.chartofaccount')),
                ('payroll_accounting_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_expense_accounts', to='payrollio.payrollaccountingpreferencessetting')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
