# Generated by Django 5.1.1 on 2025-08-14 06:20

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('employeeio', '0001_initial'),
        ('payrollio', '0022_remove_payrollfederaltaxinfosetting_effective_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollaccountingpreferencessetting',
            name='wages_expense_type',
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='company_contribution_expense_type',
            field=models.CharField(choices=[('SINGLE_WAGE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_WAGE_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)"), ('COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', 'Company contributions of the same type are posted to one expense account'), ('COMPANY_CONTRIBUTION_PER_EMPLOYEE', 'Company contributions for each employee are posted to their own expense account'), ('COMPANY_CONTRIBUTION_DIFFERENT_TYPE', 'Company contributions of different types are posted to different accounts (ex: salary, contractor, and so on)'), ('SINGLE_EMPLOYER_TAX_ACCOUNT', 'All employer taxes are posted to one expense account.'), ('PER_EMPLOYER_TAX_EXPENSE', 'Employer taxes are posted to different expense accounts for different employees.'), ('DIFFERENT_TAX_DIFFERENT_GROUP', 'Employer taxes are posted to different expense accounts for different groups of taxes.'), ('DIFFERENT_EXPENSE_DIFFERENT_TAX', 'Employer taxes are posted to different expense accounts for different tax items.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', 'Tax Liabilities are posted to different accounts for different Tax Groups.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_ITEMS', 'Tax Liabilities are posted to different accounts for different Tax Items.')], default='COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', max_length=150),
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='employer_tax_expense_type',
            field=models.CharField(choices=[('SINGLE_WAGE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_WAGE_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)"), ('COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', 'Company contributions of the same type are posted to one expense account'), ('COMPANY_CONTRIBUTION_PER_EMPLOYEE', 'Company contributions for each employee are posted to their own expense account'), ('COMPANY_CONTRIBUTION_DIFFERENT_TYPE', 'Company contributions of different types are posted to different accounts (ex: salary, contractor, and so on)'), ('SINGLE_EMPLOYER_TAX_ACCOUNT', 'All employer taxes are posted to one expense account.'), ('PER_EMPLOYER_TAX_EXPENSE', 'Employer taxes are posted to different expense accounts for different employees.'), ('DIFFERENT_TAX_DIFFERENT_GROUP', 'Employer taxes are posted to different expense accounts for different groups of taxes.'), ('DIFFERENT_EXPENSE_DIFFERENT_TAX', 'Employer taxes are posted to different expense accounts for different tax items.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', 'Tax Liabilities are posted to different accounts for different Tax Groups.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_ITEMS', 'Tax Liabilities are posted to different accounts for different Tax Items.')], default='SINGLE_EMPLOYER_TAX_ACCOUNT', max_length=150),
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='global_contribution_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_contribution_expense_account', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='global_employer_tax_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_employer_tax_expenses', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='tax_liability_expense_type',
            field=models.CharField(choices=[('SINGLE_WAGE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_WAGE_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)"), ('COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', 'Company contributions of the same type are posted to one expense account'), ('COMPANY_CONTRIBUTION_PER_EMPLOYEE', 'Company contributions for each employee are posted to their own expense account'), ('COMPANY_CONTRIBUTION_DIFFERENT_TYPE', 'Company contributions of different types are posted to different accounts (ex: salary, contractor, and so on)'), ('SINGLE_EMPLOYER_TAX_ACCOUNT', 'All employer taxes are posted to one expense account.'), ('PER_EMPLOYER_TAX_EXPENSE', 'Employer taxes are posted to different expense accounts for different employees.'), ('DIFFERENT_TAX_DIFFERENT_GROUP', 'Employer taxes are posted to different expense accounts for different groups of taxes.'), ('DIFFERENT_EXPENSE_DIFFERENT_TAX', 'Employer taxes are posted to different expense accounts for different tax items.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', 'Tax Liabilities are posted to different accounts for different Tax Groups.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_ITEMS', 'Tax Liabilities are posted to different accounts for different Tax Items.')], default='DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', max_length=150),
        ),
        migrations.AddField(
            model_name='payrollaccountingpreferencessetting',
            name='wage_expense_type',
            field=models.CharField(choices=[('SINGLE_WAGE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_WAGE_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)"), ('COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', 'Company contributions of the same type are posted to one expense account'), ('COMPANY_CONTRIBUTION_PER_EMPLOYEE', 'Company contributions for each employee are posted to their own expense account'), ('COMPANY_CONTRIBUTION_DIFFERENT_TYPE', 'Company contributions of different types are posted to different accounts (ex: salary, contractor, and so on)'), ('SINGLE_EMPLOYER_TAX_ACCOUNT', 'All employer taxes are posted to one expense account.'), ('PER_EMPLOYER_TAX_EXPENSE', 'Employer taxes are posted to different expense accounts for different employees.'), ('DIFFERENT_TAX_DIFFERENT_GROUP', 'Employer taxes are posted to different expense accounts for different groups of taxes.'), ('DIFFERENT_EXPENSE_DIFFERENT_TAX', 'Employer taxes are posted to different expense accounts for different tax items.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', 'Tax Liabilities are posted to different accounts for different Tax Groups.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_ITEMS', 'Tax Liabilities are posted to different accounts for different Tax Items.')], default='SINGLE_WAGE_ACCOUNT', max_length=150),
        ),
        migrations.CreateModel(
            name='PayrollAccountExpenseAccountComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_expense_employee', to='employeeio.employee')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_account', to='accounts.chartofaccount')),
                ('payroll_accounting_preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_accounts', to='payrollio.payrollaccountingpreferencessetting')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollFederalLoanInterestPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ui_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Federal Loan Interest Rate')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('payroll_state_tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federal_loan_interest_payment_schedules', to='payrollio.payrollstatetaxinfosetting')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='WageExpenseAccountComponent',
        ),
    ]
