# Generated by Django 5.1.1 on 2025-08-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0023_remove_payrollaccountingpreferencessetting_wages_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollaccountexpenseaccountcomponent',
            name='payroll_accounting_preferences_type',
            field=models.CharField(blank=True, choices=[('SINGLE_WAGE_ACCOUNT', "All my employee's wages are posted to one expense account"), ('PER_WAGE_EMPLOYEE', "Each employee's wages are posted to their own expense account"), ('PER_WAGE_TYPE', "Each employee's wages are posted to different types of accounts (ex: salary, contractor, and so on)"), ('COMPANY_CONTRIBUTION_SINGLE_ACCOUNT', 'Company contributions of the same type are posted to one expense account'), ('COMPANY_CONTRIBUTION_PER_EMPLOYEE', 'Company contributions for each employee are posted to their own expense account'), ('COMPANY_CONTRIBUTION_DIFFERENT_TYPE', 'Company contributions of different types are posted to different accounts (ex: salary, contractor, and so on)'), ('SINGLE_EMPLOYER_TAX_ACCOUNT', 'All employer taxes are posted to one expense account.'), ('PER_EMPLOYER_TAX_EXPENSE', 'Employer taxes are posted to different expense accounts for different employees.'), ('DIFFERENT_TAX_DIFFERENT_GROUP', 'Employer taxes are posted to different expense accounts for different groups of taxes.'), ('DIFFERENT_EXPENSE_DIFFERENT_TAX', 'Employer taxes are posted to different expense accounts for different tax items.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_GROUP', 'Tax Liabilities are posted to different accounts for different Tax Groups.'), ('DIFFERENT_LIABILITY_DIFFERENT_TAX_ITEMS', 'Tax Liabilities are posted to different accounts for different Tax Items.')], max_length=150, null=True),
        ),
    ]
