# Generated by Django 5.1.1 on 2025-08-19 09:02

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import payrollio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0049_employee_image'),
        ('payrollio', '0025_payrollaccountingpreferencessetting_other_liability_asset_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollGeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=payrollio.django_rest.helpers.slug_helpers.get_payroll_general_tax_setting_slug, unique=True)),
                ('payroll_working_days', models.CharField(blank=True, choices=[('CALENDAR_DAYS', 'Calendar Days'), ('WORKING_DAYS', 'Working Days')], max_length=150, null=True)),
                ('is_total_working_days', models.BooleanField(default=False)),
                ('max_working_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('daily_salary_half_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_round_total', models.BooleanField(blank=True, default=False, null=True)),
                ('is_show_leave_balance', models.BooleanField(blank=True, default=False, null=True)),
                ('is_encrypt_salary_slip', models.BooleanField(blank=True, default=False, null=True)),
                ('is_salary_slip', models.BooleanField(blank=True, default=False, null=True)),
                ('email_template', models.CharField(blank=True, default='Default Template', max_length=150, null=True)),
                ('is_process_payroll_by_employee', models.BooleanField(default=False, help_text='If checked, Payroll Payment will be booked against each employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
