# Generated by Django 5.1.1 on 2025-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0026_payrollgeneralsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollgeneralsettings',
            name='email_template',
            field=models.CharField(blank=True, choices=[('DEFAULT_TEMPLATE', 'Default Template'), ('CUSTOM_TEMPLATE', 'Custom Template')], max_length=150, null=True),
        ),
    ]
