# Generated by Django 5.1.1 on 2025-08-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0049_employee_image'),
        ('payrollio', '0027_alter_payrollgeneralsettings_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollaccountexpenseaccountcomponent',
            name='deduction_and_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_deduction_and_contribution', to='payrollio.deductionandcontributions'),
        ),
        migrations.AddField(
            model_name='payrollaccountexpenseaccountcomponent',
            name='employee_garnishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_employee_garnishment', to='employeeio.employeegarnishment'),
        ),
    ]
