# Generated by Django 5.1.1 on 2025-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0029_payrollcontactinfosetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsalaryprocess',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
