# Generated by Django 5.1.1 on 2025-10-15 05:41

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('payrollio', '0030_payrollsalaryprocess_schedule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCenterPayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_inside_balanzify', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_filed', models.BooleanField(default=False)),
                ('liability_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollio.payrollsalaryprocess')),
                ('tax_liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_liability_account', to='accounts.chartofaccount')),
                ('tax_record_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_record_account', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
