# Generated by Django 5.1.1 on 2025-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0031_taxcenterpaymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcenterpaymethod',
            name='liability_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
