# Generated by Django 5.1.1 on 2026-06-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0036_payrollfederaltaxinfosettingitems_unique_form_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollfederaltaxinfosettingitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payrollgeneraltaxsetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payrollworklocation',
            options={},
        ),
    ]
