# Generated by Django 5.1.1 on 2026-07-06 08:06

import dirtyfields.dirtyfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollio', '0037_alter_payrollfederaltaxinfosettingitems_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('jurisdiction', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('source_notes', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-year', 'jurisdiction'),
                'constraints': [models.UniqueConstraint(fields=('year', 'jurisdiction'), name='uniq_payroll_tax_config_year_jurisdiction')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
