# Generated by Django 5.1.1 on 2024-11-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='paymode',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('PAYPAL', 'PayPal'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('DIGITAL_WALLET', 'Digital Wallet')], default='CHEQUE', max_length=20, null=True),
        ),
    ]
