# Generated by Django 5.1.1 on 2026-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
