# Generated by Django 5.1.1 on 2026-09-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0002_employee_login_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarystructure',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supersedes', to='employeeio.employeesalarystructure'),
        ),
    ]
