# Generated by Django 5.1.1 on 2024-11-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0002_employeesalary_paymode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='paymode',
            new_name='kind',
        ),
    ]
