# Generated by Django 5.1.1 on 2024-11-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0003_rename_paymode_employeesalary_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50),
        ),
    ]
