# Generated by Django 5.1.1 on 2024-11-17 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0004_employeesalary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='join_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
