# Generated by Django 5.1.1 on 2024-11-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0001_initial'),
        ('employeeio', '0005_alter_employee_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='kind',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CASH', 'Cash'), ('PAYPAL', 'PayPal'), ('MOBILE_PAYMENT', 'Mobile Payment'), ('DIGITAL_WALLET', 'Digital Wallet'), ('FIXED', 'Fixed')], default='CHEQUE', max_length=20, null=True),
        ),
    ]
