# Generated by Django 5.1.1 on 2025-01-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0004_alter_companyshift_created_by'),
        ('employeeio', '0006_employeesalary_company_alter_employeesalary_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companydepartment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companydesignation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companysection'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyio.companyshift'),
        ),
    ]
