# Generated by Django 5.1.1 on 2025-02-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0007_alter_employee_department_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
