# Generated by Django 5.1.1 on 2025-07-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0009_alter_employeesalary_basic_alter_employeesalary_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nid_card_no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='nid_card_no',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='section',
        ),
    ]
