# Generated by Django 5.1.1 on 2025-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0011_rename_join_date_employee_confirmation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='introducer_mobile_number',
            new_name='company_phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='introducer_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='introducer_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
