# Generated by Django 5.1.1 on 2025-07-19 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0012_rename_introducer_mobile_number_employee_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='offer_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
