# Generated by Django 5.1.1 on 2025-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0013_employee_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
