# Generated by Django 5.1.1 on 2025-07-19 16:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0015_alter_employee_emergency_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
