# Generated by Django 5.1.1 on 2025-07-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0017_employeeeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee'),
        ),
    ]
