# Generated by Django 5.1.1 on 2025-07-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0019_rename_parent_employee_reports_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='reports_to',
            new_name='report_to',
        ),
    ]
