# Generated by Django 5.1.1 on 2025-07-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0020_rename_reports_to_employee_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='finger_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kind',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CONTRACT', 'CONTRACT'), ('TEMPORARY', 'Temporary'), ('SEASONAL', 'Seasonal'), ('VOLUNTEER', 'Volunteer'), ('INTERN', 'Intern'), ('TRAINEE', 'Trainee'), ('OTHER', 'Other')], default='FULL_TIME', max_length=50),
        ),
    ]
