# Generated by Django 5.1.1 on 2025-07-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0021_employee_employee_id_alter_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_joind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeebankinginformation',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings')], max_length=50, null=True),
        ),
    ]
