# Generated by Django 5.1.1 on 2025-07-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0022_employee_is_joind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
        ),
    ]
