# Generated by Django 5.1.1 on 2025-07-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0023_employeeeducation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankinginformation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='company',
        ),
    ]
