# Generated by Django 5.1.1 on 2025-07-24 14:51

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import employeeio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0024_remove_employeebankinginformation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=employeeio.django_rest.helpers.slug_helpers.get_employee_tax, unique=True)),
                ('is_the_state_other_income_tax', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('martial_status', models.CharField(choices=[('MARRIED', 'Married'), ('UN_MARRIED', 'Un Married'), ('OTHER', 'Other')], default='UN_MARRIED', max_length=50)),
                ('total_allowance', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('additional_with_holdings', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('exempt', models.CharField(blank=True, choices=[('EXEMPT', 'Exempt'), ('NOT_EXEMPT', 'Not Exempt')], null=True)),
                ('is_the_employee_exempt_from_any_state_taxes', models.BooleanField(default=False)),
                ('is_the_employee_work_in_the_state_where_live', models.BooleanField(default=False)),
                ('is_federal_with_holding', models.BooleanField(default=False)),
                ('employee_W_4_kind', models.CharField(blank=True, choices=[('YEAR_2019_OR_EARLY', 'Year 2019 Or Early'), ('YEAR_2020_OR_LETTER', 'Year 2020 Or Letter')], null=True)),
                ('is_multiple_jobs_or_spouse_works', models.BooleanField(default=False)),
                ('total_other_income', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('extra_with_holding', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('holding_status', models.CharField(blank=True, choices=[('SINGLE_OR_MARRIED_FILING_SEPARATLEY', 'Single Or Married Filing Separatley'), ('MARRIED_FILING_JOINTLY_OR_QUALIYING_WIDOW', 'Married Filing Jointly Or Qualifying Widow'), ('HEAD_OF_HOUSHOLD', 'Head Of Houshold'), ('EXEMPT', 'Exempt')], null=True)),
                ('deduction', models.CharField(blank=True, null=True)),
                ('exempt_from_with_holding', models.CharField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
