# Generated by Django 5.1.1 on 2025-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0025_employeetax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_joind',
            field=models.BooleanField(default=False),
        ),
    ]
