# Generated by Django 5.1.1 on 2025-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0026_alter_employee_is_joind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetax',
            name='holding_status',
            field=models.CharField(blank=True, choices=[('SINGLE_OR_MARRIED_FILING_SEPARATLEY', 'Single Or Married Filing Separatley'), ('MARRIED_FILING_JOINTLY_OR_QUALIYING_WIDOW', 'Married Filing Jointly Or Qualifying Widow'), ('HEAD_OF_HOUSHOLD', 'Head Of Houshold'), ('EXEMPT', 'Exempt')], max_length=50, null=True),
        ),
    ]
