# Generated by Django 5.1.1 on 2025-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0027_alter_employeetax_holding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetax',
            name='deduction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='employee_W_4_kind',
            field=models.CharField(blank=True, choices=[('YEAR_2019_OR_EARLY', 'Year 2019 Or Early'), ('YEAR_2020_OR_LETTER', 'Year 2020 Or Letter')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='exempt',
            field=models.CharField(blank=True, choices=[('EXEMPT', 'Exempt'), ('NOT_EXEMPT', 'Not Exempt')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='exempt_from_with_holding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
