# Generated by Django 5.1.1 on 2025-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0028_alter_employeetax_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_double_over_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_holiday_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_kind',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'HOURLY'), ('COMMISSION', 'Commission')], default='SALARY', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_frequency',
            field=models.CharField(choices=[('PER_YEAR', 'Per Year'), ('PER_MONTH', 'Per Month'), ('PER_WEEK', 'Per Week')], default='PER_MONTH', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_day_per_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_hour_per_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_rate_per_hour',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_salary',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
