# Generated by Django 5.1.1 on 2025-07-25 09:53

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import employeeio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0029_employee_is_bonus_employee_is_double_over_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=employeeio.django_rest.helpers.slug_helpers.get_employee_earning_tax, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50)),
                ('pay_kind', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('REIMBURSEMENT', 'Reimbursement'), ('CASH_TIPS', 'Cash Tips'), ('PAYCHECK_TIPS', 'Paycheck Tips'), ('CLERGY_HOUSING_CASH', 'Clergy Housing (Cash)'), ('CLERGY_HOUSING_IN_KIND', 'Clergy Housing (In-Kind)'), ('NONTAXABLE_PER_DIEM', 'Nontaxable Per Diem'), ('GROUP_TERM_LIFE_INSURANCE', 'Group-Term Life Insurance'), ('S_CORP_OWNERS_HEALTH_INSURANCE', 'S-Corp Owners Health Insurance'), ('COMPANY_HSA_CONTRIBUTION', 'Company HSA Contribution'), ('PERSONAL_USE_OF_COMPANY_CAR', 'Personal Use of Company Car'), ('BEREAVEMENT_PAY', 'Bereavement Pay'), ('OTHER_EARNINGS', 'Other Earnings'), ('NEW_YORK_HWB_BONUS_PROGRAM', 'New York (HWB) Worker Bonus Program')], default='ALLOWANCE', max_length=50)),
                ('total_recurring_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
