# Generated by Django 5.1.1 on 2025-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0030_employeeearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeearning',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
