# Generated by Django 5.1.1 on 2025-07-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0031_employeeearning_description'),
        ('payrollio', '0009_alter_payschedule_first_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollio.payschedule'),
        ),
    ]
