# Generated by Django 5.1.1 on 2025-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0032_employee_pay_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetax',
            name='claim_depends',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employeetax',
            name='is_employee_exempt_from_federal_tax',
            field=models.BooleanField(default=True),
        ),
    ]
