# Generated by Django 5.1.1 on 2025-07-26 07:54

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import employeeio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0033_employeetax_claim_depends_and_more'),
        ('payrollio', '0009_alter_payschedule_first_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDeductionContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=employeeio.django_rest.helpers.slug_helpers.get_employee_deduction_and_contribution, unique=True)),
                ('tax_option', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_deduction_kind', models.CharField(choices=[('FLAT_AMOUNT', 'Flat Amount'), ('PERCENT_OF_GROSS_PAY', 'Percent Of Gross Pay'), ('PER_HOUR_WORKED', 'Per Hour Worked')], default='FLAT_AMOUNT', max_length=50)),
                ('total_employee_deduction_per_pay_check', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_maximum_annual_employee_deduction', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('company_contribution_kind', models.CharField(choices=[('FLAT_AMOUNT', 'Flat Amount'), ('PERCENT_OF_GROSS_PAY', 'Percent Of Gross Pay'), ('PER_HOUR_WORKED', 'Per Hour Worked')], default='FLAT_AMOUNT', max_length=50)),
                ('total_company_contribution_per_pay_check', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('total_maximum_annual_company_contribution', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('deduction_and_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payrollio.deductionandcontributions')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
