# Generated by Django 5.1.1 on 2025-07-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0034_employeedeductioncontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedeductioncontribution',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50),
        ),
    ]
