# Generated by Django 5.1.1 on 2025-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0036_employeegarnishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegarnishment',
            name='kind',
            field=models.CharField(choices=[('CHILD_SPOUSAL_SUPPORT', 'Child/Spousal Support'), ('FEDERAL_TAX_LEVY', 'Federal tax Levy'), ('OTHER_GARNISHMENT', 'Other Garnishment')], default='OTHER_GARNISHMENT', max_length=50),
        ),
    ]
