# Generated by Django 5.1.1 on 2025-07-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0037_alter_employeegarnishment_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_day_per_day',
            new_name='total_day_per_week',
        ),
    ]
