# Generated by Django 5.1.1 on 2025-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0039_employeeworkexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkexperience',
            name='kind',
            field=models.CharField(choices=[('HISTORY', 'History'), ('EXPERIENCE', 'Experience')], default='EXPERIENCE', max_length=50),
        ),
    ]
