# Generated by Django 5.1.1 on 2025-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0040_employeeworkexperience_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_boarding_kind',
            field=models.CharField(choices=[('SELF_ONBOARD_WITH_I9', 'Employee self onboard with form i-9'), ('SELF_ONBOARD', 'Employee self onboard'), ('MANUAL_ENTRY', "I'll enter all their info myself")], default='MANUAL_ENTRY', max_length=50),
        ),
    ]
