# Generated by Django 5.1.1 on 2025-07-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0041_employee_on_boarding_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_joind',
            new_name='is_joined',
        ),
    ]
