# Generated by Django 5.1.1 on 2025-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0042_rename_is_joind_employee_is_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='citizenship_kind',
            field=models.CharField(choices=[('US citizen', 'US citizen'), ('Lawful permanent resident', 'Lawful permanent resident'), ('Noncitizen nation of the U.S', 'Noncitizen nation of the U.S'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='foreign_passort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='from_i_94',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sign_w4_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uscis_or_alien_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
