# Generated by Django 5.1.1 on 2025-08-02 10:48

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0043_employee_citizenship_kind_employee_foreign_passort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sign_w4_full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='w4_signature',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='employee/signatures', verbose_name='Signature'),
        ),
    ]
