# Generated by Django 5.1.1 on 2025-08-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceio', '0006_alter_holiday_created_by'),
        ('employeeio', '0044_remove_employee_sign_w4_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='authorized_to_work_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_set', to='attendanceio.holiday'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_included_social_security_number_from_i9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_not_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
