# Generated by Django 5.1.1 on 2025-08-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0045_employee_authorized_to_work_until_employee_holiday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='foreign_passort',
            new_name='foreign_passport',
        ),
    ]
