# Generated by Django 5.1.1 on 2025-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0046_rename_foreign_passort_employee_foreign_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='citizenship_kind',
            field=models.CharField(choices=[('US_CITIZEN', 'US citizen'), ('LAWFUL_RESIDENT', 'Lawful permanent resident'), ('NONCITIZEN_OF_USA', 'Noncitizen nation of the U.S'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
