# Generated by Django 5.1.1 on 2025-08-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0047_alter_employee_citizenship_kind'),
        ('payrollio', '0021_payrollworklocation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_location',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='payrollio.payrollworklocation'),
        ),
    ]
