# Generated by Django 5.1.1 on 2025-08-16 09:03

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0048_remove_employee_work_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/employees', verbose_name='Image'),
        ),
    ]
