# Generated by Django 5.1.1 on 2025-08-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0049_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_same_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='terminate_kind',
            field=models.CharField(choices=[('FULL', 'Full'), ('PARTIALLY', 'Partially'), ('RESIGNATION', 'Resignation'), ('RETIREMENT', 'Retirement'), ('JOB_ABANDONMENT', 'Job Abandonment'), ('FAILURE_TO_RETURN', 'Failure to Return'), ('MUTUAL_SEPARATION', 'Mutual Separation'), ('LAYOFF', 'Layoff'), ('POSITION_ELIMINATION', 'Position Elimination'), ('END_TEMP_ASSIGNMENT', 'End Temporary Assignment'), ('CONTRACT_END', 'Contract End'), ('PERFORMANCE', 'Performance'), ('MISCONDUCT', 'Misconduct / Policy Violation'), ('ATTENDANCE', 'Attendance'), ('PROBATIONARY_DISMISSAL', 'Probationary Sismissal'), ('DEATH', 'Death'), ('MEDICAL_SEPARATION', 'Medical Separation'), ('CONSTRUCTIVE_DISCHARGE', 'Constructive Discharge')], default='FULL', max_length=50),
        ),
    ]
