# Generated by Django 5.1.1 on 2025-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0050_employee_is_same_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_banking_info_verified',
            field=models.BooleanField(default=False),
        ),
    ]
