# Generated by Django 5.1.1 on 2026-02-23 05:01

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import employeeio.django_rest.helpers.slug_helpers
import employeeio.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_last_seen'),
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0051_employee_is_banking_info_verified'),
        ('supplierio', '0005_alter_supplier_billing_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=employeeio.django_rest.helpers.slug_helpers.get_employee_expense_report_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_INFO', 'Needs Info')], default='DRAFT', max_length=50)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=employeeio.models.get_employee_expense_report_receipt_path)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('currency', models.CharField(blank=True, default='USD', max_length=50, null=True)),
                ('vendor_supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('chart_of_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_expense_reports', to='accounts.chartofaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_expense_reports', to='companyio.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='employeeio.employee')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_expense_reports', to='supplierio.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
