# Generated by Django 5.1.1 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employeeio", "0054_expense_report_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeexpensereport",
            name="file_path",
            field=models.URLField(blank=True, null=True),
        ),
    ]
