# Generated by Django 5.1.1 on 2026-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0055_employeeexpensereport_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetax',
            name='is_employee_exempt_from_family_paid_leave',
            field=models.BooleanField(default=False),
        ),
    ]
