# Generated by Django 5.1.1 on 2026-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0056_employeetax_is_employee_exempt_from_family_paid_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexpensereport',
            name='status_previous',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEW', 'Review'), ('REQUEST_CHANGES', 'Request Changes'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], max_length=50, null=True),
        ),
    ]
