# Generated by Django 5.1.1 on 2026-04-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0058_employeeexpensereport_purchase_and_payment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexpensereport',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expense_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeexpensereport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_expense_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeexpensereport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expense_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
