# Generated by Django 5.1.1 on 2026-05-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeio', '0062_employeetax_w4_credit_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_address',
        ),
    ]
