# Generated by Django 5.1.1 on 2026-06-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0020_remove_company_legal_address'),
        ('employeeio', '0065_backfill_employee_is_access_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companyio.company'),
        ),
    ]
