# Generated by Django 5.1.1 on 2024-11-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brandio', '0001_initial'),
        ('productio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandconnector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productio.product'),
        ),
    ]
