# Generated by Django 5.1.1 on 2025-03-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandio', '0002_initial'),
        ('productio', '0009_alter_product_sale_price_alter_product_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandconnector',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productio.product'),
        ),
    ]
