# Generated by Django 5.1.1 on 2024-12-11 07:11

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import salesio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencyio', '0002_agency_start_of_period'),
        ('companyio', '0003_alter_companyuser_role'),
        ('customerio', '0006_alter_customer_currency'),
        ('employeeio', '0006_employeesalary_company_alter_employeesalary_employee_and_more'),
        ('productio', '0005_remove_productbundle_product_productbundleconnector'),
        ('termio', '0002_alter_term_kind_alter_termconnector_kind'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_slug, unique=True)),
                ('invoice_id', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('email', models.TextField(help_text='Signature email with a comma')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_kind', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='FLAT', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('tax_kind', models.CharField(choices=[('INCLUSIVE', 'Inclusive of Tax'), ('EXCLUSIVE', 'Exclusive of Tax'), ('NO_TAX', 'No Tax')], default='NO_TAX', max_length=20)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_invoice', models.BooleanField(default=False)),
                ('is_estimated', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termio.term')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_item_slug, unique=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productio.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesio.sale')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyio.agencytax')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
