# Generated by Django 5.1.1 on 2024-12-21 08:38

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import salesio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chartofaccount_currency'),
        ('customerio', '0006_alter_customer_currency'),
        ('employeeio', '0001_initial'),
        ('paymentio', '0001_initial'),
        ('salesio', '0001_initial'),
        ('wirehouseio', '0004_warehouse_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='bill_date',
            new_name='invoice_date',
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_receipt_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.chartofaccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wirehouseio.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SaleReceiptConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_receipt_connector_slug, unique=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesio.sale')),
                ('sale_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesio.salereceipt')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
