# Generated by Django 5.1.1 on 2024-12-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0002_rename_bill_date_sale_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereceiptconnector',
            name='sale_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='salesio.salereceipt'),
        ),
    ]
