# Generated by Django 5.1.1 on 2025-01-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
        ('salesio', '0003_alter_salereceiptconnector_sale_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale'), ('REFUND', 'Refund')], default='SALE', max_length=50),
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='refund_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_from_set', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='salereceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='deposit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_to_set', to='accounts.chartofaccount'),
        ),
    ]
