# Generated by Django 5.1.1 on 2025-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0004_salereceipt_cheque_number_salereceipt_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='refund_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('FULL_REFUNDED', 'Full Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refund_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
