# Generated by Django 5.1.1 on 2025-01-06 10:22

import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import salesio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chartofaccount__id'),
        ('companyio', '0004_alter_companyshift_created_by'),
        ('creditnoteio', '0003_alter_creditnote_kind'),
        ('customerio', '0006_alter_customer_currency'),
        ('employeeio', '0006_employeesalary_company_alter_employeesalary_employee_and_more'),
        ('paymentio', '0003_paymentinformation_subscription'),
        ('salesio', '0005_saleitem_refund_quantity_saleitem_refund_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePaymentReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_payment_receive_slug, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('email', models.TextField(help_text='Signature email with a comma')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('PARTIALLY', 'Partially'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerio.customer')),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paymentio.paymentmethod')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SalePaymentReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_payment_receive_item_slug, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REMOVED', 'Removed'), ('PARTIALLY', 'Partially'), ('COMPLETED', 'Completed')], default='DRAFT')),
                ('model_kind', models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_NOTE', 'Credit Note')])),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditnoteio.creditnote')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.sale')),
                ('sale_payment_receive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesio.salepaymentreceive')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
