# Generated by Django 5.1.1 on 2025-01-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0006_salepaymentreceive_salepaymentreceiveitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepaymentreceiveitem',
            name='model_kind',
            field=models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_NOTE', 'Credit Note')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salepaymentreceiveitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REMOVED', 'Removed'), ('PARTIALLY', 'Partially'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
