# Generated by Django 5.1.1 on 2025-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0007_alter_salepaymentreceiveitem_model_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REMOVED', 'Removed'), ('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=50),
        ),
    ]
