# Generated by Django 5.1.1 on 2025-01-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0008_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
