# Generated by Django 5.1.1 on 2025-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0009_sale_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
