# Generated by Django 5.1.1 on 2025-01-19 19:17

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import salesio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyio', '0005_companysetting'),
        ('paymentio', '0005_alter_paymentinformation_invoice_link'),
        ('salesio', '0010_saleitem_note'),
        ('termio', '0003_termconnector_sale_alter_term_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_setting_slug, unique=True)),
                ('preferred_delivery_method', models.CharField(blank=True, choices=[('PRINT_LATER', 'Print Later'), ('SEND_LATER', 'Send Later')], max_length=50, null=True)),
                ('is_shipping', models.BooleanField(default=False)),
                ('is_customer_transaction_number', models.BooleanField(default=False)),
                ('is_service_date', models.BooleanField(default=False)),
                ('is_discount', models.BooleanField(default=False)),
                ('is_deposit', models.BooleanField(default=False)),
                ('is_tag', models.BooleanField(default=False)),
                ('invoice_payment', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('ACCRUAL', 'Accrual')], max_length=50, null=True)),
                ('is_product_and_service', models.BooleanField(default=False)),
                ('is_sku', models.BooleanField(default=False)),
                ('is_quantity_and_price', models.BooleanField(default=False)),
                ('is_available_stock', models.BooleanField(default=False)),
                ('is_reminder', models.BooleanField(default=False)),
                ('is_show_transactions_as_single_line', models.BooleanField(default=False)),
                ('is_include_transaction_details', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('prefered_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentio.paymentmethod')),
                ('prefered_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='termio.term')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
