# Generated by Django 5.1.1 on 2025-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0011_salesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepaymentreceiveitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
