# Generated by Django 5.1.1 on 2025-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0012_salepaymentreceiveitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='term',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
