# Generated by Django 5.1.1 on 2025-02-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0013_remove_sale_term_saleitem_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepaymentreceiveitem',
            name='used_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
