# Generated by Django 5.1.1 on 2025-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0014_salepaymentreceiveitem_used_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
