# Generated by Django 5.1.1 on 2025-02-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0015_alter_sale_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
