# Generated by Django 5.1.1 on 2025-02-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0016_alter_sale_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deposit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='due_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_vat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='refund_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salepaymentreceive',
            name='deposit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salepaymentreceive',
            name='due_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salepaymentreceive',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salepaymentreceiveitem',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salepaymentreceiveitem',
            name='used_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='deposit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='due_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salereceipt',
            name='total_vat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
