# Generated by Django 5.1.1 on 2025-03-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0005_alter_paymentinformation_invoice_link'),
        ('salesio', '0017_alter_sale_deposit_alter_sale_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereceipt',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentio.paymentmethod'),
        ),
    ]
