# Generated by Django 5.1.1 on 2025-03-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_chartofaccount_is_fixed'),
        ('salesio', '0018_alter_salereceipt_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
    ]
