# Generated by Django 5.1.1 on 2025-03-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_chartofaccount_is_fixed'),
        ('salesio', '0019_sale_charter_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='charter_account',
        ),
        migrations.AddField(
            model_name='sale',
            name='payable_charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable_set', to='accounts.chartofaccount'),
        ),
        migrations.AddField(
            model_name='sale',
            name='receivable_charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable_set', to='accounts.chartofaccount'),
        ),
    ]
