# Generated by Django 5.1.1 on 2025-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0020_remove_sale_charter_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
