# Generated by Django 5.1.1 on 2025-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0021_alter_sale_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereceipt',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
