# Generated by Django 5.1.1 on 2025-05-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentio', '0005_alter_paymentinformation_invoice_link'),
        ('salesio', '0022_alter_salereceipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_sale_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='kind',
            field=models.CharField(choices=[('SALE', 'Sale'), ('REFUND', 'Refund')], default='SALE', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentio.paymentmethod'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
