# Generated by Django 5.1.1 on 2025-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyio', '0011_remove_currencyconnector_sale_receipt_and_more'),
        ('journalio', '0025_remove_journalentry_sale_receipt'),
        ('notificationio', '0007_remove_notification_sale_receipt_and_more'),
        ('salesio', '0023_sale_is_sale_receipt_sale_kind_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereceiptconnector',
            name='sale_receipt',
        ),
        migrations.RemoveField(
            model_name='salereceiptconnector',
            name='sale',
        ),
        migrations.DeleteModel(
            name='SaleReceipt',
        ),
        migrations.DeleteModel(
            name='SaleReceiptConnector',
        ),
    ]
