# Generated by Django 5.1.1 on 2025-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0023_sale_is_sale_receipt_sale_kind_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='email',
            field=models.JSONField(default={'bcc_emails': '', 'cc_emails': '', 'customer_email': ''}),
        ),
    ]
