# Generated by Django 5.1.1 on 2025-06-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0024_alter_sale_email'),
        ('salesio', '0024_remove_salereceiptconnector_sale_receipt_and_more'),
    ]

    operations = [
    ]
