# Generated by Django 5.1.1 on 2025-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0025_merge_20250603_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='email',
            field=models.JSONField(default={'bcc_emails': [], 'cc_emails': [], 'customer_email': ''}),
        ),
    ]
