# Generated by Django 5.1.1 on 2025-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0027_alter_sale_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepaymentreceive',
            name='email',
            field=models.JSONField(default={'bcc_emails': '', 'cc_emails': '', 'customer_email': ''}),
        ),
    ]
