# Generated by Django 5.1.1 on 2025-06-23 08:53

import common.django_rest.helpers.json_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0028_alter_salepaymentreceive_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
        migrations.AlterField(
            model_name='salepaymentreceive',
            name='email',
            field=models.JSONField(default=common.django_rest.helpers.json_helpers.email_helpers),
        ),
    ]
