# Generated by Django 5.1.1 on 2025-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0029_alter_sale_email_alter_salepaymentreceive_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_item_tax',
            field=models.BooleanField(default=True),
        ),
    ]
