# Generated by Django 5.1.1 on 2025-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0030_saleitem_is_item_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='is_item_tax',
            field=models.BooleanField(default=False),
        ),
    ]
