# Generated by Django 5.1.1 on 2025-09-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0031_alter_saleitem_is_item_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='is_item_tax',
            new_name='is_tax',
        ),
    ]
