# Generated by Django 5.1.1 on 2025-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0032_rename_is_item_tax_saleitem_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='auto_sales_tax',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
