# Generated by Django 5.1.1 on 2025-10-27 11:15

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import salesio.django_rest.helpers.slug_helpers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0010_agency_state'),
        ('companyio', '0016_companydesignation_code_and_more'),
        ('employeeio', '0051_employee_is_banking_info_verified'),
        ('salesio', '0033_sale_auto_sales_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=salesio.django_rest.helpers.slug_helpers.get_sale_agency_tax_slug, unique=True)),
                ('sales_tax_period', models.CharField(blank=True, max_length=250, null=True)),
                ('sales_tax_due_date', models.DateField(blank=True, null=True)),
                ('total_sales_tax', models.DecimalField(decimal_places=3, default=0.0, max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAID', 'Paid'), ('OVER_DUE', 'Over Due'), ('OPEN', 'Open'), ('DUE', 'Due')], default='DRAFT', max_length=50)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyio.agency')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeio.employee')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
