# Generated by Django 5.1.1 on 2025-10-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_name'),
        ('salesio', '0034_salestax'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestax',
            name='charter_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chartofaccount'),
        ),
    ]
