# Generated by Django 5.1.1 on 2025-10-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0035_salestax_charter_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='is_tax',
            field=models.BooleanField(default=True),
        ),
    ]
