# Generated by Django 5.1.1 on 2025-10-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0036_alter_saleitem_is_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='is_tax',
            field=models.BooleanField(default=False),
        ),
    ]
