# Generated by Django 5.1.1 on 2026-07-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringio', '0004_recurringtemplate_auto_email_and_more'),
        ('salesio', '0037_alter_saleitem_is_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_estimates', to='recurringio.recurringtemplate'),
        ),
    ]
