# Generated by Django 5.1.15 on 2026-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesio', '0038_sale_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tax_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
