# Generated by Django 5.1.1 on 2024-11-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerio', '0003_customer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
