# Generated by Django 5.1.15 on 2026-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerio', '0008_customer_charter_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], default='DRAFT', max_length=50, null=True),
        ),
    ]
