# Generated by Django 5.1.1 on 2024-11-21 09:11

import agencyio.django_rest.helpers.slug_helpers
import autoslug.fields
import datetime
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_historicaluser_is_admin_user_is_admin'),
        ('companyio', '0003_alter_companyuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=agencyio.django_rest.helpers.slug_helpers.get_agency_slug, unique=True)),
                ('filling_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=50)),
                ('reporting_method', models.CharField(choices=[('ACCRUAL', 'Accrual'), ('CASH', 'Cash')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REMOVED', 'Removed'), ('ACTIVE', 'Active'), ('PENDING', 'Pending')], max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyio.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AgencyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=agencyio.django_rest.helpers.slug_helpers.get_agency_tax_slug, unique=True)),
                ('rate', models.FloatField()),
                ('is_single', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyio.agency')),
                ('purchase_tax_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_account_set', to='accounts.chartofaccount')),
                ('sales_tax_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_tax_account_set', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
