# Generated by Django 5.1.1 on 2024-11-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='start_of_period',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True),
        ),
    ]
