# Generated by Django 5.1.1 on 2025-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0002_agency_start_of_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='filling_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
    ]
