# Generated by Django 5.1.1 on 2025-06-27 10:10

import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('agencyio', '0003_alter_agency_filling_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytax',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agencyio.agencytax'),
        ),
        migrations.AlterField(
            model_name='agencytax',
            name='purchase_tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_account_set', to='accounts.chartofaccount'),
        ),
        migrations.CreateModel(
            name='AgencyTaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('taxes', models.ManyToManyField(blank=True, related_name='tax_groups', to='agencyio.agencytax')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
