# Generated by Django 5.1.1 on 2025-07-01 10:41

import agencyio.django_rest.helpers.slug_helpers
import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_chartofaccount_bank_balance_chartofaccount_bank_id'),
        ('agencyio', '0004_agencytax_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencytax',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencytax',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='agencytax',
            name='purchase_tax_account',
        ),
        migrations.RemoveField(
            model_name='agencytax',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='agencytax',
            name='sales_tax_account',
        ),
        migrations.CreateModel(
            name='AgencyTaxSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=agencyio.django_rest.helpers.slug_helpers.get_group_tax_slug, unique=True)),
                ('nickname', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyio.agency')),
                ('sales_tax_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_tax_account_set', to='accounts.chartofaccount')),
                ('taxes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_groups', to='agencyio.agencytax')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='AgencyTaxGroup',
        ),
    ]
