# Generated by Django 5.1.1 on 2025-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0005_remove_agencytax_agency_remove_agencytax_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytaxset',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
