# Generated by Django 5.1.1 on 2025-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0006_alter_agencytaxset_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytax',
            name='total_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
