# Generated by Django 5.1.1 on 2025-07-03 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0007_agencytax_total_rate'),
        ('companyio', '0014_remove_company_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencytax',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyio.company'),
        ),
    ]
