# Generated by Django 5.1.1 on 2025-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0008_agencytax_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencytaxset',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=19),
        ),
    ]
