# Generated by Django 5.1.1 on 2025-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyio', '0009_alter_agencytaxset_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
