# Generated by Django 5.1.1 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatio", "0002_chatroom_chatroommessage_chatroommember_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("FILE", "File"),
                    ("VOICE", "Voice"),
                    ("EXPENSE_DATA", "Expense Data"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatroommessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("FILE", "File"),
                    ("VOICE", "Voice"),
                    ("EXPENSE_DATA", "Expense Data"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
