# Generated by Django 5.1.1 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatio', '0003_message_type_expense_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_expense_policy_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
