# Generated by Django 5.1.1 on 2026-04-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatio', '0004_chatroom_is_expense_policy_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='origin_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to='chatio.chatroommessage'),
        ),
    ]
