# Generated by Django 5.1.1 on 2026-04-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatio', '0005_chatroommessage_origin_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommessage',
            options={'ordering': ['-timestamp']},
        ),
    ]
